### ISSUE TITLE
I am not able to understand the specs control flow 

### ISSUE THREAD

**Issue by sasankasomasila** [angular/protractor#2264] opened 2015-06-17 20:55 UTC
I have the config file with the specs mentioned below.

specs: [
'test0.js',
'test1.js',

.

.

.
'create-batchsummary.js'
],

in which from the top first and second .js files are holding the tests and the last one would be used for creating a summary. But when i run this config file using protractor, "create-batchsummary.js" is being executed just before the last test script.

If we have 3 test scripts. The summary generated only for the first 2.

Can anyone help me resolve this issue.

**Comment by hankduan** [comment] 2015-06-25 18:07
Without looking into the code, I believe specs should execute in order. However, this is not the contract behavior, and you should never depend on it. You're much better off doing the summary either in a jasmine reporter, or in a onCleanup script.

**Comment by juliemr** [comment] 2015-06-29 21:28
Correct, there is no guarantee that the files are executed in the order they are listed. Closing this, since it's working as intended - please try the solutions that Hank listed.

**Closed by juliemr** 2015-06-29 21:28 UTC
Labels: needs: more info
