### ISSUE TITLE
NodeJS 8: _debugger module not found during pause

### ISSUE THREAD

**Issue by Mamoru1234** [angular/protractor#4390] opened 2017-07-17 18:55 UTC
Bug report
---

- Node Version: `8.1.4`
- Protractor Version: `5.1.2`
- Angular Version: `NO`
- Browser(s): `Chrome  59.0.3071.115 (Official Build) (64-bit)`
- Operating System and Version `Ubuntu 17.04`
- Repo with STR
https://github.com/Mamoru1234/protractor-bug (Sorry for naming)
- Output from running the test:
Error: Cannot find module '_debugger'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/alexei/temp/protractor-bug/node_modules/protractor/built/debugger/debuggerCommons.js:1:82)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

- Steps to reproduce the bug
```
npm i 
npm run selenium-setup
npm run protractor
```

**Comment by Mamoru1234** [comment] 2017-07-17 18:57
Actually, I spend some time reviewing my node_module(s) and can't find _debigger module anywhere.
As well as some require enhancement, it looks like native require is passed to debugger sandbox.

**Comment by wswebcreation** [comment] 2017-07-19 05:02
Hi @Mamoru1234 

Tnx for the issue and for the repo. 
This issue has to do with NodeJS 8. Protractor isn't officially supporting it currently. If you (downgrade to 6.9.x, I use NVM to easily switch) you will see it is working again.

This needs to be something for a future release in which Protractor will support NodeJS 8

**Comment by Mamoru1234** [comment] 2017-07-19 11:44
@wswebcreation What is the steps to get Node v8 official supported?

**Comment by wswebcreation** [comment] 2017-07-19 11:51
Hi @Mamoru1234 

I've asked it to the core team. Will post it here if I hear something.

**Comment by marandageist** [comment] 2017-08-02 21:42
Dupe of https://github.com/angular/protractor/issues/4307

**Comment by NickTomlin** [comment] 2017-08-02 21:46
I'm going to go ahead and collapse this so consolidate and track in #4307 @wswebcreation feel free to re-open if you'd like to keep things split out.

**Closed by NickTomlin** 2017-08-02 21:46 UTC

**Comment by anarang** [comment] 2018-02-15 14:44
I am facing the same issue and unable to use elementExplorer with protractor.

Node version: v8.9.1
Protractor version: Version 5.1.1

 $ protractor --elementExplorer
(node:20299) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[20:11:30] I/local - Starting selenium standalone server...
[20:11:33] I/local - Selenium standalone server started at http://192.168.1.41:51378/wd/hub
[20:11:37] I/protractor -
[20:11:37] I/protractor - ------- Element Explorer -------
[20:11:37] I/protractor - Starting WebDriver debugger in a child process. Element Explorer is still beta, please report issues at github.com/angular/protractor
[20:11:37] I/protractor -
[20:11:37] I/protractor - Type <tab> to see a list of locator strategies.
[20:11:37] I/protractor - Use the `list` helper function to find elements by strategy:
[20:11:37] I/protractor -   e.g., list(by.binding('')) gets all bindings.
[20:11:37] I/protractor -
module.js:538
    throw err;
    ^

Error: Cannot find module '_debugger'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/anisha/.npm-packages/lib/node_modules/protractor/built/debugger/debuggerCommons.js:1:82)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
[20:11:38] I/local - Shutting down selenium standalone server.'

Any solution to this yet? I see a couple of other issues but do not see any official solution yet. Any help is appreciated.

**Comment by kshrestha99** [comment] 2020-06-07 00:12
This issue is still happeneing...any one know why it is not resolved yet?
