### ISSUE TITLE
Protractor pause() debug mode does not work for cucumber framework

### ISSUE THREAD

**Issue by jlin412** [angular/protractor#1790] opened 2015-02-07 21:06 UTC
I am testing with 1.6.0 and 1.6.1 protractor with cucumber.js 0.4.7 on mac.
When I use browser.pause(), it will pause the test but will not take any command
``` shell
------- WebDriver Debugger -------
 ready

press c to continue to the next webdriver command
press d to continue to the next debugger statement
type "repl" to enter interactive mode
type "exit" to break out of interactive mode
press ^C to exit

-- WebDriver control flow schedule 
 |- waiting for debugger to attach
 |---at World.<anonymous> (/.../features/step_definitions/common_steps.js:29:37)
 |- WebDriver.getTitle()
 |---at World.<anonymous> (/.../features/step_definitions/common_steps.js:30:13)
wd-debug> repl
c
d
exit
^CROSELCXB0073323:redbox_angular linj$ 
```
The only command will work is ^C but it will terminate the test instead of continue to finish the rest of steps and scenarios.  I would like to see 'repl' and '^C' to work with cucumber framework.

**Comment by hankduan** [comment] 2015-02-08 00:28
Can you test jasmine quickly to see if the issue is with your environment+protractor or cucumber+protractor? 

just do something like 

```javascript
describe('foo', function() {
  if('bar', function() {
    browser.get('http://www.angularjs.org');
    browser.pause();
    $('html').getText().then(console.log);
  };
});
```

**Comment by jlin412** [comment] 2015-02-09 02:31
I tested jasmine code and it is working for jasmine version.
It seems that it is only not working for cucumber+pause.

**Comment by okcompute** [comment] 2015-03-18 09:52
I have the same issue with pause() on OS X Yosemite (**10.10.3**). I'm not using cucumber. Just trying to use pause() while going over the Angular tutorial. 

**Note**: I modified the tutorial to use latest protractor version(**1.8.0**). I had to because of another issue with chromedriver pointing to a Windows executable (i.e. "chromedriver.exe").

**Comment by ctrees** [comment] 2015-03-21 21:09
I just ran into the same issue.
OSX 10.10.2

protractor --version
Version 1.6.1

node --version
v0.12.0

cucumber-js --version
0.4.7

**Comment by hankduan** [comment] 2015-03-21 22:59
I think this issue is also a dup of this (https://github.com/angular/protractor/issues/1890). Can everyone who encountered this issue confirm that they are using node > 0.10.30?

**Comment by ctrees** [comment] 2015-03-21 23:37
Thanks @hankduan I'll attempt the downgrade you suggested on refer link and post back to that and this link as soon as I get a chance

**Comment by henrygrover** [comment] 2015-03-27 17:02
@hankduan I can confirm. Reverting from node 0.10.35 to 0.10.30 corrected the problem.

**Comment by hankduan** [comment] 2015-03-27 18:29
Thanks for confirmation. I'm going to close this issue. Please track here: https://github.com/angular/protractor/issues/1890

**Closed by hankduan** 2015-03-27 18:29 UTC
Labels: framework: cucumber, PRs plz!

**Comment by henrygrover** [comment] 2015-03-27 21:16
@hankduan Hate to do this to you, but the problem seems to be back now, even in 0.10.30.  Not sure what changed to cause it.

`
[root@localhost test]# nvm use 0.10.30
Now using node v0.10.30
[root@localhost test]# nvm ls
->     v0.10.30
       v0.10.35
default -> 0.10.35 (-> v0.10.35)
stable -> 0.10 (-> v0.10.35) (default)
[root@localhost test]# protractor protractor-conf.js --specs features/FileUpload.feature 
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
Selenium standalone server started at http://192.168.1.103:36685/wd/hub
.Hit SIGUSR1 - starting debugger agent.
debugger listening on port 5858
Starting WebDriver debugger in a child process. Pause is still beta, please report issues at github.com/angular/protractor

------- WebDriver Debugger -------
 ready

press c to continue to the next webdriver command
press d to continue to the next debugger statement
type "repl" to enter interactive mode
type "exit" to break out of interactive mode
press ^C to exit

repl
c
d
exit
^C[root@localhost test]#
`

**Comment by jonricaurte** [comment] 2015-04-17 00:06
Yep, this is happening again. Wonder if it has anything to do with updating to the latest version of webdriver.

**Comment by solcre** [comment] 2015-08-05 16:54
This happens to me on:

Ubuntu 14.04
Node: 0.12.3
Protractor: 2.0.0
Cucumber: 0.4.9
