### ISSUE TITLE
Unable to navigate to URL in Safari

### ISSUE THREAD

**Issue by spatchamatla** [angular/protractor#2346] opened 2015-07-14 17:53 UTC
Protractor 2.1.0
Safari 8.0.7
Webdriver 2.45.0
OSX 10.10.4
Safari extension 2.45.0

i tried with selenium-server-standalone-2.45.0 and when i run the script it navigates to the first URL but when it try to navigate to second url, it displays only about:blank and it times out with
```
ScriptTimeoutError: Timed out awaiting response to command "executeScript" after 30001 ms (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 30.10 seconds
Build info: version: '2.45.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
System info: host: 'mac.local', ip: '<>', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_45'
Driver info: org.openqa.selenium.safari.SafariDriver
Capabilities [{browserName=safari, takesScreenshot=true, javascriptEnabled=true, version=8.0.6, cssSelectorsEnabled=true, platform=MAC, secureSsl=true}]
Session ID: null

java.lang.NullPointerException
    at org.openqa.selenium.remote.RemoteWebDriver.getCurrentUrl(RemoteWebDriver.java:319)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:101)
    at com.sun.proxy.$Proxy1.getCurrentUrl(Unknown Source)
    at org.openqa.selenium.support.events.EventFiringWebDriver.getCurrentUrl(EventFiringWebDriver.java:164)
    at org.openqa.selenium.remote.server.handler.GetCurrentUrl.call(GetCurrentUrl.java:30)
    at org.openqa.selenium.remote.server.handler.GetCurrentUrl.call(GetCurrentUrl.java:1)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:168)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```
its not even navigating to second URL.Im using browser.get() to navigate to the URLs. i tested both url's manually and it works fine if i run on chrome as well.

im  to reproduce the using google and apple urls using the below code
```
describe ('Test Safari with two URLs', function() {

    var defaultSyncStatus = browser.ignoreSynchronization;

    beforeEach(function(){
        //for non angular Pages
        browser.ignoreSynchronization = true;
        browser.get('http://www.google.com');
    });

    afterEach(function() {
    });

    it('test with apple.com', function () {
        browser.ignoreSynchronization = defaultSyncStatus;
        browser.get('http://www.apple.com');
    });
});
```
but when i comment the ``` browser.ignoreSynchronization = defaultSyncStatus;```, it runs fine.

i can't continue running the tests in Safari since our login page is a non angular page.

**Comment by sjelin** [comment] 2015-07-14 22:06
Possible duplicate of https://github.com/angular/protractor/issues/2111

**Comment by juliemr** [comment] 2015-09-25 00:19
Dupe.

**Closed by juliemr** 2015-09-25 00:19 UTC
Labels: needs: investigation
