### ISSUE TITLE
Selenium Grid support (webdriver-manager)

### ISSUE THREAD

**Issue by nathandonato** [angular/protractor#2420] opened 2015-08-12 16:24 UTC
Currently, there is no way to start a Selenium Grid session using **webdriver-manager**. I believe it would be useful if **start** accepted a "--role" argument, which is how one specifies whether or not the machine is a Hub or a Node in a Selenium Grid network.

Here's how it works manually:

```
$ java -jar selenium-server-standalone-2.47.1.jar -role hub
```

Conceivably, webdriver-manager could accept something similar:

```
$ webdriver-manager start --role=hub
```

**Comment by juliemr** [comment] 2015-09-22 23:04
Our general thought has been that `webdriver-manager` is a quick setup for folks who want to get selenium/webdriver started quickly. We don't want to replicate every advanced option. If you're making a grid, the assumption is that you know what you're doing and don't need `webdriver-manager` to help. Is there a particular reason that this option would be helpful to include?

**Comment by juliemr** [comment] 2015-09-30 23:59
I'm aggressively closing issues that we are unable to reproduce, are support issues specific to one test, or deal with integrations with other projects that we don't directly support. If you feel you have a question, please see https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions. If you still have a bug report or feature request, please open a new issue. Thank you!

**Closed by juliemr** 2015-09-30 23:59 UTC
Labels: component: webdriver-manager, needs: more info, type: feature request

**Comment by Sereda-Fazen** [comment] 2018-03-30 06:42
Hi @juliemr! As I understood we couldn't use webdriver-manager as (selenium grid). Only one test. Am I right?
