### ISSUE TITLE
Protractor freezes when trying to locate sub-element inside .map()

### ISSUE THREAD

**Issue by jackzelenkin** [angular/protractor#2427] opened 2015-08-14 06:28 UTC
I'm trying to modify example code from [here](http://angular.github.io/protractor/#/) to parse ToDo items into a data structure.

```javascript
describe('angularjs homepage todo list', function() {
  it('should add a todo', function() {
    browser.get('https://angularjs.org');

    element(by.model('todoList.todoText')).sendKeys('write first protractor test');
    element(by.css('[value="add"]')).click();

    var todoList = element.all(by.repeater('todo in todoList.todos'));
    var todoStruct = todoList.map(function(el) {
      return {
        checkbox: el.element(by.model('todo.done')),
        label: el.element(by.tagName('span')).getText()
      };
    });

    todoStruct.then(function(resolvedTodoStruct) {
      expect(todoStruct.length).toEqual(3);
      expect(todoStruct[2].label).toEqual('write first protractor test');
    });
  });
});
```

From what I've read, map is the right choice for this kind of task. But for some reason, as soon as I try to locate sub-element inside .map(), protractor freezes. Why would it?

**Comment by nervgh** [comment] 2015-08-17 17:33
I tried localize the problem:
```js
// test.js
describe('Protractor Demo App', function() {
    browser.get('https://angularjs.org');

    element
        .all(by.repeater('todo in todoList.todos'))
        .map(function(element) {
            return; // work
            // return element; // not work
            // return element.element(by.model('todo.done')); // not work
        });
});
```

It looks like some promises not resolved and the browser freezes.

**Comment by jackzelenkin** [comment] 2015-08-17 18:35
My 2 cents. I might be wrong, but maybe problem is in fact that .element doesn't return a promise?

**Comment by nervgh** [comment] 2015-08-17 18:49
@jackzelenkin , see https://github.com/angular/protractor/blob/2.1.0/lib/element.js#L536

**Comment by jackzelenkin** [comment] 2015-08-17 19:15
That's my point. Maybe, element objects should not be "fully resolved". At least I'm not aware of what we would like to resolve in them. :)
I'm new to javascript, but is it hard to distinguish lists ([]) and dicts ({}) from ojects, elements in particular, and do not traverse the latter?

**Comment by Korobochka** [comment] 2015-08-28 16:57
This looks similar to issue #2227

**Comment by juliemr** [comment] 2016-01-14 01:37
I think this is a dupe of #2227. Closing to consolidate effort there.

**Closed by juliemr** 2016-01-14 01:37 UTC
Labels: status: needs investigation
