### ISSUE TITLE
ElementExplorer repl crashes when returning promises with no listeners

### ISSUE THREAD

**Issue by juliemr** [angular/protractor#2146] opened 2015-05-15 20:08 UTC
I need to make a minimal case, but so far, the sequence described in `interactive_test.js` is failing (and thus `npm test` is failing. I can reproduce manually with:

```
browser.get(url)
var q = require('q')
var deferred = q.defer(); setTimeout(function() {deferred.resolve(1)}, 100); deferred.promise
```

The browser crashes but the command line repl stays open.

**Comment by juliemr** [comment] 2015-05-15 23:25
Simplified: just do
```
> var d = q.defer()
> d.promise
```

**Comment by juliemr** [comment] 2015-05-18 17:53
Update: This only occurs after updating to node >0.10.30

**Comment by hankduan** [comment] 2015-05-18 21:30
I think it has to do with the fact that an unresolved $q promise (or any other promises) do not keep a process alive (see https://github.com/kriskowal/q/issues/600.)

0.10.30 was working before because of a bug in the timer, where it wouldn't actually wait for the full period.
i.e. if you run `var deferred = q.defer(); setTimeout(function() {deferred.resolve(1)}, 1000); deferred.promise` it doesn't actually wait for the 1sec, but resolves immediately.

**Comment by hankduan** [comment] 2015-05-18 21:45
For now the test is removed: https://github.com/angular/protractor/commit/c1021e5ce64f8c417e0e48a4ec911390de696aed
since it's not a real use case. Also, the test was originally conceived to test that `require` is injected, but doesn't really test it.

**Comment by juliemr** [comment] 2015-05-20 16:40
Putting in icebox since this seems unlikely to affect real users.

**Comment by juliemr** [comment] 2016-12-22 00:28
TODO(me): See if this works after my changes to the debugger for selenium 3.

**Comment by NickTomlin** [comment] 2017-03-04 17:21
I just did a quick check and the explorer hangs when running the simplified commands to reproduce on  `master`. The browser instance is still alive, but it is unresponsive to any commands issued from the repl.

I think I'm still going to close this as it's an internal edge case that isn't affecting normal users. Others should feel free to re-open if we want to keep this around though.

**Closed by NickTomlin** 2017-03-04 17:21 UTC
Labels: type: bug
