### ISSUE TITLE
Error will exit cucumber framework 

### ISSUE THREAD

**Issue by jlin412** [angular/protractor#2199] opened 2015-06-02 22:16 UTC
@jbpros In the latest 2.1.0 protractor and cucumber 0.4.9
Cucumber is exited prematurely when getting an error like below:
```
  this.When(/^something fails via exception$/, function (callback) {
    setTimeout(function () {
      throw new Error('#FAIL via exception');
    }, 20).then(callback);
  });

Error Msg:
Error: #FAIL via exception
  at [object Object]._onTimeout (/Users/linj/redbox_spa/redbox_angular/test/e2e/features/e2e/step_definitions/e2e_steps.js:614:13)
  at Timer.listOnTimeout (timers.js:110:15)

[launcher] Process exited with error code 1

```

I think that protractor swallow the error before sending back to cucumber.
Can someone investigate this?

I have a repo for reproducing this bug:
https://github.com/jlin412/cuke-tractor

**Comment by djlaplante** [comment] 2015-07-01 16:20
I am also having this problem, however in my case I have multiple feature files running. The first feature file to encounter the error throws it and fails just fine. The second one will throw the error, not fail, and then exit as shown above.

**Comment by jlin412** [comment] 2015-10-23 13:45
https://github.com/angular/protractor/pull/2615 should fix this.

**Comment by hankduan** [comment] 2015-11-04 18:33
Closing as duplicate of https://github.com/angular/protractor/issues/2100

**Closed by hankduan** 2015-11-04 18:33 UTC
Labels: framework: cucumber, PRs plz!
