### ISSUE TITLE
Allow retries in taskRunner.js

### ISSUE THREAD

**Issue by runk** [angular/protractor#2760] opened 2015-12-03 00:02 UTC
Hey there. First of all thanks for the awesome tool.

I faced an issue that very often selenium/webdriver fails for all sorts of non obvious reasons you cannot reproduce. Element invisible for fraction of second, buttons unclickable, stale elements and so forth. You cannot debug it easily. We had probably only 50% success rate of our protractor test runs because of those annoying flaky issues.

I've added some code to taskRunner.js to allow several retries. So when something weird happens we retry particular *spec*, rather than bailing execution of whole *test suite* and wasting time for re starting it again.

As a result success rate is very close to 100%. All weirdness/flakiness is ignored after one-two retries.

https://github.com/runk/protractor/blob/master/lib/taskRunner.js

Question: is it something main protractor project would be interested in? Should I send a PR or keep it only as a custom solution for my own needs? I'm more than happy wrapping it in a PR, adding tests etc.

Cheers

**Comment by NiklasMM** [comment] 2015-12-03 12:39
As someone who is regularly battling similar issues, I would more than welcome this to be a core protractor feature!

**Comment by NickTomlin** [comment] 2015-12-03 14:50
I believe this is a duplicate of [#1190](https://github.com/angular/protractor/issues/1190). I think it makes the most sense to submit your changes as a PR or continue the discussion there. This is definitely a handy thing to have :)

**Closed** 2015-12-07 20:23 UTC
Labels: status: duplicate, type: feature request
