### ISSUE TITLE
'Error: This driver instance does not have a valid session ID' when accessing ElementFinder in JasmineReporter

### ISSUE THREAD

**Issue by aeisenberg** [angular/protractor#2007] opened 2015-04-06 17:01 UTC
Using Protractor 2.0.0, I am getting an error when accessing the DOM in a JasmineReporter after the last test.  It looks like WebDriver.quit() is being called before the specDone event is called.

To reproduce, try the following code:

protractor.conf.js
```javascript
'use strict';

var fs = require('fs');

exports.config = {

    onPrepare: function () {
	    jasmine.getEnv().addReporter({
	        specDone: function(result) {
	            if (result.failedExpectations.length > 0) {
	                var filename = 'failed-' + result.description + '-' + Date.now() + '.html';
	                browser.findElement(by.css('html')).getOuterHtml().then(function(html) {
	                    fs.writeFile(filename + '.html', html);
	                });
	            }
	        }
	    });
    },

    framework: 'jasmine2',

    capabilities: {
        'browserName': 'chrome'
    },

    specs: ['*.spec.js'],

    baseUrl: 'https://docs.angularjs.org/'
};
```

bad-test.spec.js
```javascript
describe('Home Page', function () {
    beforeEach(function() {
        browser.get(browser.baseUrl);
    });
	
    it('should fail', function () {
        expect(true).toBe(false);
    });
    // it('should pass', function () {
    //     expect(true).toBe(true);
    // });
});
```

When running protractor as above, you will get an exception and protractor will crash.  If you uncomment the last test, the first test fails as expected and the html is saved to a file.

In case it's not obvious, my goal is to grab the full html of the page when a spec fails, but that's not possible if the last test fails.

**Comment by juliemr** [comment] 2015-04-06 18:16
Duplicate of https://github.com/angular/protractor/issues/1938

**Closed by juliemr** 2015-04-06 18:16 UTC
