### ISSUE TITLE
Stop it() on first failure and continue to next it()

### ISSUE THREAD

**Issue by mwsessom** [angular/protractor#3563] opened 2016-09-15 22:23 UTC
Protractor should stop executing the current it() test upon first failed expectation or failure. 

Typically, in an E2E scenario, a failed expectation will usually cause all subsequent expectations within that it() block to fail. Furthermore, taking screenshots on failures only captures what's on the screen when the last failure occurred. All previous failures within the it() are basically ignored.

Example E2E scenario: As a gmail user, I can create an email draft.
1) login as gmail user
2) expect login was successful (pass)
3) create draft
4) expect draft dialog box opens (pass)
5) enter text & save as draft (this fails due to no 'save as draft' button)
6) go to gmail page & search for drafts
7) expect my draft to be listed (fails)

In this example, the test should stop on step 5 and take a screenshot. However, the test finishes and the screenshot taken is from step 7. This is a very basic example, but a lot of times the state of the UI at the end of the test does not reflect the true failure.

**Comment by cnishina** [comment] 2016-09-16 23:05
Hi! This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!

**Comment by mwsessom** [comment] 2016-09-17 07:22
No, this is a feature request.

**Comment by cnishina** [comment] 2016-09-17 09:39
Sorry about that @mwsessom. From the description, it sounded like you needed help writing a test.

https://github.com/angular/protractor/blob/master/lib/element.ts#L755

It appears call `.then` in `elementArrayFinder.getWebElements().then(`without calling a `.catch`. This might need to be investigated.

**Comment by cnishina** [comment] 2016-09-17 09:40
I've also confirmed this. It appears the catch to the promise is caught only at the end of the test.

**Comment by mwsessom** [comment] 2016-09-18 01:03
Another example:
```
it("simple test", function() {
  expect(false).toBe(true); //since this expect fails, this test should be marked failed and move on.
  expect(false).toBe(true); //this expect should not be executed 
}
```

**Comment by Xotabu4** [comment] 2016-09-18 10:55
I remember some old issue here on github about this feature for JasmineWD. 
I beleive this is not a bug, just feature that should be implemented. 
#3234 
https://github.com/angular/protractor/issues/3234

Can we merge this 2 tickets together?

**Comment by juliemr** [comment] 2016-09-20 21:11
I agree that this is a duplicate of https://github.com/angular/protractor/issues/3234. Closing in favor of that.

**Closed by juliemr** 2016-09-20 21:11 UTC
Labels: type: bug
