### ISSUE TITLE
Random occurrences of UnknownError: Error communicating with the remote browser. It may have died.

### ISSUE THREAD

**Issue by ngib** [angular/protractor#2862] opened 2016-01-22 13:48 UTC
Chrome: 47.0.2526.106 (Official Build) m (32-bit)
Protractor: 3.0.0 && 2.5.1
asyncawait: 2.14.3
Not an angular project

In my overnight runs, I'm getting very inconsistent results because this is causing tests to crash in the middle of running.

To simplify the syntax for handling asynchronous tasks for some of the less technical on my team, I'm using async/await. A typical test might look something like this:

```
	it('should do the asynchronous task', async(function () {
		var result = await(doTheTask());
                expect(result).toBe('It Worked');
	}));
```

I previously was using Jasmine's done in these tests, like so:

```
	it('should do the asynchronous task', async(function (done) {
		var result = await(doTheTask());
                expect(result).toBe('It Worked');
                done()
	}));
```

Unfortunately, this was causing issues where tests would be given a false positive pass even though one or more expects actually failed. Removing the dones seemed to resolve this for all of my tests.

Here's the stack trace when running locally with directConnect disabled through team city. I do have multiple instances of protractor running, all connecting to the same selenium server instance. Strangely enough, though it complains about connecting to the remote browser, the next test in the same thread connects to the same browser instance without issue:

```
C:\BuildAgent01\work\2adec85301b53360\node_modules\protractor\node_modules\selenium-webdriver\lib\atoms\error.js:108
var template = new Error(this.message);

UnknownError: Error communicating with the remote browser. It may have died.
Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
System info: host: 'BuildAgent-1', ip: '0.0.0.0', os.name: 'Windows Server 2008 R2', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_21'
Driver info: driver.version: EventFiringWebDriver
     at new bot.Error (C:\BuildAgent01\work\2adec85301b53360\node_modules\protractor\node_modules\selenium-webdriver\lib\atoms\error.js:108:18)
     at Object.bot.response.checkResponse (C:\BuildAgent01\work\2adec85301b53360\node_modules\protractor\node_modules\selenium-webdriver\lib\atoms\response.js:109:9)
     at C:\BuildAgent01\work\2adec85301b53360\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:379:20
     at [object Object].promise.ControlFlow.runInFrame_ (C:/BuildAgent01/work/2adec85301b53360/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1857:20)
     at [object Object].goog.defineClass.notify (C:/BuildAgent01/work/2adec85301b53360/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2448:25)
     at [object Object].promise.Promise.notify_ (C:/BuildAgent01/work/2adec85301b53360/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:564:12)
     at Array.forEach (native)
     at [object Object].promise.Promise.notifyAll_ (C:/BuildAgent01/work/2adec85301b53360/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:553:15)
     at goog.async.run.processWorkQueue (C:\BuildAgent01\work\2adec85301b53360\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\async\run.js:130:15)
     at process._tickCallback (node.js:356:9)
 [launcher] Process exited with error code 1
```

**Comment by NickTomlin** [comment] 2016-01-22 14:50
Hi there!

Inconsistencies like this are the bane of integration testing :expressionless: I feel your pain. From my gut, this sounds like an issue with test setup or environment. Because of this, and the investigation/debugging necessary to get to the root of actual problem, your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!

**Comment by juliemr** [comment] 2016-01-22 18:22
I agree with Nick, this feels like a test setup issue. Having many connections to one selenium server sounds like it may be causing the issue. I think you need to look at the logs for your selenium server.

I'm unclear what the `done` changes have to do with  your issue, but I suspect it's a red herring.

I'm going to close this issue because it is more of a setup/support problem than a reproducible bug that we can track here.

**Closed by juliemr** 2016-01-22 18:22 UTC
