### ISSUE TITLE
Jasmine spec timeout error while running multiple specs together

### ISSUE THREAD

**Issue by punithj** [angular/protractor#3486] opened 2016-08-19 13:03 UTC
I am experiencing jasmine spec time out issue since a long back while I run multiple specs on IE 11 browser. Also, once the spec has jasmine spec time out then most of the specs that follows it have similar jasmine spec timed out issue. I am struggling to fix this since a long back but no luck.

I tried many things to solve it as below but issue still exists:

Increased maximumSpecCallbackDepth value to 2000
Removed BeforeEach fucntion from all spec files and moved that code to it block
Used all local variables declared in it block
Used Jasmine instead of Jasmine 2 in conf file
Using only one it block per spec file
I also upgraded to protractor 3.3.0 but the issue persists. When I run the single spec file with one it block the spec runs fine but with too many specs (tried with more than 10, 20, 30, 100 specs together), it is giving these errors. and for every run, it is behaving random results.

I googled this and tried many solutions.

My every spec first logs into the app and then carries out the operations as required. I figured out that most of my spec is giving this error when it navigates to the required page using browser.get()....It logs in to the app correctly but it fails on next browser.get() mainly.

I am not sure that this issue is related with this defect but anyhow I am commenting here just to get some stuff that can help me.

**Comment by NickTomlin** [comment] 2016-08-19 14:16
Hi there,

Please follow the [Issue Template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) when opening new issues. Otherwise it's unclear what the issue is and how we can actually help.

Please update your issue with the relevant information. Otherwise i'll go ahead and close it according to the issue template rules. 

Thanks!
Nick

**Comment by cnishina** [comment] 2016-08-19 18:16
Timeouts:

- Timeout tips are on the protractortest site. http://www.protractortest.org/#/timeouts
- You are having issues in IE, does it work in Chrome?

I am closing this issue since it is a support question and should be asked on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

**Closed by cnishina** 2016-08-19 18:16 UTC
