### ISSUE TITLE
npm errors while installing protractor

### ISSUE THREAD

**Issue by BrodaNoel** [angular/protractor#2068] opened 2015-04-20 19:16 UTC
Hi all.
I'm getting those errors while I install protractor:

```
npm http 304 http://npm.cloud.corp.dig.com/bindings

> bufferutil@1.0.1 install c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild


c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\bufferutil>node "c:\DevTools\nodejs\node_modules\npm\bin\
node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (c:\DevTools\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at c:\DevTools\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:64:11
gyp ERR! stack     at Object.oncomplete (fs.js:107:15)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "c:\\DevTools\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok

> utf-8-validate@1.0.1 install c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild


c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\utf-8-validate>node "c:\DevTools\nodejs\node_modules\npm\
bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (c:\DevTools\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at c:\DevTools\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:64:11
gyp ERR! stack     at Object.oncomplete (fs.js:107:15)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "c:\\DevTools\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.0.1
npm WARN optional dep failed, continuing utf-8-validate@1.0.1
chai-as-promised@4.1.1 node_modules\chai-as-promised
```

Here you have the complete log:

```
Welcome to Git (version 1.9.5-preview20141217)


Run 'git help git' to display the help index.
Run 'git help <command>' to display help for specific commands.

noel.broda@CBA-D013 ~
$ cd de
Desktop/   debug.log

noel.broda@CBA-D013 ~
$ cd Desktop/

noel.broda@CBA-D013 ~/Desktop
$ git clone https://github.com/angular/protractor.git
Cloning into 'protractor'...
remote: Counting objects: 6316, done.
remote: Total 6316 (delta 0), reused 0 (delta 0), pack-reused 6316
Receiving objects: 100% (6316/6316), 3.55 MiB | 106.00 KiB/s, done.
Resolving deltas: 100% (3900/3900), done.
Checking connectivity... done.

noel.broda@CBA-D013 ~/Desktop
$ cd protractor/

noel.broda@CBA-D013 ~/Desktop/protractor (master)
$ npm install
npm http GET http://npm.cloud.corp.dig.com/jasmine
npm http GET http://npm.cloud.corp.dig.com/selenium-webdriver
npm http GET http://npm.cloud.corp.dig.com/minijasminenode
npm http GET http://npm.cloud.corp.dig.com/optimist
npm http GET http://npm.cloud.corp.dig.com/adm-zip
npm http GET http://npm.cloud.corp.dig.com/jasminewd2
npm http GET http://npm.cloud.corp.dig.com/saucelabs
npm http GET http://npm.cloud.corp.dig.com/request
npm http GET http://npm.cloud.corp.dig.com/source-map-support
npm http GET http://npm.cloud.corp.dig.com/jasminewd
npm http GET http://npm.cloud.corp.dig.com/glob
npm http GET http://npm.cloud.corp.dig.com/lodash
npm http GET http://npm.cloud.corp.dig.com/expect.js
npm http GET http://npm.cloud.corp.dig.com/q
npm http GET http://npm.cloud.corp.dig.com/chai
npm http GET http://npm.cloud.corp.dig.com/accessibility-developer-tools
npm http GET http://npm.cloud.corp.dig.com/html-entities
npm http GET http://npm.cloud.corp.dig.com/chai-as-promised
npm http GET http://npm.cloud.corp.dig.com/jshint
npm http GET http://npm.cloud.corp.dig.com/mocha
npm http GET http://npm.cloud.corp.dig.com/cucumber
npm http GET http://npm.cloud.corp.dig.com/express
npm http GET http://npm.cloud.corp.dig.com/rimraf
npm http 304 http://npm.cloud.corp.dig.com/optimist
npm http 304 http://npm.cloud.corp.dig.com/adm-zip
npm http 304 http://npm.cloud.corp.dig.com/selenium-webdriver
npm http 304 http://npm.cloud.corp.dig.com/minijasminenode
npm http 304 http://npm.cloud.corp.dig.com/jasmine
npm http 200 http://npm.cloud.corp.dig.com/jasminewd2
npm http 304 http://npm.cloud.corp.dig.com/saucelabs
npm http 304 http://npm.cloud.corp.dig.com/request
npm http GET http://npm.cloud.corp.dig.com/jasminewd2/-/jasminewd2-0.0.4.tgz
npm http 304 http://npm.cloud.corp.dig.com/jasminewd
npm http 304 http://npm.cloud.corp.dig.com/source-map-support
npm http 304 http://npm.cloud.corp.dig.com/lodash
npm http 304 http://npm.cloud.corp.dig.com/glob
npm http 304 http://npm.cloud.corp.dig.com/expect.js
npm http 304 http://npm.cloud.corp.dig.com/q
npm http 304 http://npm.cloud.corp.dig.com/chai
npm http 200 http://npm.cloud.corp.dig.com/jasminewd2/-/jasminewd2-0.0.4.tgz
npm http 304 http://npm.cloud.corp.dig.com/jshint
npm http 304 http://npm.cloud.corp.dig.com/chai-as-promised
npm http 304 http://npm.cloud.corp.dig.com/mocha
npm http 304 http://npm.cloud.corp.dig.com/html-entities
npm http 304 http://npm.cloud.corp.dig.com/accessibility-developer-tools
npm http 304 http://npm.cloud.corp.dig.com/express
npm http 304 http://npm.cloud.corp.dig.com/cucumber
npm http 304 http://npm.cloud.corp.dig.com/rimraf
npm http GET http://npm.cloud.corp.dig.com/form-data
npm http GET http://npm.cloud.corp.dig.com/json-stringify-safe
npm http GET http://npm.cloud.corp.dig.com/forever-agent
npm http GET http://npm.cloud.corp.dig.com/tunnel-agent
npm http GET http://npm.cloud.corp.dig.com/mime
npm http GET http://npm.cloud.corp.dig.com/http-signature
npm http GET http://npm.cloud.corp.dig.com/oauth-sign
npm http GET http://npm.cloud.corp.dig.com/qs
npm http GET http://npm.cloud.corp.dig.com/node-uuid
npm http GET http://npm.cloud.corp.dig.com/aws-sign2
npm http GET http://npm.cloud.corp.dig.com/hawk
npm http GET http://npm.cloud.corp.dig.com/tough-cookie
npm http GET http://npm.cloud.corp.dig.com/jasmine-core
npm http GET http://npm.cloud.corp.dig.com/inherits
npm http GET http://npm.cloud.corp.dig.com/wordwrap
npm http GET http://npm.cloud.corp.dig.com/minimist
npm http GET http://npm.cloud.corp.dig.com/minimatch
npm http GET http://npm.cloud.corp.dig.com/range-parser
npm http GET http://npm.cloud.corp.dig.com/buffer-crc32
npm http GET http://npm.cloud.corp.dig.com/methods
npm http GET http://npm.cloud.corp.dig.com/cookie
npm http GET http://npm.cloud.corp.dig.com/mkdirp
npm http GET http://npm.cloud.corp.dig.com/connect
npm http GET http://npm.cloud.corp.dig.com/fresh
npm http GET http://npm.cloud.corp.dig.com/commander
npm http GET http://npm.cloud.corp.dig.com/cookie-signature
npm http GET http://npm.cloud.corp.dig.com/debug
npm http GET http://npm.cloud.corp.dig.com/send
npm http GET http://npm.cloud.corp.dig.com/source-map
npm http GET http://npm.cloud.corp.dig.com/assertion-error
npm http GET http://npm.cloud.corp.dig.com/deep-eql
npm http GET http://npm.cloud.corp.dig.com/commander
npm http GET http://npm.cloud.corp.dig.com/growl
npm http GET http://npm.cloud.corp.dig.com/diff
npm http GET http://npm.cloud.corp.dig.com/jade
npm http GET http://npm.cloud.corp.dig.com/minimatch
npm http GET http://npm.cloud.corp.dig.com/console-browserify
npm http GET http://npm.cloud.corp.dig.com/exit
npm http GET http://npm.cloud.corp.dig.com/underscore
npm http GET http://npm.cloud.corp.dig.com/shelljs
npm http GET http://npm.cloud.corp.dig.com/cli
npm http GET http://npm.cloud.corp.dig.com/strip-json-comments
npm http GET http://npm.cloud.corp.dig.com/htmlparser2
npm http 304 http://npm.cloud.corp.dig.com/forever-agent
npm http 304 http://npm.cloud.corp.dig.com/json-stringify-safe
npm http 304 http://npm.cloud.corp.dig.com/form-data
npm http 304 http://npm.cloud.corp.dig.com/mime
npm http 304 http://npm.cloud.corp.dig.com/tunnel-agent
npm http 304 http://npm.cloud.corp.dig.com/http-signature
npm http 304 http://npm.cloud.corp.dig.com/oauth-sign
npm http 304 http://npm.cloud.corp.dig.com/qs
npm http 304 http://npm.cloud.corp.dig.com/aws-sign2
npm http 304 http://npm.cloud.corp.dig.com/node-uuid
npm http 304 http://npm.cloud.corp.dig.com/hawk
npm http 304 http://npm.cloud.corp.dig.com/tough-cookie
npm http 304 http://npm.cloud.corp.dig.com/inherits
npm http 304 http://npm.cloud.corp.dig.com/wordwrap
npm http 304 http://npm.cloud.corp.dig.com/jasmine-core
npm http 304 http://npm.cloud.corp.dig.com/minimist
npm http 304 http://npm.cloud.corp.dig.com/minimatch
npm http 304 http://npm.cloud.corp.dig.com/range-parser
npm http 304 http://npm.cloud.corp.dig.com/methods
npm http 304 http://npm.cloud.corp.dig.com/cookie
npm http 304 http://npm.cloud.corp.dig.com/mkdirp
npm http 304 http://npm.cloud.corp.dig.com/commander
npm http 304 http://npm.cloud.corp.dig.com/cookie-signature
npm http 304 http://npm.cloud.corp.dig.com/connect
npm http 304 http://npm.cloud.corp.dig.com/buffer-crc32
npm http GET http://npm.cloud.corp.dig.com/combined-stream
npm http GET http://npm.cloud.corp.dig.com/async
npm http GET http://npm.cloud.corp.dig.com/sigmund
npm http GET http://npm.cloud.corp.dig.com/assert-plus
npm http GET http://npm.cloud.corp.dig.com/asn1
npm http GET http://npm.cloud.corp.dig.com/lru-cache
npm http GET http://npm.cloud.corp.dig.com/ctype
npm http GET http://npm.cloud.corp.dig.com/underscore
npm http GET http://npm.cloud.corp.dig.com/gherkin
npm http GET http://npm.cloud.corp.dig.com/nopt
npm http GET http://npm.cloud.corp.dig.com/browserify
npm http GET http://npm.cloud.corp.dig.com/cucumber-html
npm http GET http://npm.cloud.corp.dig.com/walkdir
npm http GET http://npm.cloud.corp.dig.com/coffee-script
npm http GET http://npm.cloud.corp.dig.com/pogo
npm http GET http://npm.cloud.corp.dig.com/punycode
npm http GET http://npm.cloud.corp.dig.com/boom
npm http 304 http://npm.cloud.corp.dig.com/debug
npm http GET http://npm.cloud.corp.dig.com/cryptiles
npm http GET http://npm.cloud.corp.dig.com/sntp
npm http GET http://npm.cloud.corp.dig.com/hoek
npm http 304 http://npm.cloud.corp.dig.com/send
npm http 304 http://npm.cloud.corp.dig.com/source-map
npm http 304 http://npm.cloud.corp.dig.com/assertion-error
npm http 304 http://npm.cloud.corp.dig.com/fresh
npm http GET http://npm.cloud.corp.dig.com/amdefine
npm http 304 http://npm.cloud.corp.dig.com/deep-eql
npm http GET http://npm.cloud.corp.dig.com/keypress
npm http 304 http://npm.cloud.corp.dig.com/commander
npm http GET http://npm.cloud.corp.dig.com/ms
npm http GET http://npm.cloud.corp.dig.com/type-detect
npm http 304 http://npm.cloud.corp.dig.com/growl
npm http 304 http://npm.cloud.corp.dig.com/diff
npm http 304 http://npm.cloud.corp.dig.com/jade
npm http 304 http://npm.cloud.corp.dig.com/minimatch
npm http 304 http://npm.cloud.corp.dig.com/console-browserify
npm http 304 http://npm.cloud.corp.dig.com/exit
npm http GET http://npm.cloud.corp.dig.com/graceful-fs
npm http 304 http://npm.cloud.corp.dig.com/underscore
npm http 304 http://npm.cloud.corp.dig.com/shelljs
npm http 304 http://npm.cloud.corp.dig.com/cli
npm http GET http://npm.cloud.corp.dig.com/uid2
npm http GET http://npm.cloud.corp.dig.com/pause
npm http GET http://npm.cloud.corp.dig.com/bytes
npm http GET http://npm.cloud.corp.dig.com/formidable
npm http 304 http://npm.cloud.corp.dig.com/strip-json-comments
npm http 304 http://npm.cloud.corp.dig.com/htmlparser2
npm http 304 http://npm.cloud.corp.dig.com/combined-stream
npm http 304 http://npm.cloud.corp.dig.com/async
npm http 304 http://npm.cloud.corp.dig.com/sigmund
npm http GET http://npm.cloud.corp.dig.com/delayed-stream
npm http 304 http://npm.cloud.corp.dig.com/assert-plus
npm http 304 http://npm.cloud.corp.dig.com/asn1
npm http 304 http://npm.cloud.corp.dig.com/lru-cache
npm http 304 http://npm.cloud.corp.dig.com/underscore
npm http 304 http://npm.cloud.corp.dig.com/gherkin
npm http 304 http://npm.cloud.corp.dig.com/nopt
npm http 304 http://npm.cloud.corp.dig.com/browserify
npm http 304 http://npm.cloud.corp.dig.com/cucumber-html
npm http 304 http://npm.cloud.corp.dig.com/coffee-script
npm http 304 http://npm.cloud.corp.dig.com/walkdir
npm http 304 http://npm.cloud.corp.dig.com/pogo
npm http 304 http://npm.cloud.corp.dig.com/punycode
npm http 304 http://npm.cloud.corp.dig.com/boom
npm http 304 http://npm.cloud.corp.dig.com/cryptiles
npm http 304 http://npm.cloud.corp.dig.com/sntp
npm http 304 http://npm.cloud.corp.dig.com/keypress
npm http 304 http://npm.cloud.corp.dig.com/hoek
npm http 304 http://npm.cloud.corp.dig.com/amdefine
npm http 304 http://npm.cloud.corp.dig.com/ctype
npm http 304 http://npm.cloud.corp.dig.com/type-detect
npm http 304 http://npm.cloud.corp.dig.com/graceful-fs
npm http 304 http://npm.cloud.corp.dig.com/ms
npm http 304 http://npm.cloud.corp.dig.com/uid2
npm http 304 http://npm.cloud.corp.dig.com/pause
npm http 304 http://npm.cloud.corp.dig.com/bytes
npm http 304 http://npm.cloud.corp.dig.com/delayed-stream
npm http 304 http://npm.cloud.corp.dig.com/formidable
npm http GET http://npm.cloud.corp.dig.com/abbrev
npm http GET http://npm.cloud.corp.dig.com/domutils
npm http GET http://npm.cloud.corp.dig.com/domhandler
npm http GET http://npm.cloud.corp.dig.com/readable-stream
npm http GET http://npm.cloud.corp.dig.com/domelementtype
npm http GET http://npm.cloud.corp.dig.com/nub
npm http GET http://npm.cloud.corp.dig.com/deputy
npm http GET http://npm.cloud.corp.dig.com/syntax-error
npm http GET http://npm.cloud.corp.dig.com/detective
npm http GET http://npm.cloud.corp.dig.com/buffer-browserify
npm http GET http://npm.cloud.corp.dig.com/commondir
npm http GET http://npm.cloud.corp.dig.com/resolve
npm http 304 http://npm.cloud.corp.dig.com/abbrev
npm http GET http://npm.cloud.corp.dig.com/optimist
npm http GET http://npm.cloud.corp.dig.com/vm-browserify
npm http GET http://npm.cloud.corp.dig.com/http-browserify
npm http GET http://npm.cloud.corp.dig.com/crypto-browserify
npm http 304 http://npm.cloud.corp.dig.com/readable-stream
npm http 304 http://npm.cloud.corp.dig.com/domutils
npm http 304 http://npm.cloud.corp.dig.com/domelementtype
npm http GET http://npm.cloud.corp.dig.com/uglify-js
npm http 304 http://npm.cloud.corp.dig.com/nub
npm http 304 http://npm.cloud.corp.dig.com/domhandler
npm http 304 http://npm.cloud.corp.dig.com/deputy
npm http 304 http://npm.cloud.corp.dig.com/syntax-error
npm http 304 http://npm.cloud.corp.dig.com/detective
npm http 304 http://npm.cloud.corp.dig.com/buffer-browserify
npm http 304 http://npm.cloud.corp.dig.com/commondir
npm http GET http://npm.cloud.corp.dig.com/core-util-is
npm http GET http://npm.cloud.corp.dig.com/isarray
npm http GET http://npm.cloud.corp.dig.com/string_decoder
npm http 304 http://npm.cloud.corp.dig.com/resolve
npm http 304 http://npm.cloud.corp.dig.com/optimist
npm http 304 http://npm.cloud.corp.dig.com/vm-browserify
npm http 304 http://npm.cloud.corp.dig.com/http-browserify
npm http 304 http://npm.cloud.corp.dig.com/crypto-browserify
npm http 304 http://npm.cloud.corp.dig.com/uglify-js
npm http 304 http://npm.cloud.corp.dig.com/core-util-is
npm http 304 http://npm.cloud.corp.dig.com/isarray
npm http 304 http://npm.cloud.corp.dig.com/string_decoder
npm http GET http://npm.cloud.corp.dig.com/base64-js
npm http GET http://npm.cloud.corp.dig.com/esprima
npm http GET http://npm.cloud.corp.dig.com/indexof
npm http GET http://npm.cloud.corp.dig.com/Base64
npm http GET http://npm.cloud.corp.dig.com/concat-stream
npm http 304 http://npm.cloud.corp.dig.com/base64-js
npm http 304 http://npm.cloud.corp.dig.com/esprima
npm http 304 http://npm.cloud.corp.dig.com/indexof
npm http 304 http://npm.cloud.corp.dig.com/Base64
npm http 304 http://npm.cloud.corp.dig.com/concat-stream
npm http GET http://npm.cloud.corp.dig.com/bops
npm http GET http://npm.cloud.corp.dig.com/tmp
npm http GET http://npm.cloud.corp.dig.com/ws
npm http GET http://npm.cloud.corp.dig.com/xml2js
npm http 304 http://npm.cloud.corp.dig.com/bops
npm http GET http://npm.cloud.corp.dig.com/to-utf8
npm http 304 http://npm.cloud.corp.dig.com/xml2js
npm http 304 http://npm.cloud.corp.dig.com/tmp
npm http 304 http://npm.cloud.corp.dig.com/ws
npm http GET http://npm.cloud.corp.dig.com/sax
npm http GET http://npm.cloud.corp.dig.com/xmlbuilder
npm http GET http://npm.cloud.corp.dig.com/utf-8-validate
npm http GET http://npm.cloud.corp.dig.com/bufferutil
npm http GET http://npm.cloud.corp.dig.com/options
npm http GET http://npm.cloud.corp.dig.com/ultron
npm http 304 http://npm.cloud.corp.dig.com/to-utf8
npm http 304 http://npm.cloud.corp.dig.com/options
npm http 304 http://npm.cloud.corp.dig.com/sax
npm http 304 http://npm.cloud.corp.dig.com/xmlbuilder
npm http 304 http://npm.cloud.corp.dig.com/utf-8-validate
npm http 304 http://npm.cloud.corp.dig.com/bufferutil
npm http 304 http://npm.cloud.corp.dig.com/ultron
npm http GET http://npm.cloud.corp.dig.com/lodash
npm http GET http://npm.cloud.corp.dig.com/bindings
npm http GET http://npm.cloud.corp.dig.com/nan
npm http 304 http://npm.cloud.corp.dig.com/lodash
npm http 304 http://npm.cloud.corp.dig.com/nan
npm http 304 http://npm.cloud.corp.dig.com/bindings

> bufferutil@1.0.1 install c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild


c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\bufferutil>node "c:\DevTools\nodejs\node_modules\npm\bin\
node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (c:\DevTools\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at c:\DevTools\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:64:11
gyp ERR! stack     at Object.oncomplete (fs.js:107:15)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "c:\\DevTools\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok

> utf-8-validate@1.0.1 install c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild


c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\utf-8-validate>node "c:\DevTools\nodejs\node_modules\npm\
bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (c:\DevTools\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at c:\DevTools\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:64:11
gyp ERR! stack     at Object.oncomplete (fs.js:107:15)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "c:\\DevTools\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.0.1
npm WARN optional dep failed, continuing utf-8-validate@1.0.1
chai-as-promised@4.1.1 node_modules\chai-as-promised

jasminewd@1.1.0 node_modules\jasminewd

jasminewd2@0.0.4 node_modules\jasminewd2

expect.js@0.2.0 node_modules\expect.js

rimraf@2.2.8 node_modules\rimraf

html-entities@1.1.2 node_modules\html-entities

saucelabs@0.1.1 node_modules\saucelabs

q@1.0.0 node_modules\q

minijasminenode@1.1.1 node_modules\minijasminenode

adm-zip@0.4.4 node_modules\adm-zip

lodash@2.4.1 node_modules\lodash

accessibility-developer-tools@2.6.0 node_modules\accessibility-developer-tools

optimist@0.6.1 node_modules\optimist
├── wordwrap@0.0.2
└── minimist@0.0.10

jasmine@2.1.1 node_modules\jasmine
└── jasmine-core@2.1.3

glob@3.2.11 node_modules\glob
├── inherits@2.0.1
└── minimatch@0.3.0 (sigmund@1.0.0, lru-cache@2.6.1)

source-map-support@0.2.10 node_modules\source-map-support
└── source-map@0.1.32 (amdefine@0.1.0)

chai@1.8.1 node_modules\chai
├── assertion-error@1.0.0
└── deep-eql@0.1.3 (type-detect@0.1.1)

request@2.36.0 node_modules\request
├── aws-sign2@0.5.0
├── forever-agent@0.5.2
├── json-stringify-safe@5.0.0
├── qs@0.6.6
├── tunnel-agent@0.4.0
├── oauth-sign@0.3.0
├── mime@1.2.11
├── node-uuid@1.4.3
├── tough-cookie@0.12.1 (punycode@1.3.2)
├── form-data@0.1.4 (async@0.9.0, combined-stream@0.0.7)
├── http-signature@0.10.1 (assert-plus@0.1.5, asn1@0.1.11, ctype@0.5.3)
└── hawk@1.0.0 (cryptiles@0.2.2, sntp@0.2.4, boom@0.4.2, hoek@0.9.1)

mocha@1.21.4 node_modules\mocha
├── diff@1.0.7
├── growl@1.8.1
├── commander@2.0.0
├── mkdirp@0.3.5
├── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)
├── debug@2.1.3 (ms@0.7.0)
└── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)

express@3.3.8 node_modules\express
├── methods@0.0.1
├── range-parser@0.0.4
├── cookie-signature@1.0.1
├── fresh@0.2.0
├── buffer-crc32@0.2.1
├── cookie@0.1.0
├── mkdirp@0.3.5
├── send@0.1.4 (mime@1.2.11)
├── commander@1.2.0 (keypress@0.1.0)
├── debug@2.1.3 (ms@0.7.0)
└── connect@2.8.8 (uid2@0.0.2, pause@0.0.1, qs@0.6.5, bytes@0.2.0, formidable@1.0.14)

jshint@2.5.0 node_modules\jshint
├── strip-json-comments@0.1.3
├── console-browserify@0.1.6
├── cli@0.4.5
├── underscore@1.4.4
├── exit@0.1.2
├── minimatch@0.4.0 (sigmund@1.0.0, lru-cache@2.6.1)
├── shelljs@0.1.4
└── htmlparser2@3.3.0 (domelementtype@1.3.0, domutils@1.1.6, domhandler@2.1.0, readable-stream@1.0.33)

cucumber@0.3.3 node_modules\cucumber
├── underscore@1.5.2
├── walkdir@0.0.7
├── coffee-script@1.6.3
├── cucumber-html@0.2.3
├── nopt@2.1.2 (abbrev@1.0.5)
├── gherkin@2.12.2
├── pogo@0.5.1 (underscore@1.4.4, uglify-js@2.2.4)
└── browserify@1.15.5 (nub@0.0.0, commondir@0.0.2, crypto-browserify@0.4.0, resolve@0.2.8, deputy@0.0.4, optimist@0.3.7, buffer-browserify@0.0.5, vm-browseri
fy@0.0.4, detective@0.2.1, syntax-error@0.0.1, http-browserify@0.1.14)

selenium-webdriver@2.45.1 node_modules\selenium-webdriver
├── tmp@0.0.24
├── ws@0.7.1 (options@0.0.6, ultron@1.0.1)
└── xml2js@0.4.4 (sax@0.6.1, xmlbuilder@2.6.2)

noel.broda@CBA-D013 ~/Desktop/protractor (master)
$
```

I'm creating this issue because in a few I'll create another defect that could be related to this one.

**Comment by BrodaNoel** [comment] 2015-04-20 20:34
I installed Python > 3.0.0, and I added the binary to the "PYTHON" env var. BUT, gyp need python > 2.0 and < 3.0.
That should be added to the documentation

**Comment by BrodaNoel** [comment] 2015-04-20 20:53
Confirmed. Fixed after created the PYTHON env var that have the value: "C:\Python2\python.exe".
It should be added at the documentation

**Comment by juliemr** [comment] 2015-04-20 21:47
This is a duplicate of https://github.com/angular/protractor/issues/2035

**Closed by juliemr** 2015-04-20 21:47 UTC

**Comment by BrodaNoel** [comment] 2015-04-20 22:05
If you want, I could send a PR with notes talking about it in the README.
