### ISSUE TITLE
isVerbose has no effect

### ISSUE THREAD

**Issue by ceelian** [angular/protractor#1789] opened 2015-02-06 18:46 UTC
isVerbose does not display a more verbose output.
I hoped that we would see something like the test suite filenames which are processed, or the `describe` and `it` texts.

My config file is:

```
exports.config = {
		seleniumAddress: 'http://localhost:4444/wd/hub',
		baseUrl: 'http://localhost:8080',
		framework: 'jasmine2',
		jasmineNodeOpts: {
			// If true, print colors to the terminal.
			showColors: true,
			isVerbose: true
		},
		params: testing_params,
		specs: ['test/e2e/stories/*.story.js'],
		onPrepare: function() {
			global.browser2 =  browser.forkNewDriverInstance();
		}
```

Output with `isVerbose: false`:

```
protractor prot.js --specs test/e2e/stories/test.story.js 
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
Started


.


1 spec, 0 failures
Finished in 4.616 seconds
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #1 passed

```

Output with `isVerbose: true`:

```
protractor prot.js --specs test/e2e/stories/test.story.js 
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
Started


.


1 spec, 0 failures
Finished in 4.207 seconds
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #1 passed
```

System OS X, Protractor Version 1.6.1

Thx.

**Comment by hankduan** [comment] 2015-02-06 19:31
`isVerbose` is not a jasmine2 feature as we're using https://github.com/jasmine/jasmine-npm directly now

**Comment by juliemr** [comment] 2015-02-06 20:47
Closing as answered.

**Comment by ceelian** [comment] 2015-02-09 19:15
@hankduan, @juliemr can you give a clue how to activate a more verbose output with protractor and Jasmine 2 or give a best practice? 

Our experience is that just "F"'s in a row of "." are not very useful in production environments with dozens of suites when you have to figure out in which test case the failure occurred.

**Comment by hankduan** [comment] 2015-02-09 19:18
What does your output look like? Jasmine should already point you to 1) which spec failed 2) error message and 3) stack trace

i.e.:
```
$ node lib/cli.js spec/hankConf.js --suite=hank
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
Started
F.

Failures:
1) test do authenticated tests authenticated test 1
  Message:
    Expected true to be false.
  Stack:
    Error: Failed expectation
        at Env.<anonymous> (/workspace/protractor/spec/hank_spec.js:7:20)
        at /workspace/protractor/node_modules/jasminewd2/index.js:95:14
        at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (/workspace/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
        at [object Object].webdriver.promise.ControlFlow.runEventLoop_ (/workspace/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1518:8)
        at [object Object].wrapper [as _onTimeout] (timers.js:252:14)
        at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

2 specs, 1 failure
Finished in 0.09 seconds
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #1 failed 1 test(s)
[launcher] overall: 1 failed spec(s)
[launcher] Process exited with error code 1
```

**Comment by ceelian** [comment] 2015-02-09 19:32
Unfortunately not in all cases. E.g. when an element can't be found because it is not visible, there is no spec file mentioned where this happened. 

```
[...]
2) Projects List Site changes url to project single
  Message:
    Failed: element not visible
      (Session info: chrome=40.0.2214.111)
      (Driver info: chromedriver=2.13.307650 (feffe1dd547ee7b5c16d38784cd0cd679dfd7850),platform=Mac OS X 10.9.5 x86_64) (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 15 milliseconds
    Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
    System info: host: 'karin.office.cnc', ip: '192.168.123.102', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.7.0_45'
    Session ID: d9b5991356abecf991317557cbd9162b
    Driver info: org.openqa.selenium.chrome.ChromeDriver
    Capabilities [{platform=MAC, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/var/folders/wx/qt_77kv53270dwfh0s15vbg40000gn/T/.org.chromium.Chromium.6YxstT}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=40.0.2214.111, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]
  Stack:
    Error: Failed: element not visible
      (Session info: chrome=40.0.2214.111)
      (Driver info: chromedriver=2.13.307650 (feffe1dd547ee7b5c16d38784cd0cd679dfd7850),platform=Mac OS X 10.9.5 x86_64) (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 15 milliseconds
    Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
    System info: host: 'karin.office.cnc', ip: '192.168.123.102', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.7.0_45'
    Session ID: d9b5991356abecf991317557cbd9162b
    Driver info: org.openqa.selenium.chrome.ChromeDriver
    Capabilities [{platform=MAC, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/var/folders/wx/qt_77kv53270dwfh0s15vbg40000gn/T/.org.chromium.Chromium.6YxstT}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=40.0.2214.111, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]
        at /usr/local/lib/node_modules/protractor/node_modules/jasminewd2/index.js:104:16
        at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1582:15
        at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
        at notify (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:465:12)


3) Projects Single Site Enter 3 Questions and delete one
  Message:
[...]
```

**Comment by hankduan** [comment] 2015-02-09 19:37
Thanks for the clarification. I haven't tried to reproduce yet, but if that's the case it's a bug. Jasmine should report the stack trace under 'non-verbose' mode for these errors.

**Comment by hankduan** [comment] 2015-02-09 23:29
Fixed here: https://github.com/angular/protractor/pull/1795

background:
related: https://github.com/jasmine/jasmine/issues/734
The code for protractor is already in place, and we were waiting for jasmine to release the new version to support this. For now, you can just apply the change to your machine (i.e. npm install jasmine 2.2.1) and it should automagically work.

**Comment by quarklemotion** [comment] 2015-04-21 23:19
@ceelian I was looking for the same verbose configuration option after updating protractor to use jasmine2.  My protractor suite is large and takes 5+ minutes to run.  With the default simpler test reporting in jasmine2, I am not able to kill the suite after an early failure and see the failure details - I have to wait until protractor completes.  This is not ideal for my team's workflow.  I started using the following reporter for jasmine2 that gives the verbose test feedback I was looking for:

**Comment by johnpaxton** [comment] 2015-04-22 04:21
@quarklemotion Thanks for that suggestion. It's much nicer output than stock jasmine2. Also, seems to actually have colors!

**Comment by juliemr** [comment] 2015-05-20 16:54
We've upgraded Jasmine to 2.3 in the latest version of Protractor, so this should be fixed now.

**Closed by juliemr** 2015-05-20 16:54 UTC
Labels: external bug filed, framework: jasmine2

**Comment by cboden** [comment] 2015-05-20 21:05
I'm running protractor#2.1.0 and jasmine-core#2.3.4 and am `isVerbose` still has no effect.

**Comment by hankduan** [comment] 2015-05-20 21:22
I think the idea isn't to introduce `isVerbose`. Protractor is using jasmine as is, and there is no `isVerbose` option. When Julie mentioned this being fixed, she is referring to the fact that the stack did not show properly before. @cboden What are you trying to get out of `isVerbose` that jasmine/protractor isn't providing you?

**Comment by cboden** [comment] 2015-05-20 21:24
I was looking for details on which tests were being run. I've implemented @quarklemotion's solution since; it's giving me what I was looking for.

**Comment by rdev5** [comment] 2015-06-17 17:22
Same as @cboden and @quarklemotion, I was able to take advantage of much more verbose output by configuring protractor with the following onPrepare() in config.js:

```
  onPrepare: function() {
    var SpecReporter = require('jasmine-spec-reporter');
    jasmine.getEnv().addReporter(new SpecReporter({displayStacktrace: true}));
  }
````
Thanks to https://github.com/bcaudan/jasmine-spec-reporter/blob/master/docs/protractor-configuration.md#protractor-configuration

**Comment by rmwever** [comment] 2015-10-15 20:06
Thanks @quarklemotion, your solution helped me as well

**Comment by BhupenderAgarwal** [comment] 2016-04-27 12:13
Thanks @quarklemotion , the solution you provided worked me me too. Apart from normal verbose feature it has other cool options like prefixing with symbol, ability to customize reporting output.

Appreciate for pointing to the module.

**Comment by indrasantosa** [comment] 2016-10-25 09:36
Works for me too. thanks, @quarklemotion.

**Comment by herringtown** [comment] 2018-01-28 22:06
@rdev5's link is a bit out of date - here's are the links to the current protractor conf: 

* https://github.com/bcaudan/jasmine-spec-reporter/tree/master/examples/protractor
* https://github.com/bcaudan/jasmine-spec-reporter/blob/master/examples/protractor/protractor.conf.js
