### ISSUE TITLE
Unable to run webdriver-manager-update

### ISSUE THREAD

**Issue by samshaikh87** [angular/protractor#4256] opened 2017-05-02 20:30 UTC
Hi there!

Getting the below error when running webdriver-manager update...

C:\Users\pctr294290>webdriver-manager update
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: self signed certificate in certificate chain
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)

Please help.

Bug report
---

- Node Version: ``
- Protractor Version: ``
- Angular Version: ``
- Browser(s): ``
- Operating System and Version ``
- Your protractor configuration file
- A relevant example test
- Output from running the test
- Steps to reproduce the bug
- The URL you are running your tests against (if relevant)

Feature Request
---

- Reasons for adopting new feature
- Is this a breaking change? (How will this affect existing functionality)
Hi there!

Getting the below error when running webdriver-manager update...

C:\Users\pctr294290>webdriver-manager update
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: self signed certificate in certificate chain
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)

Please help.

Bug report
---

- Node Version: ``
- Protractor Version: ``
- Angular Version: ``
- Browser(s): ``
- Operating System and Version ``
- Your protractor configuration file
- A relevant example test
- Output from running the test
- Steps to reproduce the bug
- The URL you are running your tests against (if relevant)

Feature Request
---

- Reasons for adopting new feature
- Is this a breaking change? (How will this affect existing functionality)

**Comment by samshaikh87** [comment] 2017-05-02 20:31
Node Version: `` 6.10.2
Protractor Version: `` 5.1.1
Operating System and Version `` windows 7

**Comment by bobbai** [comment] 2017-05-03 02:58
I faced the same issue and you can run the following as workaround:
```
npm cache clean
webdriver-manager update --ignore_ssl
```

**Comment by NickTomlin** [comment] 2017-05-04 02:04
This is typically due to a proxy or other networking layer that is sitting between you and the servers hosting the browser binaries. @bobbai's solution should work but the underlying issue is a networking one.

I'm going to go ahead and close this as it isn't an issue with webdriver-manager itself.

**Closed by NickTomlin** 2017-05-04 02:04 UTC

**Comment by JimTheMan** [comment] 2018-01-31 20:21
I too am behind a corporate firewall and am getting this error message. The suggested commands @bobbai suggested are not working. Is there anything else I can do or shall I open a new issue?

**Comment by MikePot** [comment] 2018-10-23 14:50
@JimTheMan Same here, I can't do webdriver-manager update, but I tried to copied all the files needed, and 'webdriver-manager start' does get run; then when I tried to run the first Protractor test (copied from the tutorial page), it doesn't get the page displayed on the chrome browser. Anyone can provide any help, it will be highly appreciated!!

**Comment by MikePot** [comment] 2018-10-23 23:30
@ashishbansali Thank you so much, I tried that. And received an unhandled error. Do you have any guess? 

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND userID userID:443

**Comment by MikePot** [comment] 2018-10-24 15:32
Thank you so much!! I still have the same error, see below.  Do you know if this is caused by the proxy may be not correct?

**Comment by MikePot** [comment] 2018-10-26 18:02
@ashishbansali Sorry to bug you, here is the response after running 'webdriver-manager update --proxy --ignore_ssl', the screen capture I sent you was not displayed, so I attached it here as a file. 

[2018-10-26_13-24-47.pdf](https://github.com/angular/protractor/files/2520287/2018-10-26_13-24-47.pdf)

**Comment by MikePot** [comment] 2018-11-09 14:21
I have added proxy and proxy sees traffic to the  registry http://registry.npmjs.org/. But there are traffic to other IPs such as 192.30.1254.16:443, could the code be updated to going to the registry place for all traffic?  @ashishbansali , do you know if this is a known issue to people who work behind the corporate firewall?
