### ISSUE TITLE
npm install errors out with protractor 2.2.0 in windows

### ISSUE THREAD

**Issue by sivaprasad09** [angular/protractor#2562] opened 2015-09-30 15:36 UTC
While doing npm install i  am getting errors after upgrading protractor version to 2.2.0 in windows.
Getting error as "Cannot find Python Executable "python"

After install python on windows we are good with npm install but tests are not executing.
Is there any dependency with python with Protractor 2.2.0 version?
Why spec is taking Absolute path?

**Comment by juliemr** [comment] 2015-09-30 17:17
Duplicate of https://github.com/angular/protractor/issues/2068 for the python issue. Some optional deps use `node-gyp` which requires python.

I don't have enough info to help with tests not executing or the absolute path issue. Please take a look at https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions to see if that can help, or open up a new issue if you have found a bug.

**Closed by juliemr** 2015-09-30 17:17 UTC
