### ISSUE TITLE
Elements outside viewport in Protractor@3.1.0

### ISSUE THREAD

**Issue by martinsznapka** [angular/protractor#2959] opened 2016-02-18 15:43 UTC
If you run with latest Firefox@44.0.1

    describe('Protractor@3.1.0 issue', function () {
        it('should work', function () {
            browser.get('https://angularjs.org');
    
            element(by.model('todoList.todoText')).sendKeys('write first protractor test');
            element(by.css('a.learn-link')).click();
        });
    });

in Protractor@3.0.0, then everything works like expected. In Protractor@3.1.0 test fails.

Looks like elements outside of viewport are not reachable anymore.

    Failed: Element is not clickable at point (633.5, 21.5). Other element would receive the click: <a href="#" class="dropdown-toggle" data-toggle="dropdown"></a>

**Comment by martinsznapka** [comment] 2016-02-22 13:29
The issue is related to Selenium version. With version >= 2.49.0 it doesn't work.

Works:
Firefox@44.0.2 + Protractor@3.1.1 + selenium-server-standalone-2.48.2.jar

Doesn't work:
Firefox@44.0.2 + Protractor@3.1.1 + selenium-server-standalone-2.49.0.jar

**Comment by gsagenjr** [comment] 2016-02-22 22:27
I can confirm I am having this issue as well, switching to 2.48.2 does 'fix' it.

**Comment by NickTomlin** [comment] 2016-02-23 01:14
I think https://github.com/SeleniumHQ/selenium/issues/1202 applies here.

Looks like this can also be fixed by configuring `elementScrollBehavior` in `>= 2.50.1`. Not sure what the best path is here because upgrading would still probably require a config change for tests.

**Comment by juliemr** [comment] 2016-02-23 18:03
Yes, this is due to the webdriver upgrade, and is intended new behavior (FirefoxDriver now works in the same way as ChromeDriver). See the particular comment https://github.com/SeleniumHQ/selenium/issues/1202#issuecomment-172232971 and below for more info. I'm going to close since this is not Protractor specific and is working as FirefoxDriver intends.

**Closed by juliemr** 2016-02-23 18:03 UTC
Labels: status: external bug filed, type: external bug

**Comment by border-radius** [comment] 2016-03-03 13:26
I'm using this workaround:
```javascript
browser
.executeScript('document.querySelector(".offer.button").scrollIntoView(false)')
.then(function () {
  element(
    by.css('.offer.button')
  ).click();
});
```
