### ISSUE TITLE
Protractor throwing firefox Webdriver Error 

### ISSUE THREAD

**Issue by vivekbrahmadandi** [angular/protractor#3120] opened 2016-04-12 10:27 UTC
The below is the logs of protractor console

WebDriverError: The FirefoxDriver cannot be used after quit() was called.
Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
System info: host: 'NBLAP99', ip: '192.168.7.10', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_71'
Driver info: driver.version: FirefoxDriver
    at WebDriverError (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\error.js:27:10)
    at Object.checkLegacyResponse (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\error.js:580:13)
    at C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:360:15
    at Promise.invokeCallback_ (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1329:14)
    at TaskQueue.execute_ (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2790:14)
    at TaskQueue.executeNext_ (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2773:21)
    at C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2652:27
    at C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:639:7
    at process._tickCallback (node.js:366:9)
[launcher] Process exited with error code 1

**Comment by NickTomlin** [comment] 2016-04-12 17:53
Please follow the [Issue Template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) when opening new issues. Otherwise it's unclear what the issue is and how we can actually help.

I'm going to close this issue, please re-open a new one following the issue template linked above. Thanks! 😄

**Closed by NickTomlin** 2016-04-12 17:53 UTC

**Comment by IAmAnubhavSaini** [comment] 2016-05-30 04:02
Is it created again with the template later?

**Comment by vivekbrahmadandi** [comment] 2016-05-30 15:42
Yes @IAmAnubhavSaini

**Comment by IAmAnubhavSaini** [comment] 2016-06-01 01:43
Well could you point me to that issue?

**Comment by AlexK777** [comment] 2016-06-13 16:46
I am seeing this as well. Was another issue opened for this?
