### ISSUE TITLE
Protractor failed to start firefox latest version - Accessibility support partially disabled

### ISSUE THREAD

**Issue by arjunsinghk3** [angular/protractor#3980] opened 2017-01-16 06:37 UTC
I am trying to run protractor with Firefox latest version. It failed to start Firefox, showing the following warning.

"Accessibility support is partially disabled due to compatibility issues with new Firefox features"

**Comment by mgiambalvo** [comment] 2017-01-17 19:45
Protractor currently only supports Firefox 47, though it can be made to work with Firefox 51 (see https://github.com/angular/protractor/pull/3953) using directConnect. Unfortunately, Firefox 51 will not work using Selenium Standalone 3.0.1 - this is due to a fixed bug (https://github.com/SeleniumHQ/selenium/issues/3115), so we're waiting on the next Selenium release.

Sorry for the inconvience. Once Firefox 51 and the next version of Selenium are released, things will be better.

**Comment by mgiambalvo** [comment] 2017-01-18 21:55
Closing as duplicate of #3823

**Closed by mgiambalvo** 2017-01-18 21:55 UTC
Labels: status: external bug filed, status: fixed for next release
