### ISSUE TITLE
"document unloaded while waiting for result" with href="#"

### ISSUE THREAD

**Issue by eolognt** [angular/protractor#2405] opened 2015-08-05 22:44 UTC
This is my page:

```html
<html ng-app="test" class="ng-scope">
<head>
    <script src="https://code.angularjs.org/1.4.3/angular.min.js"></script>
    <script>angular.module("test", []).controller(function () {});</script>
</head>
<body>
    <a href="#"></a>
</body>
</html>
```

And this is what trigger the following error message:

```javascript
browser.get('data:text/html,<html><head>...')
browser.waitForAngular();
```
> Failed: javascript error: document unloaded while waiting for result

If I remove the hash from the href attribute and for example exchange it with a `/` the error is gone.

I find this behaviour really odd as it happens when running the `waitForAngular()` task.

**Comment by sjelin** [comment] 2015-09-21 16:54
This is very odd.  Are you sure you escaped everything properly?

**Comment by juliemr** [comment] 2015-10-01 00:00
I'm aggressively closing issues that we are unable to reproduce, are support issues specific to one test, or deal with integrations with other projects that we don't directly support. If you feel you have a question, please see https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions. If you still have a bug report or feature request, please open a new issue. Thank you!

**Closed by juliemr** 2015-10-01 00:00 UTC
Labels: needs: more info
