### ISSUE TITLE
Using fdescribe seems to run beforeAll many times and causes test instability

### ISSUE THREAD

**Issue by metaman** [angular/protractor#1743] opened 2015-01-22 00:23 UTC
If I update the protractor config to target one specific test suite then I get all three tests passing consistently.  However if I update the test suite to use fdescribe then the beforeAll function gets called 3 times and at least one of the test fails regularly.  The tests seem to become very unstable.

Using 1.6.0.

**Comment by hankduan** [comment] 2015-01-22 01:53
This is working as intended according to the people at jasmine: https://github.com/jasmine/jasmine/issues/732

Yes the behavior between fdescribe/fit and afterAll/beforeAll feels strange to me too. Protractor could potentially (I haven't investigated this possibility yet) patch the fit/fdescribe to make them work as intended, but that's not a path I really want to go down.

**Comment by juliemr** [comment] 2015-01-22 02:09
Labeling this 'external bug' since I agree we don't want to be patching this, but a more proper label might be 'external WAI'.

**Comment by metaman** [comment] 2015-01-22 08:00
Wow, thanks for the very prompt response. I agree about not patching but it might make sense to document this somewhere for anyone else coming along.

**Comment by juliemr** [comment] 2015-03-18 00:01
I'm closing this, since I think that Jasmine has done what they will.

**Closed by juliemr** 2015-03-18 00:01 UTC
Labels: type: external bug
