### ISSUE TITLE
Do not remove existing files

### ISSUE THREAD

**Issue by blabno** [angular/protractor#2555] opened 2015-09-29 09:41 UTC
When webdriver-manager decides it needs to download new drivers it removes existing ones.
Now if I use `out_dir` flag so that I want webdriver-manager to use cached files and I have 2 different projects with protractor that need different versions of the drivers and run them in turns, then drivers used by previous run will be removed and no cacheing will take place.

**Comment by juliemr** [comment] 2015-09-30 21:49
Duplicate of #2507

**Closed by juliemr** 2015-09-30 21:49 UTC
Labels: component: webdriver-manager, type: feature request
