### ISSUE TITLE
issue on browser.get() with alert window.

### ISSUE THREAD

**Issue by Changsoo-Park** [angular/protractor#4284] opened 2017-05-12 21:57 UTC
Bug report
---
- Node Version: `6.9.x`
- Protractor Version: ``
- Angular Version: ``
- npm version : 4.1.2
- Browser(s): `Chrome`
- Operating System and Version `MacOS Sierra 10.12.4`
- Output from running the test 
: Error Message : E/launcher - unexpected alert open: {Alert text : false}

1. Test Case
Input : Navigate to other page via URL change in address bar
Expected result : Alert window appears. Message : Changes you made may not be saved.
==> And then the script should click on Cancel button or Leave button to verify some features

2. So I used browser.get() to implement it. 
Actual Result : Alert window appears but Protractor return error and stop test run.
Error Message : E/launcher - unexpected alert open: {Alert text : false}
==> Protractor considering the alert window is an Error. (unexpected)

3.       So I’ve used catch() to pass it.

browser.get(url).catch(function() {
    return browser.switchTo().alert().then(function (alert) {
      alert.accept();
      return browser.get(url).then(done);
    });
});
 
Result : Skip the error and navigate to destination page. (Expectation is display alert window without navigate to destination page)
So my opinion is protractor has a defect on browser.get() with alert window.

or is there any other way to implement above test case?

Feature Request
browser.get() should stop when browser alert window appears with no error

- Reasons for adopting new feature
In real situation, the browser alert window is expected but browser.get() is considering it is unexpected. So return error.

- Is this a breaking change? (How will this affect existing functionality)

Thanks

**Comment by NickTomlin** [comment] 2017-05-13 13:22
Could you share the actual error you are receiving after trying to accept the dialog? Also, if you could provide a small minimal example repo reproducing this that would be wonderful. Thanks!

**Comment by Changsoo-Park** [comment] 2017-05-14 15:45
Error Message : 
> protractor

(node:1524) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[10:28:10] I/launcher - Running 1 instances of WebDriver
[10:28:10] I/direct - Using ChromeDriver directly...
Feature: ......

cucumber event handlers attached via registerHandler are now passed the associated object instead of an event
getPayloadItem will be removed in the next major release
  Scenario: Validate warning modal window feature when navigates to other page via Changing URL in address bar
  ✔ Given Application is loaded and user is in add customer page.
  ✔ And Verify the customer header text 'New Customer' is present.
[10:28:23] E/launcher - unexpected alert open: {Alert text : false}
  (Session info: chrome=57.0.2987.110)
  (Driver info: chromedriver=2.29.461585 (0be2cd95f834e9ee7c46bcc7cf405b483f5ae83b),platform=Mac OS X 10.12.4 x86_64)
[10:28:23] E/launcher - UnexpectedAlertOpenError: unexpected alert open: {Alert text : false}
  (Session info: chrome=57.0.2987.110)
  (Driver info: chromedriver=2.29.461585 (0be2cd95f834e9ee7c46bcc7cf405b483f5ae83b),platform=Mac OS X 10.12.4 x86_64)
    at Object.checkLegacyResponse (/Users/......../Documents/......../......../node_modules/selenium-webdriver/lib/error.js:512:13)
    at parseHttpResponse (/Users/......../Documents/......../......../node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/Users/......../Documents/......../......../node_modules/selenium-webdriver/lib/http.js:440:13)
    at process._tickCallback (internal/process/next_tick.js:109:7)
From: Task: Protractor.get(https://.........run.asv-pr.ice.predix.io/customer-management/view/default/details) - reset url
    at Driver.schedule (/Users/......../Documents/......../......../node_modules/selenium-webdriver/lib/webdriver.js:816:17)
    at ProtractorBrowser.executeScriptWithDescription (/Users/......../Documents/......../......../node_modules/protractor/lib/browser.ts:583:24)
    at driver.controlFlow.execute.then.then.then (/Users/......../Documents/......../......../node_modules/protractor/lib/browser.ts:888:23)
    at ManagedPromise.invokeCallback_ (/Users/......../Documents/......../......../node_modules/selenium-webdriver/lib/promise.js:1366:14)
    at TaskQueue.execute_ (/Users/......../Documents/......../......../node_modules/selenium-webdriver/lib/promise.js:2970:14)
    at TaskQueue.executeNext_ (/Users/......../Documents/......../......../node_modules/selenium-webdriver/lib/promise.js:2953:27)
    at asyncRun (/Users/......../Documents/......../......../node_modules/selenium-webdriver/lib/promise.js:2813:27)
    at /Users/......../Documents/......../......../node_modules/selenium-webdriver/lib/promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:109:7)
[10:28:23] E/launcher - Process exited with error code 199

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/Cellar/node/7.7.4/bin/node" "/usr/local/bin/npm" "run" "_e2e_"
npm ERR! node v7.7.4
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! ........@0.0.1-1 _e2e_: `protractor`
npm ERR! Exit status 199
npm ERR! 
npm ERR! Failed at the ........@0.0.1-1 _e2e_ script 'protractor'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ........ package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ........
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ........
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/......../Documents/......../......../npm-debug.log

Example : 
i.e.) Testing on Edit Profile page
Scenario : User navigates to any other page in the application via changing URL in address bar 
Expectation : receive a warning when user try to navigate away from an Edit Profile page so that user doesn't accidentally lose his/her work.

Test Steps : 
1. Navigate to the Edit Profile page
2. Enter any value
3. navigates to any other page in the application via changing URL in address bar
==> here browser.get(url).then(done); makes above unexpected alert error. 
==> but the alert window is expected one.

Thanks

**Comment by NickTomlin** [comment] 2017-05-15 02:52
I'm not able to reproduce using a [simple example application](https://github.com/NickTomlin/protractor-minimal-working-example/blob/master/example_spec.js#L4-L12). Can you provide a small repository that reproduces the issue? Otherwise it's difficult to understand the root cause here. 

Also, you haven't supplied an angular version in your issue. Are you using this on a non angular page?

**Comment by Changsoo-Park** [comment] 2017-05-15 12:39
Hi Nick
Your scripts are working well in my local. (in our framework)I think our configuration or application has some kinds of different environment than normal one.
I will research on it and let you know the details.Thanks for your quick reply.
Changsoo Park 

    On Sunday, May 14, 2017 9:52 PM, Nick Tomlin <notifications@github.com> wrote:
 

 I'm not able to reproduce using a simple example application. Can you provide a small repository that reproduces the issue? Otherwise it's difficult to understand the root cause here.Also, you haven't supplied an angular version in your issue. Are you using this on a non angular page?—

**Comment by NickTomlin** [comment] 2017-05-15 13:41
Okay that is good to know. I'm going to go ahead and close this issue. If you are having issues configuring your application please [ask a question on StackOverflow](http://stackoverflow.com/questions/ask?tags=protractor).

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks and good luck! 😄

**Closed by NickTomlin** 2017-05-15 13:41 UTC

**Comment by Changsoo-Park** [comment] 2017-05-15 14:00
It was my bad.

I had to use browser.driver.get() but I used browser.get().
That's why I've got the error.

Thanks for your help Nick!
