### ISSUE TITLE
Passing ElementFinder into executeScript()

### ISSUE THREAD

**Issue by alecxe** [angular/protractor#2290] opened 2015-06-30 20:44 UTC
Would it be possible to avoid calling `getWebElement()` every time there is the need to pass an "element" into `executeScript()`?

For example, being able to write:

    var elm = element(by.id("test"));
    browser.executeScript("arguments[0].scrollIntoView();", elm);

instead of:

    var elm = element(by.id("test"));
    browser.executeScript("arguments[0].scrollIntoView();", elm.getWebElement());

I think this ["TODO" line](https://github.com/angular/protractor/blob/6ebc4c3f8b557a56e53e0a1622d1b44b59f5bc04/spec/basic/elements_spec.js#L172) is related to the request:

    // TODO(juliemr): should be able to do this without the getWebElement call

**Comment by juliemr** [comment] 2016-07-14 18:17
Duplicate of https://github.com/angular/protractor/issues/1600

**Closed by juliemr** 2016-07-14 18:17 UTC
Labels: type: feature request
