### ISSUE TITLE
[launcher] 1 instance(s) of WebDriver still running

### ISSUE THREAD

**Issue by amitojduggal** [angular/protractor#2966] opened 2016-02-20 13:19 UTC
The issue reported here  https://github.com/angular/protractor/issues/1130

I can confirm is still being seen with protractor 3.0 and grunt protractor runner 3.0.

The thing is i dont see it while i am working with linux UI, i see it in the CI when we are using xvfb to run the tests, is there some issue concerning protractor sharding feature and xvfb.

its seen only with Chrome and not with firefox.

**Comment by amitojduggal** [comment] 2016-02-22 03:10
My configurations
```
Protractor config:
exports.config = {

    baseUrl: 'https://localhost/app/',
    framework: "jasmine2",
    directConnect: true,
    // run.
    suites: {
        Suite1: 'src/e2e/tests1.js',
        Suite2: 'src/e2e/tests2.js',
        Suite3: 'src/e2e/tests3.js',
        Suite4: 'src/e2e/tests4.js',
        Suite5: 'src/e2e/test5.js',
        Suite6: 'src/e2e/tests6.js',
        Suite7: 'src/e2e/tests7.js',

    },
    allScriptsTimeout: 1200000,
    getPageTimeout: 500000,

    capabilities: {
        'browserName': 'chrome',
        'chromeOptions': {
            'args': ['--disable-extensions', '--incognito', ]
        }
    },

    //
    // See the full list at https://github.com/juliemr/minijasminenode/tree/jasmine1
    jasmineNodeOpts: {
        onComplete: null,
        isVerbose: false,
        showColors: true,
        includeStackTrace: true,
        defaultTimeoutInterval: 1800000,
    },

  };

Grunt config:
protractor: {
            options: {
                keepAlive: false,
                configFile: 'protractor.conf.js'
            },
chrome: {
                options: {
                    keepAlive: false,
                    args: {
                        directConnect: true,
                        capabilities: {
                            'browserName': 'chrome',
                            'shardTestFiles': true,
                            'maxInstances': 4,
                            'chromeOptions': {
                                'args': ['--disable-extensions', '--incognito', ]
                            }
                        }
                    }
                }
            }
}
```

**Comment by NickTomlin** [comment] 2016-02-22 15:03
Thanks for posting your configuration. 

- An example specs as
- Your distro / version of linux
- Your node version
- Does it work without `grunt-protractor-runner`

**Comment by amitojduggal** [comment] 2016-02-23 10:22
Distro: Centos 7
XVFB instance is launched first and then the tests are executed through Jenkins. I see that the problem is happening only when running on CI, on my machine it goes through all the time
Node: 4.3.1
Protractor: 3.0, also tried with 2.5.1
Grunt-Protractor-runner: 3.0 , also tried with 2.1.2
Does it work without grunt-protractor-runner: No
Spec: 
Sorry but its not possible for me to share the exact spec. I hope this will be descriptions.
What my specs are doing is, logging into an app, running and validating searches on a webApp.
 i have many suites that are doing the same work.

I observe that only the last instance of the Webdriver keeps on running.
Can it be probably the timeouts that is causing this problem?

But only and only on Chrome, Firefox is always accurate and closes webdriver instances by itself.

**Comment by juliemr** [comment] 2016-07-14 20:00
Closing as I believe this is a dupe of https://github.com/angular/protractor/issues/2419

**Closed by juliemr** 2016-07-14 20:00 UTC
Labels: status: needs investigation
