### ISSUE TITLE
Issue with ExpectedConditions working with forked browser instances 

### ISSUE THREAD

**Issue by bitliner** [angular/protractor#3761] opened 2016-11-22 12:40 UTC
Bug report
---

- Node Version: `v6.9.1`
- Protractor Version: `4.0.11`
- Angular Version: `1.5.6`
- Browser(s): `chrome`
- Operating System and Version `mac osx`

Code of my test is as following:

```

beforeAll(function(){
  browser2=browser.forkNewDriverInstance();
  return user.login(browser2);
});

beforeEach(function(){
  return browser2.get('/other-page');
});
```

and user.login() is:

```
User.prototype.login=function(browserToUse){
  browser.runLogin()
    .then(function(){
      return browserToUse.wait(EC.urlContains('/home'), 5000*2,'Waiting ofr URL /home');
    });
}
```

It looks like that it executes instructions in the wrong order, that is:

1. user.login(b)
2. browser2.get('/other-page')
3. browserToUse.wait(EC.urlContains('/home'), 5000*2,'Waiting ofr URL /home');

indeed, the 3rd instruction generates a time out exception. But the browser goes through /home URL, it is a problem of synchronization.

I wonder: how is it possible? 

Which is the way to tell protractor: don't use your algorithm for ordering instructions, but I manage the order?

I am using `.then()` for each instruction, but it does not seem enough.

It is worth to note that:
* this test (that includes the beforeAll) have other tests (describe and it) and that before it
* when i run this test by itself, it does not go in timeout
* when i run the whole file, it goes in timeout

**Comment by cnishina** [comment] 2016-11-22 19:52
`beforeAll` is the first to execute then `beforeEach` and not the other way around.

![jasmine order](https://pbs.twimg.com/media/CaVN7OSUUAATX13.jpg:large)

This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!

**Comment by bitliner** [comment] 2016-11-22 22:17
@cnishina your example is wrong, you don't have promises in the beforeAll and beforeEach.

**Comment by bitliner** [comment] 2016-11-22 22:27
It might be more clear on http://stackoverflow.com/questions/40752782/protractor-does-not-synchronize-well-beforeall-and-beforeeach

**Comment by cnishina** [comment] 2016-11-22 22:47
Sorry about the initial close...I misread the issue. Alright I think I have an idea why this is breaking. I think the actual question / issue is "Does EC work on forked browser". Reviewing the EC code I believe it does not.

Could you use the initial browser object (without forking it)? My guess is that this does works. If it works on browser but not the forked browser, this is definitely a limitation on EC and should be fixed.

**Comment by cnishina** [comment] 2016-11-22 22:56
This works:

```
  it('should work with EC', () => {
    let title = 'My AngularJS App';
    let EC = protractor.ExpectedConditions;
    browser.get('http://www.protractortest.org/testapp/ng1/#/form');
    browser.wait(EC.titleIs('My AngularJS App'), 1000);
    browser.get('http://www.protractortest.org/testapp/ng1/#/async');
  });
```

This does not work:

```
  it('should work with EC from a forked instance', () => {
    let browser2 = browser.forkBrowserInstance();
    let title = 'My AngularJS App';
    let EC = protractor.ExpectedConditions;
    browser2.get('http://www.protractortest.org/testapp/ng1/#/form');
    browser.wait(EC.titleIs('My AngularJS App'), 1000);
    browser.get('http://www.protractortest.org/testapp/ng1/#/async');
  });
```

Just some extra notes to self. `ProtractorBrowser` creates a static `ExpectedConditions`. `ExpectedConditions` uses `(<Ptor>global.protractor).browser` when referencing the browser. My initial thoughts are:

- ExpectedConditions should not be static
- a reference to the `browser` instance should be passed to a new `ExpectedConditions` in the `ProtractorBrowser` constructor
- Using a forked instance of browser should get the EC with:

   ```
   let browser2 = browser.forkBrowserInstance();
   let EC = browser2.ExpectedConditions;
   browser2.wait(EC.titleIs('foobar'), 5000);
   ```

**Comment by cnishina** [comment] 2016-11-22 23:07
Confirmed. Will have a PR to fix this.

**Comment by bitliner** [comment] 2016-11-22 23:11
Thank you very much for your help.

Just a note: in your example, that does not work, the wait should be on browser2 in order to make it more similar to my example (of course a fix to make browser to work too is required).

**Comment by cnishina** [comment] 2016-11-22 23:15
@bitliner yup, I sort of modified the example above it and did a quick copy / paste / edit. I just updated the comment to reflect `browser2` and not `browser`

**Closed** 2016-12-01 19:33 UTC
Labels: type: bug
