### ISSUE TITLE
Protractor 3.1.1 doesn't run test for application having .debugInfoEnalbled(false)

### ISSUE THREAD

**Issue by ravitej-klair** [angular/protractor#3009] opened 2016-03-08 00:09 UTC
Pretty new here,

Recently upgraded to Protractor 3.1.1 and testing the debug feature [(148f020)](https://github.com/angular/protractor/commit/148f020bf4bbd71e17326581a2f7ed6f4ff55832)

I understand that the debug flag added in the protractor.js helps to run the tests for applications with `.debugInfoEnabled(false);`

But my test doesn't without the following hack 
`browser.executeScript('window.name = "NG_ENABLE_DEBUG_INFO!"');`

But wasn't this the whole point of upgrading to Protractor 3.1.1 so you don't have to do this?!

Any suggestions?

**Comment by juliemr** [comment] 2016-03-08 01:08
It looks like that commit has the order wrong - Angular first checks if the string _starts with_ NG_ENABLE_DEBUG_INFO, and then checks for the NG_DEFER_BOOTSTRAP string. Needs to be switched.

**Comment by ravitej-klair** [comment] 2016-04-06 17:26
Hi Guys,

I'm using protractor 3.2.2 now and still not able to run my test WITHOUT hacking it with 
`browser.executeScript('window.name = "NG_ENABLE_DEBUG_INFO!"');`

**Comment by juliemr** [comment] 2016-04-21 01:34
I'm rolling back the associated PR since it is causing issues with older versions of Angular.

Note that if you are not using manual bootstrap, we should be able to turn on debug info by using Protractor's default set of mock modules. @ravitej-klair can you provide a test application that we can run against showing where this fails?

**Comment by machtyn** [comment] 2016-04-26 14:26
I'm using Protratctor 3.2.2 and attempted to use elementExplorer.  Here are the results of running various commands.  For details on the setup, see this page: http://stackoverflow.com/questions/36851322/attempting-to-select-angular-component-element-and-getting-an-error?noredirect=1#comment61273847_36851322

> &gt; browser.executeScript('window.name = "NG_ENABLE_DEBUG_INFO!"');
null
> &gt; element(by.css('state-selection-component')).getText()
Error while waiting for Protractor to sync with the page: "Could not find testability for element."
> &gt; element(by.css('state-selection-component')).getLocation()
Error while waiting for Protractor to sync with the page: "Could not find testability for element."
> &gt; element(by.css('state-selection-component')).isEnabled()
Error while waiting for Protractor to sync with the page: "Could not find testability for element."
> &gt; element(by.css('state-selection-component div > p')).isEnabled()
Error while waiting for Protractor to sync with the page: "Could not find testability for element."
> &gt;

**Comment by machtyn** [comment] 2016-04-26 18:13
I noticed that the status and type was changed.  I'm not sure if you need something more reproducible, but if it helps, here's what I did. 
Create a new folder (angular2play).
Follow instructions on Angular 2 quick start guide, with the following addition to the package.json file:
`"devDependencies": {  ...,  "protractor": "^3.2.2",  ... }`

Run npm start which displayed the "My First Angular 2 App" text appropriately.
In a new terminal, run `protractor --elementExplorer`
Within elementExplorer run the following commands:
` 
> browser.get('http://localhost:3000')`
` > element(by.css('my-app h1')).getText();`
`Error while waiting for Protractor to sync with the page: "Could not find testability for element."`

See attached file for the result of 
` > element(by.css('my-app h1'));`
[elementResult.txt](https://github.com/angular/protractor/files/237196/elementResult.txt)

This was performed on a MacOS (El Capitan 10.11.4). For the tutorial, I copied the text and pasted it in the files using Sublime Text (I decided to remove the IDE variable).

$ npm ls --depth=0
angular2play@1.0.0 /Users/jgosnell/Projects/angular2play
├── angular2@2.0.0-beta.16
├── concurrently@2.0.0
├── es6-shim@0.35.0
├── lite-server@2.2.0
├── protractor@3.3.0
├── reflect-metadata@0.1.2
├── rxjs@5.0.0-beta.2
├── systemjs@0.19.26
├── typescript@1.8.10
├── typings@0.8.1
└── zone.js@0.6.12

**Comment by juliemr** [comment] 2016-04-26 18:26
OH this is for Angular2. Angular2 does not respond to the `NG_ENABLE_DEBUG_INFO` window name modifier. You'll need to change the mode in the application you are serving - no way around that in Angular2.

I'm not sure if that was the original issue from @ravitej-klair or not, but in either case, I'm closing this as infeasible to change for now. See instead clean new issue: https://github.com/angular/protractor/issues/3174

**Closed by juliemr** 2016-04-26 18:26 UTC
Labels: status: needs more info, type: bug (unconfirmed)
