### ISSUE TITLE
click() doesn't work in IE 11 but works in Chrome on the same elements

### ISSUE THREAD

**Issue by sssalib42** [angular/protractor#2244] opened 2015-06-12 22:22 UTC
I have two clickable elements on my webpage, which is a login page. One is a remember-me checkbox, and the other is a login button. The code below executes successfully on chrome. However, when I run the test against IE 11, the tests actually pass! But the buttons are never clicked. Only the 'will recieve a login error' test fails with IE because the error message is never presented since the login button is never clicked.

Here is the code:

    //run test
    describe('Test my Login webpage', function () {

    var usernameInput = element(by.id('UserName'));
    var passwordInput = element(by.id('Password'));
    var loginButton   = element(by.tagName('button'));
    

    it('will open the login webpage', function () {
        browser.get('http://<my website>/Account/Login');
    });

    it('will click the remember-me checkbox', function () {
        expect(element(by.id('RememberMe')).isSelected()).not.toBeTruthy();
        element(by.id('RememberMe')).click();
    });

    it('will type a username', function () {

        expect(element(by.id('UserName')).isDisplayed()).toBe(true);
        usernameInput.sendKeys('testing...').then(function () {
            expect(element(by.id('UserName')).getText()).toBe('');
        });
    });

    it ('will type a password', function () {
        expect(element(by.id('UserName')).isDisplayed()).toBe(true);

        passwordInput.sendKeys('fakePassword').then(function () {
            expect(element(by.id('Password')).getText()).toContain('');
        });
    });

    it('will click login button', function () {
        expect(loginButton.isDisplayed()).toBe(true);
        loginButton.click();

        browser.waitForAngular();

        usernameInput.clear();
        usernameInput.sendKeys('my second attempt');
    });
    it('will recieve a login error', function () {
        expect(element(by.css('.error-msg')).isDisplayed()).toBe(true);
        //expect(element(by.class('error-msg')).getText()).toMatch('Username or password was invalid, please retry');
    });
    });

**Comment by sssalib42** [comment] 2015-06-17 18:41
Pumping the Thread. @sjelin , can you please clarify the process, as in what I should expect, or when I may receive back a response. Also, thanks for all the help guys! There is so much work you all have put into protractor and in responding to open issues associated with it.

**Comment by sjelin** [comment] 2015-06-30 18:01
Uh, we'll work on it when we get a chance.  Normally we work on these issues at end of quarter (i.e. right now), but we're busier than usual because of Angular 2.

**Comment by juliemr** [comment] 2015-09-30 23:55
I'm aggressively closing issues that we are unable to reproduce, are support issues specific to one test, or deal with integrations with other projects that we don't directly support. If you feel you have a question, please see https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions. If you still have a bug report or feature request, please open a new issue. Thank you!

**Closed by juliemr** 2015-09-30 23:55 UTC
Labels: browser: IE, needs: investigation

**Comment by yuri-kalinin** [comment] 2016-06-16 14:21
For me the reason was that I had my **global scaling in Windows set to >100%** (Desktop > rclick > Display Settings). Apparently this caused IEDriver to click on the wrong coordinates.
Not a Protractor issue, posting for the sake of other people that will end up here googling for it.

**Comment by nsmaniqa** [comment] 2019-06-17 11:50
Is Protractor support IE11?

I am always facing issue with click action. Any tip for Ie browser. Same code working fine for chrome and Firefox

**Comment by nimatullah** [comment] 2020-02-29 07:03
Hey guys, I have the same issue.
