### ISSUE TITLE
Internet Explorer get errors when redirected.

### ISSUE THREAD

**Issue by Urriel** [angular/protractor#3264] opened 2016-06-13 16:54 UTC
Bug report
---

- Node Version: `6.2.1`
- Protractor Version: `3.3.0`
- Browser(s): `Internet Explorer 11`
- Operating System and Version `Windows 8.1`
- Your protractor configuration file

```
exports.config = {
        seleniumAddress: 'http://localhost:4444/wd/hub',

        capabilities: {
            browserName: 'internet explorer'
        },

        specs: ['../specs/*.spec.js'],
        allScriptsTimeout: 60000,

        resultJsonOutputFile: 'test/results/ie/ptor-out.json',

        // Options to be passed to Jasmine-node.
        onPrepare: function () {
            var reporters = require('jasmine-reporters');
            jasmine.getEnv().addReporter(
                new reporters.JUnitXmlReporter({
                    savePath: 'test/results/ie/'
                })
            );
        },

        afterLaunch: function () {
            var reporter = require('protractor-multicapabilities-htmlreporter');
            reporter.generateHtmlReport('test/results/ie/ptor-out.json', 'Automation Results', 'test/results/ie/report.html');
        },

        jasmineNodeOpts: {
            showColors: true,
            defaultTimeoutInterval: 300000
        }
    };
```

- A relevant example test

My application redirect when I have successfully entered my logins information. This cause an error, only on Internet Explorer. It happen also when a sub-domain redirect me to the login page.

- Output from running the test
```
Message:
    Failed: Page reload detected during async script (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 1.11 seconds
    Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
    System info: os.name: 'Windows 8.1', os.arch: 'x86', os.version: '6.3', java.version: '1.8.0_91'
    Driver info: org.openqa.selenium.ie.InternetExplorerDriver
    Capabilities [{browserAttachTimeout=0, enablePersistentHover=true, ie.forceCreateProcessApi=false, pageLoadStrategy=normal, ie.usePerProcessProxy=false, ignoreZoomSetting=false, handlesAlerts=true, version=11, platform=WINDOWS, nativeEvents=true, ie.ensureClean
Session=false, elementScrollBehavior=0, ie.browserCommandLineSwitches=, requireWindowFocus=false, browserName=internet explorer, initialBrowserUrl=http://localhost:40913/, takesScreenshot=true, javascriptEnabled=true, ignoreProtectedModeSettings=false, enableElemen
tCacheCleanup=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=dismiss}]
    Session ID: e40a6c69-7335-42da-a32d-0d0a9440e3da
  Stack:
    WebDriverError: Page reload detected during async script (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 1.11 seconds
    Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
    System info: os.name: 'Windows 8.1', os.arch: 'x86', os.version: '6.3', java.version: '1.8.0_91'
    Driver info: org.openqa.selenium.ie.InternetExplorerDriver
    Capabilities [{browserAttachTimeout=0, enablePersistentHover=true, ie.forceCreateProcessApi=false, pageLoadStrategy=normal, ie.usePerProcessProxy=false, ignoreZoomSetting=false, handlesAlerts=true, version=11, platform=WINDOWS, nativeEvents=true, ie.ensureClean
Session=false, elementScrollBehavior=0, ie.browserCommandLineSwitches=, requireWindowFocus=false, browserName=internet explorer, initialBrowserUrl=http://localhost:40913/, takesScreenshot=true, javascriptEnabled=true, ignoreProtectedModeSettings=false, enableElemen
tCacheCleanup=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=dismiss}]
    Session ID: e40a6c69-7335-42da-a32d-0d0a9440e3da
        at WebDriverError (C:\Users\Administrator\Desktop\Projects\Protractor_Test_Runner\node_modules\selenium-webdriver\error.js:27:5)
        at Object.checkLegacyResponse (C:\Users\Administrator\Desktop\Projects\Protractor_Test_Runner\node_modules\selenium-webdriver\error.js:580:13)
        at C:\Users\Administrator\Desktop\Projects\Protractor_Test_Runner\node_modules\selenium-webdriver\lib\webdriver.js:360:15
        at Promise.invokeCallback_ (C:\Users\Administrator\Desktop\Projects\Protractor_Test_Runner\node_modules\selenium-webdriver\lib\promise.js:1329:14)
        at TaskQueue.execute_ (C:\Users\Administrator\Desktop\Projects\Protractor_Test_Runner\node_modules\selenium-webdriver\lib\promise.js:2790:14)
        at TaskQueue.executeNext_ (C:\Users\Administrator\Desktop\Projects\Protractor_Test_Runner\node_modules\selenium-webdriver\lib\promise.js:2773:21)
        at asyncRun (C:\Users\Administrator\Desktop\Projects\Protractor_Test_Runner\node_modules\selenium-webdriver\lib\promise.js:2652:27)
        at C:\Users\Administrator\Desktop\Projects\Protractor_Test_Runner\node_modules\selenium-webdriver\lib\promise.js:639:7
        at process._tickCallback (internal/process/next_tick.js:103:7)
    From: Task: Run it("#002 Should be able to sign in") in control flow
        at Object.<anonymous> (C:\Users\Administrator\Desktop\Projects\Protractor_Test_Runner\node_modules\jasminewd2\index.js:81:14)
    From asynchronous test:
    Error
        at Suite.<anonymous> (C:\Users\Administrator\Desktop\Projects\Protractor_Test_Runner\specs\box_#001_start_test_suite.spec.js:14:1)
        at Object.<anonymous> (C:\Users\Administrator\Desktop\Projects\Protractor_Test_Runner\specs\box_#001_start_test_suite.spec.js:3:1)
        at Module._compile (module.js:541:32)
        at Object.Module._extensions..js (module.js:550:10)
        at Module.load (module.js:458:32)
        at tryModuleLoad (module.js:417:12)
```

- Steps to reproduce the bug

The application need to redirect once the credentials are correct.

**Comment by juliemr** [comment] 2016-07-01 19:15
Duplicate of https://github.com/angular/protractor/issues/2567

**Closed by juliemr** 2016-07-01 19:15 UTC
Labels: OS: windows, type: bug (unconfirmed)
