### ISSUE TITLE
 StaleElementReferenceError even if element there is in page

### ISSUE THREAD

**Issue by teo89** [angular/protractor#2327] opened 2015-07-10 12:28 UTC
I am trying to click a button  but i get all the time that error 
StaleElementReferenceError: stale element reference: element is not attached to the page document

I have tried 
1. element(by.xpath("//button[@ng-click='save()']")).click();
2.var element= element(by.xpath("//button[@ng-click='save()']"));
browser.driver.wait(protractor.until.elementIsVisible(element), 300000).then(function(result){
									if(result){
										element.click();
									}
								});

I didn't have any result and i am sure that button is visible

**Comment by sjelin** [comment] 2015-07-10 19:41
Are you sure it's the *same* element?  Like, if the page reloaded or something and a duplicate of the original element was put on the page, Selenium would still lose track of it.

**Comment by juliemr** [comment] 2015-09-30 21:59
Closing stale issues. Please open a new issue if you feel there is still a general bug.

**Closed by juliemr** 2015-09-30 21:59 UTC
Labels: needs: more info
