### ISSUE TITLE
When I run scroll into view it doesn't scroll till end by provided element

### ISSUE THREAD

**Issue by pradiipyadav** [angular/protractor#2517] opened 2015-09-22 12:43 UTC
var lastElement  = element(by.xpath("//li[text()='Users']"));
browser.executeScript('arguments[0].scrollIntoView()', lastElement.getWebElement());

It goes down twice then stops.
Using chrome and firefox, jasmine2, Protractor 2.1.0, node 0.12.7,

**Comment by juliemr** [comment] 2015-09-23 19:16
I'm not sure exactly what the issue is. What do you mean 'by provided element' or 'goes down twice then stops'? What are you expecting to happen? What does the page you're testing look like?

**Comment by pradiipyadav** [comment] 2015-09-24 05:20
![view page scrollbar 1](https://cloud.githubusercontent.com/assets/5370400/10065787/a74c6d84-62a8-11e5-8b7a-cefef04551b6.png)

The page looks like attached screenshot and I am referring to inner scroll bar.
And the last element is element at bottom from list of issue shown in provided screenshot, so by when I run above code scroll bar doesn't go to bottom.

Expecting: When I run above code scroll should scroll to bottom.

Thanks in advance.

**Comment by juliemr** [comment] 2015-09-24 16:11
What happens when you run that script, `arguments[0].scrollIntoView()`, using the expected element in the browser console? Does it work in that case?

**Comment by pradiipyadav** [comment] 2015-09-25 10:22
Yes, when I run the script it scrolls the scroll bar a bit down but do not take scroll bar to bottom(my last element is hidden at bottom).
As I have more than 250 option which are currently hidden, so it should scroll to bottom to see last option

**Comment by juliemr** [comment] 2015-10-01 00:24
It sounds like this is an issue with how scrolling works in general on your application, not something specific to Protractor, then. Closing, as not an issue with Protractor.

**Closed by juliemr** 2015-10-01 00:24 UTC
Labels: needs: more info
