### ISSUE TITLE
Browser.pause not working with node8

### ISSUE THREAD

**Issue by zerdos** [angular/protractor#4344] opened 2017-06-20 12:08 UTC
Bug report
---
Browser.pause throws error in the console.

Hint:
https://github.com/angular/protractor/blob/master/lib/debugger/debuggerCommons.js
Line1: 
```var baseDebugger = require('_debugger');```

In node 7.10, it makes sense:
https://github.com/nodejs/node/blob/v7.10.0/lib/_debugger.js

But from 8.0, this file is missing :(
https://github.com/nodejs/node/blob/v8.0.0/lib/_debugger.js

- Node Version: `8.1.2`
- Protractor Version: `5.1.2`

**Comment by pmowrer** [comment] 2017-06-20 18:24
Dupe of https://github.com/angular/protractor/issues/4307

**Closed** 2017-07-11 18:25 UTC
