### ISSUE TITLE
cannot install protractor: types/selenium-webdriver' is not in the npm registry

### ISSUE THREAD

**Issue by atrascau** [angular/protractor#3645] opened 2016-10-14 15:58 UTC
**npm install -g protractor**
npm ERR! Linux 4.4.0-42-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "protractor"
npm ERR! node v4.6.0
npm ERR! npm  v3.10.8
npm ERR! code E404

npm ERR! 404 Not Found: @types/selenium-webdriver
npm ERR! 404 
npm ERR! 404  '@types/selenium-webdriver' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'protractor'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by NickTomlin** [comment] 2016-10-14 17:23
I can't reproduce this on a debian/osx machine; the types package is also definitely in the registry. 

If you continue to have issues I would imagine this is something with cache/registry configuration for your local version of NPM. 

I'm going to close this issue for now; please follow up on StackOverflow or the NPM issues thread. 
If this turns out to be an issue with protractor itself please open a new issue with some reproducible steps.

Thanks!

**Closed by NickTomlin** 2016-10-14 17:23 UTC

**Comment by anuradhaganapathi** [comment] 2016-10-20 13:44
I was also facing the same error. I got it resolved after updating the npm version.(>1.9)

**Comment by atrascau** [comment] 2016-10-20 13:50
My npm version is 3.10.8.
The problem was indeead with the registry configuration. I changed it with the official npm one and everything worked.

**Comment by Piyush-Jeswani** [comment] 2017-10-16 06:50
My npm version is 3.10.10 and m facing the same issue. 
Can anyone help with steps ?

Thanks in advance.

**Comment by Piyush-Jeswani** [comment] 2017-10-16 07:02
I upgraded to latest using command 
npm install -g npm@latest

It got me to 5.5.1
Still its an issue.
