### ISSUE TITLE
ESLint protractor plugin

### ISSUE THREAD

**Issue by alecxe** [angular/protractor#2884] opened 2016-01-29 04:55 UTC
This is a discussion issue.

I'm starting to work on the [`eslint-plugin-protractor`](https://github.com/alecxe/eslint-plugin-protractor) package which is a plugin to `ESLint` static code analysis tool. I need you guys to think of what do people usually do wrong when writing Protractor tests in order to make a set of `ESLint` rules that would help to spot problems early during the static code analysis.

What I'm currently thinking about:

 * `browser.actions()` without `perform()`. Example violations:

         browser.actions().mouseMove(elm).click();
         browser.actions.dragAndDrop(elm1, elm2);

* `browser.executeScript()` called with an `ElementFinder` as an argument (and not a `WebElement`). Example violations:

        browser.executeScript("arguments[0].scrollIntoView();", elm);

We might even enforce (if possible) some of the _Style Guide_ suggestions/rules.

Would appreciate any help with that. Thanks!

**Comment by sjelin** [comment] 2016-01-29 10:27
@juliemr @andresdominguez

**Comment by alecxe** [comment] 2016-02-05 14:34
Currently implemented 3 rules (some more are coming): 

 * [missing-perform](https://github.com/alecxe/eslint-plugin-protractor/blob/master/docs/rules/missing-perform.md)
 * [missing-wait-message](https://github.com/alecxe/eslint-plugin-protractor/blob/master/docs/rules/missing-wait-message.md)
 * [no-browser-sleep](https://github.com/alecxe/eslint-plugin-protractor/blob/master/docs/rules/no-browser-sleep.md)

Thinking about warning about the `by.xpath` usage to be complaint with the style guide, but not sure about this one - sometimes XPaths help to get to things you cannot easily get with other types of locators.

Anyway, let me know if you have any other ideas. Thanks.

**Comment by NickTomlin** [comment] 2016-02-05 15:02
Nice! 

It's minor, but I wonder if having something that advocates for `$` and `$$` shorthand (instead `element(by.css` might be helpful. 

I think the xapth check might be helpful, you can always ignore an individual warning if using xpath  is absolutely necessary.

**Comment by alecxe** [comment] 2016-02-05 15:35
@NickTomlin like these, will implement. Thanks.

**Comment by juliemr** [comment] 2016-07-14 19:28
This is really nifty, thanks!

I'm closing the issue since it's not a bug/feature-request.

**Closed by juliemr** 2016-07-14 19:28 UTC
Labels: type: discussion
