### ISSUE TITLE
Set instance specific parameter value

### ISSUE THREAD

**Issue by venkateswaris** [angular/protractor#3381] opened 2016-07-15 12:06 UTC
Hi,

When running multiple instance, we want to pass different parameter to each of those instance.
 
Example:
i want to set parameter called "name" in all instance.
in instance 1, the value of name = "instance1" 
in instance 2, the value of name = "instance2"
and i want to use this param value in the test.

does protractor support this?

**Comment by juliemr** [comment] 2016-07-15 17:27
I think you're looking for params: https://github.com/angular/protractor/blob/master/docs/referenceConf.js#L280

Closing this as it's a support question, not a bug report or feature request.

**Closed by juliemr** 2016-07-15 17:27 UTC
