### ISSUE TITLE
Protractor for hybrid apps

### ISSUE THREAD

**Issue by LeninChristopher** [angular/protractor#1977] opened 2015-03-27 10:21 UTC
can we use protractor to automate hybrid apps.. browser testing works fine but how to proceed with hybrid apps.

**Comment by juliemr** [comment] 2015-03-27 18:33
Duplicate of https://github.com/angular/protractor/issues/1940

**Closed by juliemr** 2015-03-27 18:33 UTC

**Comment by LeninChristopher** [comment] 2015-03-27 18:47
>
> Hi,

We want to implement Protractor in all the angular projects in our
> company CSC so need your support & guidance.. Kindly let us know your team
> availability we will have a conference call.


Can you please clarify following
1. Protractor support for hybrid apps release date
2. How to work with date picker controls

Regards
Lenin Christopher

**Comment by LeninChristopher** [comment] 2015-03-27 19:19
We would like to implement it all our angular projects...Can you please clarify following
1. Protractor support for hybrid apps release date 
2. How to work with date picker controls

**Comment by LeninChristopher** [comment] 2015-03-27 19:23
We would like to implement protractor all our angular projects.. Please clarify the following
1. Protractor support for hybrid apps release date (showstopper for us now)
2. How to work with date picker controls
3. On switching over to new page the controls in navigated page not getting identified..it displays error as element not found
