### ISSUE TITLE
angular chained filter not updating

### ISSUE THREAD

**Issue by ststrobel** [angular/protractor#1986] opened 2015-03-28 19:11 UTC
Hi all,

first of all, thanks for the great testing framework!
But I am currently facing an issue with angular's ng-repeat directive containing multiple, piped filters. Although I can see Protractor see click the sort/toggle button, the list does not change.

However, when I execute it manually, it works just fine!

Please find how I call Protractor:
```javascript
element(by.id('customers_sort_id')).click();
browser.driver.sleep(500);
browser.waitForAngular();
expect(element.all(by.repeater('c in list.customers')).get(0).all(by.tagName('td')).first().getText()).toEqual('500');
```

I have built in the sleep command as well as the waitForAngular call just for debugging reasonst, but they also change nothing.

This is the HTML:
```html
<tr class="clickable" ng-repeat="c in list.customers | filter : list.companyFilter.visible | filter : list.searchFilter | orderBy : list.orderBy : list.reverse" ng-click="detailOn(c.id)">
```

This is how the filter variable is set:
```javascript
$scope.toggleSort = function(column) {
	if($scope.list.orderBy == column) {
		$scope.list.reverse = !$scope.list.reverse;
	}
	$scope.list.orderBy = column;
};
```

Neither the orderBy nor the reverse filter do anything.

Thanks for any input!
Stefan

**Comment by juliemr** [comment] 2015-03-30 22:03
This looks like it's not a generic issue, so closing as a question:

 Please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks! 

If you can show us a reproducible test case, then we can help debug.

**Closed by juliemr** 2015-03-30 22:03 UTC

**Comment by ststrobel** [comment] 2015-03-31 21:47
Hi Julie,

sorry for posting my question in the wrong place.
I have opened a [stackoverflow question] (http://stackoverflow.com/questions/29379129/angular-chained-orderby-not-updating-when-running-protractor-tests-in-browser) for it.

Thanks!
