### ISSUE TITLE
Protractor is throwing an error when executing with restartBrowserBetweenTests set to true

### ISSUE THREAD

**Issue by Saurabh06** [angular/protractor#3487] opened 2016-08-19 13:59 UTC

**Comment by NickTomlin** [comment] 2016-08-19 14:14
Hi there,

Please follow the [Issue Template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) when opening new issues. Otherwise it's unclear what the issue is and how we can actually help.

I'm going to close this issue, please re-open a new one following the issue template linked above. Thanks! 😄

**Closed by NickTomlin** 2016-08-19 14:14 UTC
