### ISSUE TITLE
Update "selenium-webdriver" for Node 4 compatibility

### ISSUE THREAD

**Issue by mzgol** [angular/protractor#2544] opened 2015-09-27 17:38 UTC
Currently included selenium-webdriver@2.45.1 depends on a ws version with some broken optional dependencies. Since they're optional this should work fine in theory but I found that's not always the case (see https://github.com/npm/npm/issues/9772), especially if one updates npm to the now stable version 3.

selenium-webdriver@2.47.0 installs fine on Node 4.1.1.

**Comment by surfjedi** [comment] 2015-09-28 02:11
+1 I have been having issues across testing environments also and found updating both selenium(to 2.47.1) and the chromedriver(to 2.19) have improved consistency. 

there seem to be some inconsistencies in current master - what webdriver version to be installed, so I in package.json it has 2.45.1 not 2.47.1, but inside the config.json file it has 2.47.1. SO even if you update it might not go to the correct version.

Ill try to do  a pull request

**Comment by sjelin** [comment] 2015-09-28 07:28
We're working on it.  This is a duplicate of a few other issues.

**Closed by sjelin** 2015-09-28 07:28 UTC

**Comment by juliemr** [comment] 2015-09-28 17:55
Duplicate issue: https://github.com/angular/protractor/issues/2245
