### ISSUE TITLE
 ScriptTimeoutError: Timeout expired waiting for async script (WARNING: The server did not provide any stacktrace information)

### ISSUE THREAD

**Issue by vivekbrahmadandi** [angular/protractor#3122] opened 2016-04-12 11:25 UTC
A Jasmine spec timed out. Resetting the WebDriver Control Flow.
F

Failures:
1) ND Child Reseller creation and activation suite Create Sales Team
  Message:
    Failed: Timeout expired waiting for async script (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 95.06 seconds
    Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
    System info: host: 'NBLAP99', ip: '192.168.7.10', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_71'
    Session ID: bfc6de8b-fd48-49f3-ab0e-899c4b38553c
    Driver info: org.openqa.selenium.ie.InternetExplorerDriver
    Capabilities [{platform=WINDOWS, javascriptEnabled=true, elementScrollBehavior=0, ignoreZoomSetting=false, enablePersistentHover=true, ie.ensureCleanSession
viour=dismiss, version=11, pageLoadStrategy=normal, ie.usePerProcessProxy=false, cssSelectorsEnabled=true, ignoreProtectedModeSettings=false, requireWindowFocus
sApi=false, nativeEvents=true, browserAttachTimeout=0, ie.browserCommandLineSwitches=, takesScreenshot=true}]
  Stack:
    ScriptTimeoutError: Timeout expired waiting for async script (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 95.06 seconds

**Comment by NickTomlin** [comment] 2016-04-12 17:50
Please follow the [Issue Template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) when opening new issues. Otherwise it's unclear of what the issue is.

I'm going to close this issue, please re-open a new one following the issue template linked above. Thanks! 😄

**Closed by NickTomlin** 2016-04-12 17:50 UTC
