### ISSUE TITLE
Installing protractor hangs every one in three times.

### ISSUE THREAD

**Issue by q4w56** [angular/protractor#2782] opened 2015-12-14 07:32 UTC
I use 
`nvm use 4.2.3`
`npm install protractor -dd`
Sometimes installations hangs. I found there is 3 cases. Success, hang on installOne, and hang on unlock.
* Success: 
the installation completed smoothly and under 1 minute.
* Hang on unlock: <br>
`npm verb unlock done using /home/jchn/.npm/_locks/selenium-webdriver-552a20708a2c24b7.lock for /home/jchn/333/node_modules/protractor/node_modules/selenium-webdriver`<br>
It hanged for 15 mins! Installing selenium-webdriver alone doesn't has this problem.
* Hang on installOne: <br>
`npm verb installOne of protractor to /home/jchn/333 not in flight; installing`<br>
In this case it hanged for about 30 secs and went smoothly and completed.

At first I thought the cases appears randomly, but found that the cases repeated in this order. It repeats with a period of 3. I means I install for 15 times, and It succeed, hang, hang, succeed, hang, hang... etc. 

I am new to the node. The box is Ubuntu 14.04. Node version is 4.2.3.

**Comment by juliemr** [comment] 2016-01-14 01:55
I strongly suspect this is an issue with your particular computer. Angular uses npm to install Protractor on continuous integration several times a day and it's never an issue. 

There's a monster issue which looks similar to this problem at https://github.com/npm/npm/issues/7862. Can you check that out and see if any solutions there work for you?

Closing because the problem is not with Protractor specifically.

**Closed by juliemr** 2016-01-14 01:55 UTC
Labels: status: needs investigation
