### ISSUE TITLE
Timeout after $location.url call

### ISSUE THREAD

**Issue by kennethlynne** [angular/protractor#2309] opened 2015-07-07 09:51 UTC
I have an issue where when I call `$location.url('/some/thing')` it breaks the tests.

Everything looks good in the browser, but the tests never make it past this test.

I have reduced it to this single it statement:
```js
it('should redirect the user to the default space', function () {
      page.usernameInputEl.sendKeys(page.mockUser.email);
      page.passwordInputEl.sendKeys(page.mockUser.password);
      page.loginButtonEl.click(); 
      //The page is correctly redirected
      //Test times out
      expect(browser.getLocationAbsUrl())
        .toBe('/spaces/1');
    });
```
Implementation
```js
      User
        .login(credentials)
        .then(function(){ //This resolves in about 300 - 500 ms
           $location.url('/spaces/1');
        });
``` 
```bash
Started
A Jasmine spec timed out. Resetting the WebDriver Control Flow.
F

Failures:
1) The login state with correct password should redirect the user to the default space
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
```

```js
console.log(jasmine.DEFAULT_TIMEOUT_INTERVAL);//  10000
```

**Comment by donaldpipowitch** [comment] 2015-07-10 11:31
Is this related to https://github.com/angular/protractor/issues/1797?

I have a similar problem. It seems the tests work correctly in my browser, but all I get is 

````
A Jasmine spec timed out. Resetting the WebDriver Control Flow.
F

Failures:
1) foo...
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at [object Object]._onTimeout (/Users/foo/Workspace/ws/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1812:23)
````

I don't know, if it happens because of `$location.url` in my code, too. Maybe hidden in `ui-router`...

**Comment by kennethlynne** [comment] 2015-07-10 11:57
I am also using ui-router btw

**Comment by Krun** [comment] 2016-03-01 15:12
I am having the exact same issue. When my angular app modifies the location, I get a timeout.

If I increase Jasmine's timeout I get a synchronization timeout:

```
1) Home page view lets you lookup a CID
  Message:
    Failed: Timed out waiting for Protractor to synchronize with the page after 90 seconds. Please see https://github.com/angular/protractor/blob/master/docs/faq.md. The following tasks were pending:
    - $timeout: function o(){var e=n&&n.$$destroyed,t=e?[]:r.queue,o=e?null:r.digest;r.queue=[],r.timeout=null,r.digest=!1,t.forEach(function(e){e()}),o&&d.$digest()}
  Stack:
    Error: Failed: Timed out waiting for Protractor to synchronize with the page after 90 seconds. Please see https://github.com/angular/protractor/blob/master/docs/faq.md. The following tasks were pending:
    - $timeout: function o(){var e=n&&n.$$destroyed,t=e?[]:r.queue,o=e?null:r.digest;r.queue=[],r.timeout=null,r.digest=!1,t.forEach(function(e){e()}),o&&d.$digest()}
```

I don't use the $timeout service at all (don't use $interval either) unless angular/angular material is calling it internally

**Comment by solshark** [comment] 2016-03-09 18:37
Same here

**Comment by megawebmaster** [comment] 2016-07-13 13:01
Any progress on that? I've hit this issue today when I was writing some tests that checked whether the page correctly changes depending on the action.

I'm using ui-router.

**Comment by punithj** [comment] 2016-08-12 05:11
I am experiencing jasmine spec time out issue since a long back while I run multiple specs on IE 11 browser. Also, once the spec has jasmine spec time out then most of the specs that follows it have similar jasmine spec timed out issue. I am struggling to fix this since a long back but no luck.

I tried many things to solve it as below but issue still exists:

1. Increased maximumSpecCallbackDepth  value to 2000
2. Removed BeforeEach fucntion from all spec files and moved that code to it block
3. Used all local variables declared in it block
4. Used Jasmine instead of Jasmine 2 in conf file
5. Using only one it block per spec file

I also upgraded to protractor 3.3.0 but the issue persists. When I run the single spec file with one it  block the spec runs fine but with too many specs (tried with more than 10, 20, 30, 100 specs together), it is giving these errors. and for every run, it is behaving random results.

I googled this and tried many solutions. 

My every spec first logs into the app and then carries out the operations as required. I figured out that most of my spec is giving this error when it navigates to the required page using browser.get()....It logs in to the app correctly but it fails on next browser.get() mainly.

I am not sure that this issue is related with this defect but anyhow I am commenting here just to get some stuff that can help me.

**Comment by punithj** [comment] 2016-08-16 05:54
any updates?

**Comment by mgiambalvo** [comment] 2016-10-19 20:46
@punithj Please open a new issue for your problem (timeouts using multiple specs in IE 11). Also, it would be helpful if you could see if you get the same problem in other browsers.

**Comment by mgiambalvo** [comment] 2016-10-19 22:36
This issue has kind of turned into a grab bag for unrelated timeout problems. The original timeout problem was probably caused by the issue of Protractor needing to bootstrap after a page load. Navigating using $location.url will cause a page reload, thus breaking your test. If you need to change the url in your test, either use $location.search or turn on html5mode so that your url changes don't refresh the page.

This is covered by #3374, so I'm going to close this issue as a duplicate.

**Closed by mgiambalvo** 2016-10-19 22:36 UTC
Labels: status: needs investigation
