### ISSUE TITLE
Chrome opened by protractor add a postfix "/NG_DEFER_BOOTSTRAP!" to the address bar  in a specific angular page

### ISSUE THREAD

**Issue by mike123vn** [angular/protractor#4283] opened 2017-05-12 16:03 UTC
Chrome opened by protractor adds a postfix "/NG_DEFER_BOOTSTRAP!" to the address bar such as example.com/invite/NG_DEFER_BOOTSTRAP! in a specific angular page. However, if I open chrome normally, chrome do not behave like that.
The issue is that it make my test failed because  the address  http://example.com/invite/NG_DEFER_BOOTSTRAP! is an invalid address.

- Node Version: 6.9.1
- Protractor Version: 5.1.1
- Angular Version: 2
- Browser(s): Chrome
- Operating System and Version Windows 10 & MAC10.12.14
- Your protractor configuration file: Attached
- Output from running the test:404 Error
- Steps to reproduce the bug:
Create a simple test case, just open a new chrome browser by protractor.
Close protractor and take control browser from it.
Using this browser to log in and click to create an item.
**Get "No item cat found" and Chrome add a postfix "/NG_DEFER_BOOTSTRAP!" to the address bar.
Check error code in dev tools is 404**
Delete a postfix "/NG_DEFER_BOOTSTRAP!" in the address bar, get create item input form as normal.
**Open a new browser manually, still follow above steps, chrome does not add any postfix after clicking to create an item**
- The URL you are running your tests against (if relevant): N/A because this is my client website

Note: I take control of protractor because, in a full test case, chrome under protractor control still get this trouble when it did above steps.

[config.txt](https://github.com/angular/protractor/files/998340/config.txt)

**Comment by NickTomlin** [comment] 2017-05-12 18:52
Hi there,

Please follow the [Issue Template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) when opening new issues. Otherwise it's unclear what the issue is and how we can actually help.

Please edit your issue to follow the issue template linked above. I'll close this in a day if those edits haven't been made. Thanks! 😄

**Comment by mike123vn** [comment] 2017-05-13 04:30
Thank Nick,
I update my post.
Sorry, i cannot tell the address website. This is my client product. Thanks

**Comment by NickTomlin** [comment] 2017-05-13 13:33
Interesting; the actual URL shouldn't be changing here; the only thing we write `NG_DEFER_BOOTSTRAP` to is `window.name`. Can you provide a small example repo that reproduces this problem?

**Comment by mike123vn** [comment] 2017-05-13 15:47
Hi Nick,

Could you check my email in your gmail mailbox (I get it from your personal website).

**Comment by NickTomlin** [comment] 2017-05-13 16:12
I'm sorry but I don't have the time to log into your application and debug it for you. I'd suggest asking a question on [StackOverflow](http://stackoverflow.com/questions/ask?tags=protractor) that provides a small, reproducible example, in an open source repository, that others can run. Otherwise it is going to be difficult to figure out what is actually going on here. My guess is that there's a JS error during the initialization step for Protractor.

I'm going to go ahead and close this issue. 

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!

**Closed by NickTomlin** 2017-05-13 16:12 UTC

**Comment by mike123vn** [comment] 2017-05-13 16:27
Thank you. Because this is my client website, not my own website, I cannot have the source code to make a small repo as your request.
Anyway, I will as their developer to check their app.  Thank you so much.
