### ISSUE TITLE
when browser.wait() fails to find element used inside setInterval() it returns 199 unknown exit code

### ISSUE THREAD

**Issue by pearljamik** [angular/protractor#3654] opened 2016-10-24 10:25 UTC
When you have sth like:

```
let counter = 0;
setInterval(() => {

browser.wait(protractor.ExpectedConditions.presenseOf(element), 5000).then(() => {counter++;}
);
if (counter === 5) {done()}

}, 10000);
```

Bug report
When the browser.wait wont find element on the page, the test fails with result 199, and runner does not mark it as failed, which results in i.e. a plugin that generates reports not able to generate a report (because it is not marked as failed explicit).
---

- Node Version: ``
- Protractor Version: `4.0.3`
- Angular Version: `2 RC4`
- Browser(s): `chrome`
- Operating System and Version `windows 10 x64`
- Your protractor configuration file
- A relevant example test
- Output from running the test
- Steps to reproduce the bug
- The URL you are running your tests against (if relevant)

Feature Request
---

- Reasons for adopting new feature
- Is this a breaking change? (How will this affect existing functionality)

**Comment by juliemr** [comment] 2016-10-24 19:10
Why are you trying to call `browser.wait` inside a `setInterval`? This is very much against the intended use, which is in a test script. It looks like you're trying to manage the `done` function yourself, but suspect this isn't working properly. 

Because you have not listed a full test for us to reproduce or removed unnecessary information from the issue template, I'm closing this issue. Please open a new issue with a complete reproducible case if you still feel there is a problem.

**Closed by juliemr** 2016-10-24 19:10 UTC
