### ISSUE TITLE
chaining element() is not working with xpath (at least)

### ISSUE THREAD

**Issue by KWodarczyk** [angular/protractor#3887] opened 2016-12-28 14:16 UTC
//HTML

```html
                                      <div class="row">
                                        <div class="col-sm-6 border-right">
                                            <div class="description-block">
                                                <h5 class="description-header ng-binding">1</h5>
                                                <span class="description-text">Successful additions</span>
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="description-block">
                                                <h5 class="description-header ng-binding">0</h5>
                                                <span class="description-text">Failed attempts</span>
                                            </div>
                                        </div>
                                    </div>

```
//Protractor code

```js
function GetSummaryCounts(){

   

        var parentXpath = '//span[contains(text(),"Successful additions")]/..';
        var parentDiv = element(by.xpath(parentXpath));

        var h5XPath = '/h5[@class="description-header ng-binding"]';
        
        //var h5Element = parentDiv.element(by.xpath(h5XPath)); // does not work !!!
        
        var h5Element = element(by.xpath(parentXpath+h5XPath)); // does work

        var EC = protractor.ExpectedConditions;
        browser.wait(EC.presenceOf(h5Element), 5000);
        return h5Element.getText();

    };
```

**Comment by sjelin** [comment] 2016-12-28 19:42
What error message do you get?

**Comment by KWodarczyk** [comment] 2016-12-29 00:01
Well get actually a java exception something to with casting hashmap to string I will paste it tomorrow once im back in the office

**Comment by juliemr** [comment] 2016-12-29 00:20
Chaining does not work with xpath, this is just how xpath selectors work in webdriver. This is documented at http://www.protractortest.org/#/api?view=webdriver.By.xpath. Closing this as working as intended.

**Closed by juliemr** 2016-12-29 00:20 UTC
Labels: status: needs more info

**Comment by KWodarczyk** [comment] 2016-12-29 06:47
Hi thanks for for point this out, you are right this is documented but to be honest, that documentation would be the last thing I would be looking at, this is because it's a special case and if this works with other elements selectors why would anyone think it a different case with xpath ?. 
Im jus't saying it's not intuitive at all. If that was me I would probably change the API on protractor level and fix this under the hood. Otherwise this is extending a webdriver library together with their issues.  This should probably be fixed in the webdriver as well.
