### ISSUE TITLE
webDriverProxy does not work

### ISSUE THREAD

**Issue by pearljamik** [angular/protractor#3139] opened 2016-04-19 21:10 UTC
Although the webDriverProxy: 'http://localhost:3128' is set, the proxy is not used.

**Comment by sjelin** [comment] 2016-04-22 21:40
Could you provide more information?  Other people have used the proxy

**Comment by NickTomlin** [comment] 2016-04-25 17:26
@pearljamik i'm going to go ahead and close this issue since there hasn't been any movement on it. If this is still a problem, please open a new issue using the [Issue Template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) and provide more details on how we can reproduce this. 

Thanks! 😄

**Closed by NickTomlin** 2016-04-25 17:26 UTC
