### ISSUE TITLE
ExpectedCondition methods should support element.all().first()

### ISSUE THREAD

**Issue by marklagendijk** [angular/protractor#2314] opened 2015-07-08 14:59 UTC
The `ExpectedConditions` methods are very nice when testing stuff outside of Angular. However, there is a limitation. Currently it is impossible to wait for the *first* element matching a certain selector.

I would expect the following to work:
``` javascript
function waitForElementByLocator(locator, timeout){
    var elem = element.all(locator).first();
    var isClickable = protractor.ExpectedConditions.elementToBeClickable(elem);
    browser.wait(isClickable, timeout, 'Waiting for element  \'' + locator + '\' timed out');
    return elem;
}

// There are multiple .myElement elements, we want to click the first one
waitForElementByLocator(by.css('.myElement')).click();
```
However, this fails if `.myElement` is not present at the moment the wait is started. We get an error:
```
Failed: Index out of bound. Trying to access element at index: 0, but there are only 0 elements that match locator LOCATOR
```

It does work when we use `element(locator)` instead of `element.all(locator).first()`:
``` javascript
function waitForElementByLocator(locator, timeout){
    var elem = element(locator);
    var isClickable = protractor.ExpectedConditions.elementToBeClickable(elem);
    browser.wait(isClickable, timeout, 'Waiting for element  \'' + locator + '\' timed out');
    return elem;
}

// There are multiple .myElement elements, we want to click the first one
waitForElementByLocator(by.css('.myElement')).click();
```
However, when we do this, we get warnings about  the fact that there are multiple matches: 
```
WARNING - more than one element found for locator LOCATOR - the first result will be used.
```

I see two possible solutions for this:
1. Prevent / swallow the `Index out of bound` exception in the methods.
2. Support passing an ArrayElementFinder to the methods. E.g: `protractor.ExpectedConditions.elementToBeClickable(element.all(by.css('.myElement')))`

**Comment by marklagendijk** [comment] 2015-07-09 09:26
If you are encountering the same issue you use the following terribly ugly and hacky workaround:
``` javascript
var _ = require('lodash');
console.log = _.wrap(console.log, function(log, message){
    if(!_.startsWith(message, 'WARNING - more than one element found for locator ')){
        log.apply(console, _.slice(arguments, 1));
    }
});
```

**Comment by mradionov** [comment] 2015-07-20 10:17
I was able to workaround this by adding custom expected condition, which resolves when parent element gets children, and then chaining it using `EC.and` with the expected condition I wanted to use for nth element :

```js
function haveChildren(parent) {
    return function () {
        return parent.count().then(function (count) {
            return count > 0;
        });
    };
}

var container = $$('.container');

browser.wait( EC.and( haveChildren(container), EC.presenceOf(container.first()) ), 1000);

expect(container.first().isPresent()).toBe(true);

**Comment by juliemr** [comment] 2016-07-14 18:20
Closing in favor of https://github.com/angular/protractor/issues/2917, as these have the same root cause.

**Closed by juliemr** 2016-07-14 18:20 UTC
Labels: type: feature request
