### ISSUE TITLE
Failed: Timed out waiting for Protractor to synchronize with the page after X seconds.

### ISSUE THREAD

**Issue by pebels** [angular/protractor#3070] opened 2016-03-29 09:44 UTC
This fail only happens when tests use chrome. In Firefox is ok and no problem happens.

The configuration I am using is the next:

Node version 4.4.1 LTS.
Npm 2.14.20
Protractor 3.2.2
Selenium 2.52.0
Chromedriver 2.21
Jasmine Spec Reporter: 2.4.0

Chrome
Versión 49.0.2623.110 (64-bit)

Firefox
Versión: 44.0.2

I login into my website, and go to a private url, in this url I click a button that open a modal. 
In this modal I write with sendkeys. In firefox the characters are written, but Chrome keeps in the field forever without writting, and for that happens "Timed out" (I have test with 11000 and 22000 miliseconds). It is a barbarity!! I have coleages that with the same configuration Chrome works well. I dont understand what may be happen and how to fix it. If you need more information, I would be pleasent to send it.

I have recorder my screen to show what is happening when I use Chrome. The video file is only 3MB.
https://www.dropbox.com/s/lkmgt78ffdgfwuc/TimeOut-Chrome-Protractor.mov?dl=0

Thank you so much.

**Comment by NickTomlin** [comment] 2016-03-29 16:49
Could I get you to provide a smaller more isolated case? It's hard to debug this without more code/setup info because the failure could be happening at a few different layers. 

An repo with a simple example and protractor config would be extremely helpful. Or you if you can reproduce using the [protractor example](https://github.com/angular/protractor/tree/master/example) as a basis.

**Comment by pebels** [comment] 2016-03-30 09:48
Ok, you are right Nickomlin. In my config.js I have this:
I am only executing suite called applications. This is a weird thing because it only happens in my computer, and in the coleage pcs it is working. I dont know what can be happening. I have a Mac OS X The Captain.

exports.config = {
  framework: 'jasmine',
  seleniumAddress: 'http://localhost:4444/wd/hub',
  multiCapabilities: [
    {browserName: 'chrome'}
  ],
  suites: {
    applications: '**/pages/clients/applications/*.spec.js',
    developers: '**/pages/clients/developers/*.spec.js',
    usePlans: '**/pages/clients/use-plans/*.spec.js',
  },
  baseUrl: 'https://mydomain.com', //this is not real
  allScriptsTimeout: 11000,
  getPageTimeout: 10000,
  jasmineNodeOpts: {
    isVerbose: false,
    showColors: true,
    includeStackTrace: true,
    defaultTimeoutInterval: 40000
  },
  params: {
    login: {
      user: 'notreal',
      password: 'notreal'
    },
    domain_name: 'https://mydomain.com' //this is not real (is the same that baseUrl)
  }, noGlobals: false,
  onPrepare: function () {
    // Set Window size
    browser.manage().window().setSize(1920, 1080);

    // Maximize Window
    browser.driver.manage().window().maximize();

    // Jasmine Spec Reporter
    var SpecReporter = require('jasmine-spec-reporter');
    jasmine.getEnv().addReporter(new SpecReporter({
      displayFailuresSummary: true,
      displayFailedSpec: true,
      displaySuiteNumber: true,
      displaySpecDuration: true
    }));

    // Disable animations so e2e tests run more quickly
    var disableNgAnimate = function () {
      angular.module('disableNgAnimate', []).run(['$animate', function ($animate) {
        $animate.enabled(false);
      }]);
    };
    browser.addMockModule('disableNgAnimate', disableNgAnimate);

    // Save browser name inside browser.name
    browser.getCapabilities().then(function (value) {
      browser.name = value.get('browserName');
    });
  }
};

**Comment by pebels** [comment] 2016-03-30 09:56
The fact is I have download docker and I have download an image from
https://github.com/elgalu/docker-selenium
And I have changed config.js for running with docker and everything also in chrome go right.
I dont understand why from my local its happening the error, and if I execute against that docker image all is right and it works.

**Comment by juliemr** [comment] 2016-04-04 18:27
Unfortunately, there's not much we can do on this forum to debug issues that we can't reproduce. I'd suggest the usual reinstalling chrome, node, etc and see if that helps.

Closing this as non-actionable.

**Closed by juliemr** 2016-04-04 18:27 UTC
Labels: status: needs more info
