### ISSUE TITLE
Upgrade from 1.8.0 to 2.1.0 and getCurrentUrl stops working

### ISSUE THREAD

**Issue by ryanmc2033** [angular/protractor#2278] opened 2015-06-29 17:26 UTC
Hey all, thanks for the great framework. I am trying to upgrade protractor from 1.8.0 to 2.1.0, but it seems like all my getCurrentUrl calls stop working (the promise never resolves). I'm sure I am doing something wrong. Here is my code

```
navigate: {
        value: function() {
            return browser.getCurrentUrl().then(
                function(url) {
                    console.log('here3');
                    if(!utils.endsWith(url, '/admin/settings'))
                    {
                        utils.openLeftNavBar();
                        return utils.settingsBtn.click();
                    }
                }
            );
        }
    },
```

I put the console.log in for debug, but I never get the 'here3'. Any suggestions would be appreciated.

**Comment by sjelin** [comment] 2015-06-29 18:25
You're sure `navigate.value()` is being executed?

**Comment by ryanmc2033** [comment] 2015-06-29 18:27
if I add another console.log like this

```
navigate: {
        value: function() {
            console.log('here2');
            return browser.getCurrentUrl().then(
                function(url) {
                    console.log('here3');
                    if(!utils.endsWith(url, '/admin/settings'))
                    {
                        utils.openLeftNavBar();
                        return utils.settingsBtn.click();
                    }
                }
            );
        }
    },
```

I see 'here2' printed out on the console.

**Comment by bvasilchik** [comment] 2015-06-29 19:24
would something like this work?

```javascript
navigate: {
  value: function () {
      browser.getCurrentUrl().then(function (currentUrl) {
      browser.wait(function () {
         return browser.getCurrentUrl().then(function (newUrl) {
            var test = newUrl;
            if( test.indexOf('/admin/settings') >= 0){
              // Found word
              return false;
            }
            else{
              utils.openLeftNavBar();
              return utils.settingsBtn.click();
            }
         });
      }, 5000 , "failed to wait for url not to contain /admin/settings");
    });
  }
},

```

**Comment by ryanmc2033** [comment] 2015-06-29 19:45
nope, it never makes it past the first getCurrentUrl.

in the console I am getting an error, maybe that will help

```
c:\projects\si\presentations\site\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1877
      var result = fn();
                   ^
TypeError: undefined is not a function
```

**Comment by bvasilchik** [comment] 2015-06-29 20:24
are you able to use the title of the of the webpage rather than the url? I sometimes do something like this.

you can also use 
**protractor.until.titleContains('text')**
**protractor.until.titleMatches(/text/)** <<< regex
```javascript
 browser.wait(protractor.until.titleIs("Some Title"), 5000, "✗ Failed to wait for Some title page to load").then(function(){
  utils.openLeftNavBar();
  return utils.settingsBtn.click();
});
```

**Comment by ryanmc2033** [comment] 2015-06-29 21:12
Is there a reason that getCurrentUrl does not work?

**Comment by juliemr** [comment] 2015-06-29 22:00
What's the context in which you're calling `navigate.value`? Can you share a reproducible case?

**Comment by ryanmc2033** [comment] 2015-06-29 22:31
I'm not sure how to produce a reproducible case since this is testing against an internal website, but I will see if I can get it to break using a different website.

Here is the test case that uses navigate

```
it('Navigates to the settings page and retrieves the company name', function (done) {
        settings.navigate().then(
            function () {
                settings.verifyPage();
                browser.waitForAngular();
                settings.companyName.then(
                    function (company) {
                        utils.getFieldText(company).then(
                            function (name) {
                                company_name = name;
                                console.log('Company name: ' + company_name);
                                done();
                            }
                        );
                    }
                );
            }
        );
    });
```

**Comment by juliemr** [comment] 2015-06-29 22:41
Can you try it out of the context of everything else? Just:

```
it('navigates', function() {
  settings.navigate();
});
```
And see if that hangs?

**Comment by ryanmc2033** [comment] 2015-06-30 14:45
it does not hang, it just fails the test "navigates - fail" and gives me an error like before

```
c:\projects\salesindicator\presentations\site\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1877
      var result = fn();
```

That being said. I played around with it some more and it looks like it is not waiting for angular to finish before failing the tests. In the console I will see a bunch of failures, but in the browser the pages are way behind and still loading.

Did something change in v2 that would cause protractor to not wait until angular has loaded?

**Comment by juliemr** [comment] 2015-06-30 17:17
No, there should not be an issue with waiting for angular to finish. Full changelog is at https://github.com/angular/protractor/blob/master/CHANGELOG.md

Please let us know if you can create a reproducible error.

**Comment by juliemr** [comment] 2015-06-30 17:17
I'm closing this particular issue since it doesn't seem like the problem is with `getCurrentUrl`. Please open a new issue if you have a reproducible problem. Thanks!

**Closed by juliemr** 2015-06-30 17:17 UTC
Labels: needs: more info, type: question
