### ISSUE TITLE
Protractor failing to drag and drop

### ISSUE THREAD

**Issue by Risto-Stevcev** [angular/protractor#1875] opened 2015-02-28 11:59 UTC
I can't get drag and drop to work. I'm currently trying it on a modified version of the simple w3schools [HTML5 Drag and Drop](http://www.w3schools.com/HTML/tryit.asp?filename=tryhtml5_draganddrop) example:

```html
<!DOCTYPE HTML>
<html ng-app="app">
<head>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js"></script>
<script>
var app = angular.module('app', [])
</script>
<style>
#div1 {width:350px;height:70px;padding:10px;border:1px solid #aaaaaa;}
</style>
<script>
function allowDrop(ev) {
    ev.preventDefault();
}

function drag(ev) {
    ev.dataTransfer.setData("text", ev.target.id);
}

function drop(ev) {
    ev.preventDefault();
    var data = ev.dataTransfer.getData("text");
    ev.target.appendChild(document.getElementById(data));
}
</script>
</head>
<body>

<p>Drag the W3Schools image into the rectangle:</p>

<div id="div1" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
<br>
<img id="drag1" src="img_logo.gif" draggable="true" ondragstart="drag(event)" width="336" height="69">

</body>
</html>
```

And with this spec, it seems to be failing no matter what I try:
```js
describe('it', function() {
  beforeEach(function() {
    browser.get('http://localhost:8080/dragdrop.html')
  })

  it('should', function() {
    var div = element(by.id('div1'))
    var drag = element(by.id('drag1'))

    expect(div.isPresent()).toBe(true)
    expect(drag.isPresent()).toBe(true)
    expect(div.getTagName()).toBe('div')
    expect(drag.getTagName()).toBe('img')

    expect(div.getInnerHtml()).toBe('')

    /*
    browser.actions()
           .mouseMove(drag.getWebElement(), {x: 0, y: 0})
           .mouseDown()
           .mouseMove(drag.getWebElement(), {x: 5, y: 5})
           .mouseMove(div.getWebElement())
           .mouseUp()
           .perform()
    */

    //browser.actions().dragAndDrop(drag, {x: 0, y: 50}).perform()
    
    /*
    div.getLocation().then(function(divLocation) {
      browser.actions().dragAndDrop(drag, divLocation).perform()
    })
    */

    expect(div.getInnerHtml()).not.toBe('')
  })
})
```

I can confirm that the drag and drop test, [fb46ec9](https://github.com/angular/protractor/commit/fb46ec9bcd568510248831f11d43d0e2398cc606), works. But it's testing a slider and not this particular use case, which takes an object and places it in the drop zone. What am I doing wrong?

I've tried it on Firefox 34 and Chromium 40.

**Comment by juliemr** [comment] 2015-03-01 02:29
Closing as a dupe of https://github.com/angular/protractor/issues/583 - see the related issue on selenium issue tracker there.

**Closed by juliemr** 2015-03-01 02:29 UTC

**Comment by LibuMathew** [comment] 2017-03-16 16:16
**Resolved**
I used the HTML Drag and Drop Simulator from github https://github.com/PloughingAByteField/html-dnd 
 
Working code:
```
 var dragAndDrop = require('html-dnd').code;
 
 describe('Protractor Drag and Drop', function () {
     it('should add one and two', function () {
         browser.get('http://127.0.0.1:7000/#/editor');
 
         var draggable = element(by.id('Input'));
         var droppable = element(by.id('___content'));
         var offsetX = 0;
         var offsetY = 0;
 
         browser.executeScript(dragAndDrop, draggable, droppable, offsetX, offsetY);
         browser.sleep(3000);
     });
 });

```
