### ISSUE TITLE
Protractor doesn't clean up after uncaught exceptions

### ISSUE THREAD

**Issue by mzgol** [angular/protractor#1772] opened 2015-02-02 00:17 UTC
I've just encountered a similar issue as one reported earlier (#1072): Protractor sometimes doesn't clean up after itself; the chromedriver process and the Chrome browser are not killed if `browser.driver.wait` times out. The relevant function:
```js
function waitForElementBySelector(selector) {
    browser.driver.wait(function () {
        return browser.driver.findElements(by.css(selector)).then(function (elementsArray) {
            return elementsArray.length === 1;
        });
    }, 30000);
}
```
Protractor 1.6.1 (latest), Node 0.10 & io.js 1.0.4.

The error message:
```
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
Selenium standalone server started at http://192.168.1.45:64592/wd/hub

/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654
      var result = fn();
                   ^
Error: Wait timed out after 30026ms
    at /Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1425:29
    at /Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1582:15
    at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
    at notify (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:465:12)
    at [object Object].then (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:522:7)
    at Object.webdriver.promise.asap (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:767:11)
    at newFrame.onComplete (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1670:25)
    at [object Object].webdriver.promise.Frame_.notify_ (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1914:5)
    at [object Object]._onTimeout (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1901:11)
    at Timer.listOnTimeout (timers.js:90:15)
==== async task ====
    at [object Object].webdriver.promise.ControlFlow.wait (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1410:15)
    at [object Object].webdriver.WebDriver.wait (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:646:21)
    at waitForFunction (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/test/e2e/lib/helpers.js:22:20)
    at waitForElementBySelector (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/test/e2e/lib/helpers.js:36:5)
    at Object.helpers.user.registerAccount (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/test/e2e/lib/helpers.js:109:13)
    at onPrepare (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/protractor.conf.js:47:22)
    at /Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/protractor/lib/util.js:54:41
    at Function.promise (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/protractor/node_modules/q/q.js:650:9)
    at Object.exports.runFilenameOrFn_ (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/protractor/lib/util.js:44:12)
[launcher] Process exited with error code 1
```

**Comment by juliemr** [comment] 2015-03-19 21:50
I've just tried this and I'm unable to reproduce. The timeout occurs as you say, but the instance of chrome is cleaned up and my output ends with

```
1 spec, 1 failure
Finished in 4.058 seconds
Shutting down selenium standalone server.
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #1 failed 1 test(s)
[launcher] overall: 1 failed spec(s)
[launcher] Process exited with error code 1
```

Can you still reproduce this? Can you share some code that makes it happen?

**Comment by juliemr** [comment] 2015-03-19 21:52
Ah, I think I've figured out what you're doing. Are you doing this wait on `onPrepare`? I can reproduce if I try to do it there. I'm renaming the issue to clarify this.

**Comment by mzgol** [comment] 2015-03-19 22:29
I'll need to check but I think I use this in onPrepare as well so your observation is most likely true.

**Comment by juliemr** [comment] 2015-03-19 23:11
This is a quick way to reproduce the same behavior:

```js
  onPrepare: function() {
    protractor.promise.delayed(30).then(function() {
      throw new Error('my error from onPrepare');
    });
  }
```

**Comment by juliemr** [comment] 2015-03-19 23:57
The issue here is that this is causing an uncaught exception. If we return a promise which errors, everything is cleaned up as expected. For the record, the same sort of issue happens with uncaught errors from tests:

```js
  it('should clean up after itself', function() {
    protractor.promise.delayed(30).then(function() {
      throw new Error('my async error from the test');
    });
  });
```

So the question is, should we start catching uncaught exceptions and forcing cleanup in those cases? We should look into using node domains to do this.

**Comment by mzgol** [comment] 2015-03-23 13:53
> We should look into using node domains to do this.

See https://iojs.org/api/domain.html. Domains are deprecated, I wouldn't dive into them with new code...

**Comment by juliemr** [comment] 2015-03-23 17:46
@mzgol thanks for the heads up. Do you have any idea what the non-deprecated path is?

**Comment by mzgol** [comment] 2015-03-23 17:49
From the site:
> This module is pending deprecation. Once a replacement API has been finalized, this module will be fully deprecated

which means that for now the safest options seems to be just try-catching everything that might throw errors...

**Comment by juliemr** [comment] 2015-03-23 17:51
In that case, I think we can close this issue for now. Since the thing that might throw an error is user-written code in `onPrepare`, there's nothing that Protractor can add here.

**Closed by juliemr** 2015-03-23 17:51 UTC
Labels: type: feature request
