### ISSUE TITLE
Firefox 50.1.0 not working

### ISSUE THREAD

**Issue by stanbe** [angular/protractor#3823] opened 2016-12-14 14:11 UTC
Bug report
---

- Node Version: 6.7.0
- Protractor Version: 4.0.10
- Angular Version: 2.1.0
- Browser(s): Firefox 50.1.0
- Operating System and Version Win8.1 Enterprise
- Your protractor configuration file

```
exports.config = {
    capabilities: {
        'browserName': 'firefox'
    },
    specs: ['**/*.e2e.spec.js'],
    useAllAngular2AppRoots: true,
    baseUrl: 'http://localhost:64065/',
    directConnect : true
};
```
- A relevant example test

```
describe('Expense overview list', function () {

    it('should should have Anakin Skywalker as first entry', function () {
        browser.get('/home');
        expect(browser.getTitle()).toEqual('Angular');

        browser.get('/overview');

        expect(element(by.id('00000000-0000-0000-0000-000000000001')).getText()).toEqual('ANAKIN SKYWALKER');
    });
});
```
- Output from running the test
```
[15:08:27] I/direct - Using FirefoxDriver directly...
[15:08:27] I/launcher - Running 1 instances of WebDriver
[15:09:12] E/launcher - Timed out waiting for the WebDriver server at http://127.0.0.1:60626/hub
[15:09:12] E/launcher - Error: Timed out waiting for the WebDriver server at http://127.0.0.1:60626/hub
    at Error (native)
    at onError (C:\Users\john\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\http\util.js:87:11)
    at ManagedPromise.invokeCallback_ (C:\Users\john\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1379:14)
    at TaskQueue.execute_ (C:\Users\john\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2913:14)
    at TaskQueue.executeNext_ (C:\Users\john\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2896:21)
    at asyncRun (C:\Users\john\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2775:27)
    at C:\Users\john\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:639:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at Function.createSession (C:\Users\john\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:329:24)
    at Driver (C:\Users\john\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\firefox\index.js:386:38)
    at Direct.getNewDriver (C:\Users\john\AppData\Roaming\npm\node_modules\protractor\built\driverProviders\direct.js:75:26)
    at Runner.createBrowser (C:\Users\john\AppData\Roaming\npm\node_modules\protractor\built\runner.js:198:43)
    at C:\Users\john\AppData\Roaming\npm\node_modules\protractor\built\runner.js:285:30
    at _fulfilled (C:\Users\john\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\john\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\john\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:796:13)
    at C:\Users\john\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:556:49
    at runSingle (C:\Users\john\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:137:13)
[15:09:12] E/launcher - Process exited with error code 199
```

- Steps to reproduce the bug
just run protractor protractor.conf.js
- The URL you are running your tests against (if relevant)
see protractor.conf.js

Firefox is starting but nothing happens, just an empty screen.

**Comment by Xotabu4** [comment] 2016-12-14 18:34
+ 1

**Comment by wh33ler** [comment] 2016-12-16 06:13
+1

**Comment by wlsf82** [comment] 2016-12-18 12:45
I received emails of 3 different friends facing exactly the same issue, but I'm not able to reproduce. :/

**Comment by BishuSinha** [comment] 2016-12-18 23:27
+1

**Comment by juliemr** [comment] 2016-12-19 19:19
Right, firefox is very confused with the latest versions of selenium server. We're investigating what's compatible with what now, with marionettedriver and geckodriver and various versions of selenium. Stay tuned.

**Comment by juliemr** [comment] 2016-12-19 19:20
See also https://github.com/angular/protractor/issues/3750

**Comment by sjelin** [comment] 2016-12-22 04:28
(assigning to you @mgiambalvo because I didn't assign many over issues to you, and I feel like I need to balance)

**Comment by mgiambalvo** [comment] 2017-01-10 23:30
We will need to update the directConnect provider for Selenium 3.0. However, Firefox is still broken. We can address this once Firefox 51 ships.

**Comment by mgiambalvo** [comment] 2017-01-18 21:59
Note that as of Protractor 5.1, we'll support Firefox 51+ and greater. Older versions of Firefox won't work with directConnect, but may work with selenium server and `marionette: false`. A bug was introduced in Selenium 3.0.0 that breaks the JS Firefox driver (SeleniumHQ/selenium#3115) - it's been fixed, but won't be available until the next release of selenium server (3.0.2 or greater). So to use the latest Firefox, you'll need to use selenium server 3.0.0-beta4 like so:

```
webdriver-manager update
wget http://selenium-release.storage.googleapis.com/3.0-beta4/selenium-server-standalone-3.0.0-beta4.jar -P ./node_modules/webdriver-manager/selenium
webdriver-manager start --versions.standalone 3.0.0-beta4
```

**Comment by sdseenu** [comment] 2017-02-03 05:52
Protractor  test is not running on FireFox 51+ for Windows 8.1 64bit

Browser is open but do not have any action take place getting below error
![03-02-2017 11-21-31](https://cloud.githubusercontent.com/assets/25522319/22581017/07ee8b30-ea03-11e6-8fe4-7a390c2c65dc.png)

**Comment by theandrewlane** [comment] 2017-02-08 21:10
+1

**Comment by sjelin** [comment] 2017-02-08 22:18
+ @seanmay

**Comment by esoyke** [comment] 2017-02-09 15:33
Thanks @mgiambalvo. It was driving me nuts why during the middle of the day, Protractor/Firefox had been working fine then suddenly Firefox wouldn't even go to the URL but instead timed out. Looking at Firefox's update history I discovered it had auto-updated from 50.1.0 to 51.0.1 while I was at lunch!

There were a few extra hoops I personally had to jump through. Some are Mac-specific, but this might help speed up others with the same issues.

1- OSX doesn't have wget installed by default, but it's an easy install
2- The webdriver-manager start failed as it expected the JAR in a different location (/Users/esoyke/.nvm/versions/node/v6.2.2/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.0.0-beta4.jar). I manually moved it there.
3- Ran into another error starting Selenium (Exception in thread "main" java.lang.UnsupportedClassVersionError: org/openqa/grid/selenium/GridLauncherV3 : Unsupported major.minor version 52.0 ). The Mac had Java 7 so I upgraded to 8.
4- Was still getting the same error until I removed the "directConnect: true" from my config.

Back in the saddle!

**Comment by JoshLipps** [comment] 2017-02-15 07:46
For me I also had to modify the original workaround slightly:
```
wget http://selenium-release.storage.googleapis.com/3.0-beta4/selenium-server-standalone-3.0.0-beta4.jar -P ./node_modules/protractor/node_modules/webdriver-manager/selenium
./node_modules/.bin/webdriver-manager start --versions.standalone 3.0.0-beta4
```

**Comment by eKatsarski** [comment] 2017-02-16 08:23
+1

**Comment by joeydaowang** [comment] 2017-02-27 01:14
Does anyone know whether Selenium 3.1.0 works or not?

**Comment by JoshLipps** [comment] 2017-02-27 07:31
For me the release of 3.1.0 does seem to have fixed things. (I no longer have to use the above work around)

**Comment by joeydaowang** [comment] 2017-02-27 20:53
@JoshLipps does 'directConnect: true' work for you?

**Comment by rahulmr** [comment] 2017-03-15 04:35
`directConnect:true` not working for me on Firefox 52.0 32bit and gecko 15.0 while it works with selenium-standalone 3.3.1 but only when I provide below options and start server manually in another git bash shell.
```
-Dwebdriver.gecko.driver=./node_modules/protractor/node_modules/webdriver-manager/selenium/geckodriver-v0.15.0.exe
```
see logs [here][1]

[1]: https://github.com/angular/protractor/issues/886

**Comment by benitogf** [comment] 2017-03-15 06:42
Same issue as @rahulmr here https://travis-ci.org/benitogf/corsarial

**Comment by RaviKlair** [comment] 2017-04-10 22:59
@rahulmr how did you start the server manually with the mentioned option ?

**Comment by rahulmr** [comment] 2017-04-11 02:29
@RaviKlair its a simple one. see below  
`java -jar selenium-standalone-3.3.1,jar -Dwebdriver.gecko.driver=./node_modules/protractor/node_modules/webdriver-manager/selenium/geckodriver-v0.15.0.exe`

**Comment by RaviKlair** [comment] 2017-04-11 16:31
@rahulmr where exactly is your .jar file present ? mine is in the same location as gecko driver.
![image](https://cloud.githubusercontent.com/assets/24551166/24919740/7e0faedc-1e99-11e7-85ef-1859bb18ba30.png)

**Comment by jlin412** [comment] 2017-04-11 16:51
It works with this combination selenium server 3.3.1 and gecko 0.15 and
firefox 52.  There is a bug for firefox less than 52.

**Comment by RaviKlair** [comment] 2017-04-11 17:31
i'm using protractor 5.0.0, firefox 52, angular1 application
![image](https://cloud.githubusercontent.com/assets/24551166/24922107/f8e0ba18-1ea1-11e7-8543-4d3e83b3e591.png)
It's installing selenium-server-standalone-2.53.1.jar

**Comment by rahulmr** [comment] 2017-04-11 19:41
@RaviKlair sorry to confuse you.  Here is the complete command and I am using protractor 5.1.1 here

```
D:\projects\gulp-protractor\example_2>java -Dwebdriver.gecko.driver=".\node_modules\protractor\node_modules\webdriver-manager\selenium\geckodriver-v0.15.0.exe" -jar .\node_modules\protractor\node_modules\webdriver-manager\selenium\selenium-server-standalone-3.3.1.jar
```

**Comment by RaviKlair** [comment] 2017-04-11 19:56
@rahulmr Thanks for the detailed response! I'm able to start the server with the mentioned cmd but when I run a spec, its not grabbing the gecko driver present in selenium folder, rather its trying to find it in PATH.
Any comments ?
![image](https://cloud.githubusercontent.com/assets/24551166/24928130/28d9631e-1eb6-11e7-8210-818f25651f8c.png)

**Comment by jlin412** [comment] 2017-04-11 20:20
Currently, firefox doesn't work with direct connect with gecko driver
0.15.  You need to set --seleniumAddress=

**Comment by rahulmr** [comment] 2017-04-11 20:30
@jlin412 is right . You need to set `seleniumAddress` in `protractor.conf.js` file like below

```
  seleniumAddress: 'http://localhost:4444/wd/hub',
```

**Comment by RaviKlair** [comment] 2017-04-11 20:31
Right! I've added `seleniumAddress: 'http://localhost:4444/wd/hub'` in my conf file.
So, now if I run my test, it opens up firefox but closes it after 1 sec and spits out the following error 
![image](https://cloud.githubusercontent.com/assets/24551166/24929535/255a5b1c-1ebb-11e7-8026-564b452eb71f.png)

Sorry for spamming this thread

**Comment by rahulmr** [comment] 2017-04-11 20:36
@RaviKlair you are right you should stop posting it here. Rather create your own repository and let's play it there. Create issue for yourself. May be you can create travis file. I will try to help you out there. It seems you are overriding some parameters.

**Comment by jlin412** [comment] 2017-04-11 20:37
I see this error if you are using firefox less than 52

**Comment by rahulmr** [comment] 2017-04-11 20:38
@RaviKlair Few checkpoints though.

1. Firefox version (64 bit or 32 bit) 52 or greater
2. gecko version

**Comment by RaviKlair** [comment] 2017-04-11 20:43
@rahulmr @jlin412  Apparently the protractor was not picking up the latest firefox version (52). Now with 52 the tests are running successfully. All it needed was a little nudge.
Thanks to you both!

**Comment by mftaha** [comment] 2017-04-13 17:35
+1

**Comment by heathkit** [comment] 2017-05-01 02:22
See https://github.com/angular/protractor/issues/4253 for the issues with directConnect and Firefox 52 in Protractor 5.1.1

**Closed by heathkit** 2017-05-01 02:22 UTC
Labels: browser: firefox, status: external bug filed

**Comment by pramodh06** [comment] 2017-05-16 12:50
for this issue Firefox 52.0 and Protractor 5.1.1 is helpful
