### ISSUE TITLE
Cannot run element explorer from command line on windows. Keep getting Error: Invalid character code:800A03f6. Setting i have in elelemtexlporer is #!/usr/bin/env node. Please suggest how to set this setting for windows.

### ISSUE THREAD

**Issue by venkatpandiri** [angular/protractor#3593] opened 2016-09-22 16:29 UTC
Hi there!

Cannot run element explorer from command line on windows. Keep getting Error: Invalid character code:800A03f6. Setting i have in elelemtexlporer is #!/usr/bin/env node. Please suggest how to set this setting for windows.

**Comment by NickTomlin** [comment] 2016-09-22 16:51
Hi there,

Please follow the [Issue Template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) when opening new issues. Otherwise it's unclear what the issue is and how we can actually help.

I'm going to close this issue, please re-open a new one following the issue template linked above. Thanks! 😄

**Closed by NickTomlin** 2016-09-22 16:51 UTC

**Comment by venkatpandiri** [comment] 2016-09-22 17:00
Can you please help us with information. I had went to the website and put in the request.

**Comment by NickTomlin** [comment] 2016-09-22 17:22
The issue queue is not for support requests (please read the issue template or the CONTRIBUTING.md)

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by venkatpandiri** [comment] 2016-09-22 17:49
Yes  I was asking on the stacktrace not sure. Where the missing link is

**Comment by venkatpandiri** [comment] 2016-09-22 17:50
Look at the image below
[cid:image001.png@01D214D8.45A35830]

**Comment by NickTomlin** [comment] 2016-09-22 18:44
I think there's a communication breakdown here. Please direct your questions to StackOverflow or Gitter.

I'm going to lock this thread to avoid any more confusion. Thanks! 😄
