### ISSUE TITLE
Element is visible but not clickable

### ISSUE THREAD

**Issue by eolognt** [angular/protractor#2173] opened 2015-05-21 15:03 UTC
```
var EC = protractor.ExpectedConditions;
var button = $('#xyz');
browser.wait(EC.elementToBeClickable(button), 5000);
button.click()
```
Doing `browser.wait(EC.elementToBeClickable(button, 5000);` when waiting for elements to be clickable isn't a safe way to go. `elementToBeClickable` checks if the element is visible and enable, but even if these evaluate true, the element could be 'unclickable'. I have figured out that `button.click()` does a mousemove to the center of the element and then a mousedown and a mouseup and while an element can be visible, its centerpoint could be outside the viewport. I then get this error doing `button.click()`:
> - Failed: unknown error: Element is not clickable at point (150, -25)

I got this for example when waiting for animating elements to be clickable, because they are outside the viewport from the start and when sliding into the viewport and visible, Protractor tries to click on the element. But this can sometime give me that error printed above. Not always, because the timing varies.

**Comment by sjelin** [comment] 2015-05-21 15:27
Duplicate of #2139

**Closed by sjelin** 2015-05-21 15:27 UTC
Labels: duplicate
