### ISSUE TITLE
Failed: e2e tests in CI (Angular 2)

### ISSUE THREAD

**Issue by Shyam-Chen** [angular/protractor#3136] opened 2016-04-18 10:23 UTC
![Local](https://img.shields.io/badge/Local-OK-brightgreen.svg) ![CI](https://img.shields.io/badge/CI-Error-red.svg) ![Angular 1 (CI)](https://img.shields.io/badge/Angular%201%20(CI)-OK-brightgreen.svg)

in Travis CI ([result](https://travis-ci.org/Shyam-Chen/ng2-test-ci/jobs/123857303)):
```bash
Failed: Component returned failure code: 0x804b000a (NS_ERROR_MALFORMED_URI) [nsIDOMLocation.replace]
Failed: Error while waiting for Protractor to sync with the page: "window.getAllAngularTestabilities is not a function"
```

![default](https://cloud.githubusercontent.com/assets/13535256/14601071/96d57b20-0592-11e6-8e91-7055c8e4aece.PNG)

mgechev/angular2-seed#732

**Comment by NickTomlin** [comment] 2016-04-21 19:29
Hi there,

Please follow the [Issue Template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) when opening new issues. Otherwise it's unclear what the issue is and how we can actually help.

I'm going to close this issue, please re-open a new one following the issue template linked above. Thanks! 😄

**Closed by NickTomlin** 2016-04-21 19:29 UTC
