### ISSUE TITLE
browset.get() method sometimes freezes Protractor

### ISSUE THREAD

**Issue by azangru** [angular/protractor#2144] opened 2015-05-15 13:29 UTC
Dear Protractor team,

We have this very confusing issue. When running a test suite, Protractor occasionally freezes at the step that calls the `browser.get()` method. To make matters worse, it doesn't happen always, but it happens frequently enough to be painful (about every third or fourth run of the test suite). Here is what we could figure out so far:

- we use the Cucumber.js framework, and the freezing episodes occur only when the whole suite (of 18 scenarios) is run; never when running individual scenarios;
- in our test suite, `browser.get` is called multiple times — yet in those ~30% of test runs that result in Protractor's freezing, this freezing occurs in the middle of the test suite, after `browser.get` has been successfully called several times (also, it is always the same step during which the freezing occurs);
- before Protractor hangs, the code up to `browser.get` in the problematic step gets executed without any problems;
- the browser does not visit the url passed as an argument to `browser.get`, but just hangs indefinitely;
- the Node console shows that no GET request has been sent
- console loggers placed in the `Protractor.prototype.get` method (in `node_modules/protractor/lib/protractor.js`) show that:
  - the method gets called
  - it receives the correct url as the `destination` argument
  - it starts the first `for` loop (`for (var i = 0; i < this.mockModules_.length; ++i)`)
  - it, however, does not execute Protractor's `driver.wait` method: the following console logger does not get registered

```  
  this.driver.wait(function() {
        console.log('1. I am inside Protractor. And I was told to visit:', destination);
```

At this point, we are completely mystified. Could you please suggest which parts of Protractor's code we could check further to narrow down the possible reason of this strange behavior?

P.S.: We use Protractor v. 1.8, but v. 2.0 behaves the same.

**Comment by cajoy** [comment] 2015-05-15 15:07
I have the same issue.

Protractor stopped working.

It opens browser successfully but not sends url to it.

**Comment by azangru** [comment] 2015-05-15 15:57
*Updated:* Please disregard the P.S. in my message above — I realized that I have not tested v.2.0 properly. V.2.0 is now giving me a different kind of trouble (it fails some tests complaining that `UnknownError: <unknown>: Failed to set the 'cookie' property on 'Document': Cookies are disabled inside 'data:' URLs.`), but it hasn't frozen on me yet.

**Comment by juliemr** [comment] 2015-05-15 20:13
Are you able to reproduce using another test framework? That would help us narrow it down.

I'm guessing it's some sort of control flow synchronization issue - usually when things are hanging unpredictably that's the culprit. There was an issue that is fixed for the next release of `selenium-webdriver` - https://github.com/SeleniumHQ/selenium/issues/444

**Comment by azangru** [comment] 2015-05-19 02:47
We haven't tried any other frameworks. However I've been experimenting with Protractor v.2.0.0 over the past 3 days, and these hanging episodes never occurred when testing with v.2.0.0. So I guess my original question may be closed now.

Protractor v.2.0 seems to have a more fragile control flow than its predecessor though, because it would sporadically fail the tests that worked fine on v.1.8. We are basically coding the control flow manually now, explicitly writing all the `then`'s, and still certain steps would fail from time to time, usually the same ones, but quite inconsistently.

**Comment by juliemr** [comment] 2015-05-19 06:30
I'm hoping that the resolution to the issue I linked above will help with
the fragility.

**Comment by djlaplante** [comment] 2015-06-24 20:04
I am currently having this problem in version  2.1.0. 

The hang occurs on driver.browser.get(url), and occurs consistently at the start of the second scenario in a feature file. This means that the first scenario plays through to completion, the current browser is closed, a new one is opened, and the first step in the next scenario (the get) hangs. The only configuration I've done is:

	  var seleniumAddress = 'http://localhost:4444/wd/hub';
	  var options = { browser : 'firefox', timeout : 100000};
	  this.World = pc.world(seleniumAddress, options);

	  this.After(function(callback) {
		    this.quit(callback);
		  });

**Comment by borisdiakur** [comment] 2015-07-15 12:38
@djlaplante Are you using [grunt-protractor-runner](https://github.com/teerapap/grunt-protractor-runner)? If so, try without it. I had the same problem and was able to solve it, well, now at least __most of the time__ all the suits run without hanging. Anyway, due to the __most of the time__ I've got to +1 here.

**Comment by djlaplante** [comment] 2015-07-15 13:38
@borisdiakur Nope, just regular ol' protractor-cucumber run with protractor I'm afraid :/

**Comment by borisdiakur** [comment] 2015-07-15 14:35
Using Jasmine. Still hanging occasionally.

**Comment by kisglaci** [comment] 2015-08-11 06:14
Having the same issue using protractor 2.1 with Jasmine

**Comment by dmccown1500** [comment] 2015-08-17 20:15
+1

**Comment by danieka** [comment] 2015-08-25 07:58
+1

**Comment by borisdiakur** [comment] 2015-08-25 08:42
Running with the `--troubleshoot` flag I see that the WebDriver session is not started successfully in our case. So -1 in favour of #2419

**Comment by olabalboa** [comment] 2015-09-14 13:27
We had the same problem using protractor 2.2. 
I edited config.json in the protractor root folder, changed chromedriver version to 2.19 and downloaded  the new version of cromedriver with webdriver-manager update. That solved the freeze-problem for us.

**Comment by sjelin** [comment] 2015-11-17 20:17
Closing this because we split cucumber off with https://github.com/angular/protractor/pull/2710

**Closed by sjelin** 2015-11-17 20:17 UTC
Labels: framework: cucumber

**Comment by timnederhoff** [comment] 2018-06-07 08:55
I still encounter this problem with protractor 5.3.2, geckodriver 0.20.1 and Firefox 60.0.1. Was there a solution for this issue? I don't really get why #2710 whould fix it. Can you explain @sjelin ?

**Comment by wswebcreation** [comment] 2018-06-07 09:42
@timnederhoff 

First of all this is an old issue, so nobody will look at this (instead of me ;-)). 
Secondly @sjelin currently isn't working on the project, so the change he will react is small.

If this is still an issue please create a new issue with a detailed description in it so we can reproduce it

Tnx in advance

**Comment by timnederhoff** [comment] 2018-06-07 13:11
Hi @wswebcreation Thanks for noticing! I'll create a new issue then

**Comment by IgorSasovets** [comment] 2018-06-08 13:09
@wswebcreation , sorry that ask you here but does @sjelin supports webdriver-js-extender now? In case he doesn't, who I should ask for issue review?

**Comment by wswebcreation** [comment] 2018-06-08 13:49
Hi @IgorSasovets

I don't know who's picking this up. This issue is already closed.
