### ISSUE TITLE
getLocationAbsUrl() returns PATH instead of absolute URI

### ISSUE THREAD

**Issue by brunocascio** [angular/protractor#3830] opened 2016-12-15 13:28 UTC
Hi there!

I'm trying to get the absolute URI `getLocationAbsUrl()` but this returns `/login` instead of `http://localhost:8000/#!/login`.

Bug report
---

- Node Version: `6.9.1`
- Protractor Version: `^4.0.13`
- Angular Version: `1.5.9`
- Browser(s): `Chrome (using npm install chromedriver instead of driver update)`
- Operating System and Version `OS X Yosemite`
- Your protractor configuration file:
```
var SpecReporter = require('jasmine-spec-reporter');

exports.config = {
  // Your test script communicates directly Chrome Driver or Firefox Driver,
  // bypassing any Selenium Server.
  directConnect: true,

  // Capabilities to be passed to the webdriver instance.
  capabilities: {
    'browserName': 'chrome'
  },

  // path to chrome driver
  chromeDriver: 'node_modules/chromedriver/bin/chromedriver',

  // Spec patterns are relative to the location of the spec file. They may
  // include glob patterns.
  suites: {
    // login page tests
    login: 'tests/e2e/login/**/*.spec.js',
  },

  // Options to be passed to Jasmine-node.
  jasmineNodeOpts: {
    print: function() {
      // return undefined. Using SpecReporter instead.
    }
  },

  onPrepare: function() {
    // add jasmine spec reporter
    jasmine.getEnv().addReporter(new SpecReporter());
  }
};

```
- A relevant example test
```
describe('Page: Login', function() {
  var URI = common.URL + '/#!/login';
  var TEST_EMAIL = common.TEST_EMAIL;

  beforeEach(function(){
    browser.get(URI);
    browser.driver.manage().deleteAllCookies();
  });

  it('Login Form: should be redirected on success login', function() {
    element(by.model('vm.credentials.username')).sendKeys('rbobby');
    element(by.model('vm.credentials.password')).sendKeys('paSsw0rdh@sh');
    var btnSubmit = $('.loginform [type="submit"]').click();

    // HERE
    expect(browser.getLocationAbsUrl()).not.toEqual(URI);
  });

});
```

- Output from running the test

```
✗ Login Form: should be redirected on success login
      - Expected '/login' not to equal 'http://localhost:8000/#!/login'.
```
- The URL you are running your tests against (if relevant)

```
http://localhost:8000
```

**Comment by juliemr** [comment] 2016-12-19 19:10
Duplicate of https://github.com/angular/protractor/issues/3830

**Closed by juliemr** 2016-12-19 19:10 UTC

**Comment by brunocascio** [comment] 2016-12-20 18:02
@juliemr #3830 is this issue :)

**Comment by bmsoko** [comment] 2016-12-21 20:47
@juliemr Which is this duplicated of?
