### ISSUE TITLE
by.repeater doesn't handle one-time bindings

### ISSUE THREAD

**Issue by voithos** [angular/protractor#2641] opened 2015-10-28 14:13 UTC
Essentially, a repeater defined as `ng-repeat="item in ::ctrl.items"` does not get found by the locator `by.repeater('item in ctrl.items')`. I'm not sure if this flexibility is desired, but since there is already a more precise `by.exactRepeater`, perhaps it'd be worthwhile.

It seems like the current implementation [simply search for the locator string via `.indexOf()`](https://github.com/angular/protractor/blob/bc16de70ae7f58474ba46ae4bf24497fab09ae70/lib/clientsidescripts.js#L149). The fix may be as simple as stripping out the `::` before checking for the locator:

    return ngRepeat.replace(/::/g, '').indexOf(repeater) != -1;

**Comment by hankduan** [comment] 2015-10-28 17:38
duplicate of https://github.com/angular/protractor/issues/2434

**Closed by hankduan** 2015-10-28 17:38 UTC
Labels: status: duplicate
