### ISSUE TITLE
Feature Request: add `closeOnFail` or equivalent option to config file  

### ISSUE THREAD

**Issue by T3KT4K** [angular/protractor#2983] opened 2016-02-28 07:26 UTC
Feature Request:
Would it be possible to add an option you can set in your config file that would allow for you to choose whether or not the browser being run got closed when a failed test is run? This feature request is like #1433 however, if this option were to be set to false, **only the tests that fail would stay open**.
Example config file
```
exports.config = {
    //other settings skipped for clarity
    closeOnFail = false
};
```
- Reasons for adopting new feature: This would be incredibly useful for debugging both the tests and the actual applications when a result is not as was expected.
- Is this a breaking change? I cannot imagine it would be as it would probably use the same functionality of `browser.pause()` but only call it at a failed test

**Comment by NickTomlin** [comment] 2016-02-28 15:07
Could you please update your request with the information for feature requests in the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE#L27)?

**Comment by T3KT4K** [comment] 2016-03-01 07:15
bump

**Comment by NickTomlin** [comment] 2016-03-05 14:30
I'm not sure how we'd handle this, since tests run one after another. Orchestration would get very complex since we'd need to do the following on test failure 

1. Keep the existing protractor session over 
2. Start an entirely new one at the point where the other failed (skipping over the failed test) 
3. Leave the failed windows open.

**Comment by juliemr** [comment] 2016-07-14 20:01
Dupe of https://github.com/angular/protractor/issues/1433

**Closed by juliemr** 2016-07-14 20:01 UTC
Labels: type: feature request
