### ISSUE TITLE
self signed certificate error when trying webdriver-manager update

### ISSUE THREAD

**Issue by bakumastah** [angular/protractor#1847] opened 2015-02-24 16:05 UTC
This is what I get:
```
Updating selenium standalone
downloading https://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar...
Updating chromedriver
downloading https://chromedriver.storage.googleapis.com/2.14/chromedriver_mac32.zip...
Error: Got error Error: self signed certificate in certificate chain from https://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar
Error: Got error Error: self signed certificate in certificate chain from https://chromedriver.storage.googleapis.com/2.14/chromedriver_mac32.zip
```

**Comment by tullmann** [comment] 2015-02-24 18:06
This probably isn't a Protractor problem, but a configuration issue on your host.  You should be able to reproduce this by just visiting the URL directly:

    curl -O "https://chromedriver.storage.googleapis.com/2.14/chromedriver_mac32.zip"

(Or try it in a local web browser from the same host.)  You should see the same error.

I ran into a similar problem recently and the issue was resolved by updating the trusted CA certificates on my host (the "ca-certificates" package on Debian Linux).  But, I suspect there are lots of ways to break SSL trust chains, so the problem could be different in your case.  (I'm pretty confident that googleapis.com isn't using a self-signed certificate.)

**Comment by juliemr** [comment] 2015-02-25 18:26
@tullmann that sounds about right, I don't think webdriver-manager can fix all configuration issues. Closing as not a general protractor issue.

**Closed by juliemr** 2015-02-25 18:26 UTC

**Comment by bakumastah** [comment] 2015-02-25 18:28
It turned out to be a Kaspersky Antivirus HTTPS protection issue. Thanks for your help!

**Comment by esoyke** [comment] 2016-12-21 15:47
I found this can be overcome by using the --ignore_ssl option:
https://github.com/angular/protractor/issues/1477

I had previously tried manually doing a curl of the three libraries with the -k option, which did download the libraries, but that wasn't enough to get it installed as a start still wouldn't work. Judging by the console output when I ran update with the -ignore_ssl option, it looks like I simply forgot to unzip the files (and it also sets file permissions).

**Comment by vvedachalam** [comment] 2018-02-27 14:48
@esoyke I recently only used set strict-ssl false  but now it is not working. Not sure why
I was trying ignore-ssl instead of ignore_ssl
Thanks

**Comment by espekkaya** [comment] 2018-03-01 07:10
I had same issue there. Our machine is working on windows server. I have opened cmd with as administrator. it is working like a charm now.
