### ISSUE TITLE
Error: Cannot find module '_debugger'

### ISSUE THREAD

**Issue by MrFrankel** [angular/protractor#4443] opened 2017-08-13 13:40 UTC
Hey,
I'm getting:
`Error: Cannot find module '_debugger'` when placing browser.pause() anywhere in my suites.

any clues?

- Node Version: 8.1.4
- Protractor Version: ^5.1.2
- Angular Version: ^4.1.2
- Browser(s): chrome
- Operating System and Version  mac elcapitan

**Comment by wswebcreation** [comment] 2017-08-13 14:01
Duplicate of https://github.com/angular/protractor/issues/4307, will close this one

**Closed by wswebcreation** 2017-08-13 14:01 UTC
