### ISSUE TITLE
Bug in timeouts protractor 2.1.0, jasmine 2.3.1

### ISSUE THREAD

**Issue by nishakchaudhari** [angular/protractor#2394] opened 2015-07-31 21:02 UTC
I have a few test cases and when one of the test fails because of timeout , all the subsequent tests fail because of timeout. If I increase the timeout for the failing test and make that test case pass, no subsequent test case fails. All work fine. Why subsequent test cases use timeout specified for previous test case?
Below is my spec file:
```js
'use strict';

describe('page', function() {
beforeEach(function() {
console.log('------- in before each');
});
afterEach(function() {
console.log('------- in after each');
});
it('test 1',function() {
return browser.get('https://docs.angularjs.org/api');
});
it('test 2',function() {
return browser.get('https://angularjs.org/');
},100);
it('test 3',function() {
return browser.get('https://docs.angularjs.org/tutorial');
});
it('test 4',function() {
return browser.get('https://docs.angularjs.org/misc/contribute');
});
});
```
below is my conf file:
```js
exports.config = {
seleniumAddress: 'http://localhost:4444/wd/hub',
specs: ['todo-spec.js'],
capabilities: {
'browserName': 'firefox',
},
framework: 'jasmine2',
};
```
So test 2 fails and test 3 and test 4 also fail.
If test 2 passes then test 3 and test 4 pass .
Also I observed that this problem occurs if using afterEach in suite. If we are not using afterEach , everything works fine.

**Comment by nishakchaudhari** [comment] 2015-07-31 21:04
I also found out the following: 
if you comment following line , it works fine
node_modules/protractor/node_modules/jasminewd2/index.js : 258:    // flow.reset();
OR
 if we comment the following line, it will work fine
node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:
1355:         // this.activeFrame_ = null;
@juliemr

**Comment by sjelin** [comment] 2015-09-21 16:24
Duplicate of https://github.com/angular/protractor/issues/1797.  We're working on it

**Closed by sjelin** 2015-09-21 16:24 UTC
