### ISSUE TITLE
display: none element getText() works in Chrome but it doesn't work in Firefox 31

### ISSUE THREAD

**Issue by patoi** [angular/protractor#1272] opened 2014-09-01 17:42 UTC
Ubuntu 14.04.1 64 bit
Chrome: Version 34.0.1847.116
Firefox: 31.0
Protractor:  tested with 1.0.0 and 1.1.1, both failed

Example:
```html
<div style="display: none;" id="example">{{mycontent}}</div>
```
```javascript
element(by.id('example')).getText().then(function(e) {
            console.log(e);
        });
```
Results:
In Chrome shown e value in terminal.
In Firefox shown nothing.

**Comment by patoi** [comment] 2015-01-20 15:51
Testing iframe data with Chrome doesn't work (it is working as described before).

Ubuntu 14.04.1 64 bit
Protractor 1.6.1
Chrome 39

Workaround: use 2em (1em isn't working)
```html
<iframe style="display: block; width: 2em; height: 2em; position: fixed; top: 0px; left: 0px;" ...
```

Last described workaround with 1em is not working.

Use case: creating dynamic html content (mustachejs) for printing. Content is hidden in an iframe. Generated data in the iframe will be tested by protractor.

**Comment by jleyba** [comment] 2015-02-25 21:44
From Selenium's point-of-view, Firefox has the correct behavior. With `display:none`, getText should always return an empty string. In your work around, you shouldn't need to use em. Setting `width: 1px; height: 1px` should be sufficient.

**Comment by juliemr** [comment] 2015-10-01 00:23
Closing as working as intended, as Selenium/Webdriver is implemented.

**Closed by juliemr** 2015-10-01 00:23 UTC
Labels: type: external bug, WebDriver issue/feature
