### ISSUE TITLE
Select element by attribute

### ISSUE THREAD

**Issue by BrodaNoel** [angular/protractor#2012] opened 2015-04-07 13:50 UTC
Guys,
I'm getting Invalid Selector ussing:

by.css('.xxxx .select-option[data-value=3]')
and
by.css('.xxxx .select-option["data-value"=3]')

Why is that? Is it Ok?
Is there a way to select by class+attr?

**Comment by juliemr** [comment] 2015-04-08 20:23
You can see that these are not valid selectors by using them in chrome or firefox dev tools console, such as `document.querySelector('.xxxx .select-option["data-value"=3]')`. 

The problem is that the number is not a valid comparison. Fix: `.xxx select-option["data-value"="3"]`

**Comment by juliemr** [comment] 2015-04-08 20:24
See also
http://stackoverflow.com/questions/6247221/css-selectors-cannot-match-numerical-attribute-values-why

Closing as an answered question.

**Closed by juliemr** 2015-04-08 20:24 UTC
