### ISSUE TITLE
Protractor 5.1.1- Assertions failure is causing E/launcher - Process exited with error code 199

### ISSUE THREAD

**Issue by nanichandu84** [angular/protractor#4199] opened 2017-04-04 00:53 UTC
Hi I am using protractor version 5.1.1. When my chai assertions are failed the process exit with error code 199 and no reports are generated. 

I am using protractor-cucumber framework with chai & chai-as-promised libraries.

Any help is much appreciated. Thanks in advance.

**Comment by NickTomlin** [comment] 2017-04-04 18:13
Hi there,

Please follow the [Issue Template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) when opening new issues. Otherwise it's unclear what the issue is and how we can actually help.

I'm going to close this issue, please re-open a new one following the issue template linked above. Thanks! 😄

**Comment by mgiambalvo** [comment] 2017-04-12 00:17
I think this is the error you get when using directConnect with FireFox. There's a known issue (https://github.com/angular/protractor/issues/3823) about this. If you are using directConnect with Firefox, you might try switching to selenium standalone. You can do 

```
webdriver-manager update
webdriver-manager start
```
 
to start a selenium standalone server and add `seleniumAddress: 'http://localhost:4444` to your config, and then you should be good to go.

**Comment by heathkit** [comment] 2017-05-01 02:15
I'm going to assume this is the Firefox issue. If it isn't, please submit a new issue with more detail. See https://github.com/angular/protractor/issues/4253

**Closed by heathkit** 2017-05-01 02:15 UTC
Labels: status: duplicate
