### ISSUE TITLE
Using element(by.xpath)-> is causing FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

### ISSUE THREAD

**Issue by kajaleprashant24** [angular/protractor#3442] opened 2016-08-04 05:16 UTC
Using element(by.xpath)-> is causing FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory.

- Node Version: `:- V4.3.1
- Protractor Version: `:- 3.3.0
- Browser(s): Chrome
- Operating System and Version :- Windows 10, Windows server 2012 R2
- Your protractor configuration file
- A relevant example test

- Steps to reproduce the bug
1. locate a element using xpath
` Var el=element(by.xpath("//tcc-banner//div[@class='banner-right']//div[text()='NEW QORDERI2 CASE']"));``

2. Use JS to scroll into view to that element. Below is the function for that.
```

scrollAndClick(el);

this.scrollAndClick = function(element) {
        browser.executeScript(arguments[0].scrollIntoView(), element);
        element.click();
    };
```
3. Run the tests.

- Output from running the test:-

Exceptions:-
Started

<--- Last few GCs --->

  113789 ms: Mark-sweep 1325.3 (1456.9) -> 1329.5 (1456.9) MB, 3702.4 / 0 ms [allocation failure] [GC in old space requested].
  117537 ms: Mark-sweep 1329.5 (1456.9) -> 1329.5 (1456.9) MB, 3747.9 / 0 ms [allocation failure] [GC in old space requested].
  121527 ms: Mark-sweep 1329.5 (1456.9) -> 1325.3 (1456.9) MB, 3988.4 / 0 ms [last resort gc].
  125012 ms: Mark-sweep 1325.3 (1456.9) -> 1325.3 (1456.9) MB, 3484.2 / 0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000001E8ABBB4639 <JS Object>
    3: addCallback_ [C:\Users\pkajale\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:~1278] [pc=000000293803D99B] (this=0000008E6D24F199 <a Promise with map 0000003BDF2C5CF1>,callback=0000031C0CEF2CE1 <JS Function toWireValue (SharedFunctionInfo 00000235E9E55919)>,errback=000001E8ABB041B9 <undefined>,name=000001E8ABB671F9 <String[4]: then>,fn=000002...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory.

If we locate the element with ` browser.findElement(by.xpath()); ` This works.

**Comment by NickTomlin** [comment] 2016-08-04 17:39
Hi there,

Please follow the [Issue Template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) when opening new issues. Otherwise it's unclear what the issue is and how we can actually help.

I'm going to close this issue, please re-open a new one following the issue template linked above. Thanks! 😄

**Comment by kajaleprashant24** [comment] 2016-08-05 03:56
Updated the description

**Closed** 2016-08-05 04:10 UTC
Labels: status: needs more info
