### ISSUE TITLE
feat(webdriver functions): Unwrapp Portractor elements when passed to webdriver functions

### ISSUE THREAD

**Issue by sjelin** [angular/protractor#3061] opened 2016-03-24 18:48 UTC
Sometimes users run into problems when they get an element using protractor's `element()`, and then pass it to a webdriver function, which is expecting the [`webdriver.WebElement`](http://www.protractortest.org/#/api?view=webdriver.WebElement) version instead of our wrapped [`ElementFinder`](http://www.protractortest.org/#/api?view=ElementFinder).  Instead of directly copying functions from `webdriver` to `protractor` and `driver` to `browser`, we could put in a small wrapper which calls [getWebElement](http://www.protractortest.org/#/api?view=ElementFinder.prototype.getWebElement) on all `ElementFinder` arguments.  Thoughts?  The only issue is if for some reason the original `ElementFinder` version had to be passed.

@NickTomlin @juliemr @cnishina @mgiambalvo

**Comment by juliemr** [comment] 2016-07-14 20:14
duplicate of https://github.com/angular/protractor/issues/1600

**Closed by juliemr** 2016-07-14 20:14 UTC
Labels: type: discussion, type: feature request
