### ISSUE TITLE
Switching browser windows on non-angular pages

### ISSUE THREAD

**Issue by unknownletter** [angular/protractor#3077] opened 2016-03-31 14:55 UTC
I was wondering if I could get some more information about switching windows in chrome. I have to non-angular pages and after a submit a form another window opens and I am trying to access that window. I have tried just getting getting all the handles and just accessing handles[1], but it seems to just stall on trying to get this handle and gives me a Failed: timeout: Timed out receiving message from renderer: 10.000. I do see the second window open and it seems to be accessible. The handles.length I get it 2 so I know it sees something. I just don't know why I can't access that second handle. 

I thought maybe it would be linked to this issue, but my code does pass once in a while: https://bugs.chromium.org/p/chromedriver/issues/detail?id=817

I apologize if this should be in stackexchange. I do have a question posted there with my detailed code: http://stackoverflow.com/questions/36271826/switching-windows-and-focus-in-webdriver-with-non-angular-pages/36285686#36285686

Selenium standalone version: 2.52.0
Chromedriver version: 2.21
Chrome: 49.0.2623.110
Protractor version: 3.2.2

**Comment by NickTomlin** [comment] 2016-03-31 21:07
Hi there!

You did the right thing by asking on StackOverflow. The protractor issue queue is not for debugging questions. It looks like you are dealing with a _lot_ of waiting for pages to load. I'd recommend narrowing down your question to the smallest possible reproducible example to get help.

I'm going to go ahead and close this issue because StackOverflow or Gitter are the right places to proceed.

Thanks!

**Closed by NickTomlin** 2016-03-31 21:07 UTC
