### ISSUE TITLE
invalid selector error when using $ syntax on numerical id

### ISSUE THREAD

**Issue by qualityshepherd** [angular/protractor#1973] opened 2015-03-25 19:34 UTC
I'm getting an error when attempting to use a selector that starts with a number? At least that the only time I see the error. Non-numeric ids seem to all work fine... 

Element works as expected when using `element` syntax:
    `this.layerHidden = element(by.id('5508ce43a91b2'));`

Works fine:
    `this.whatever = $('#someId');`

But throws error when using `$` syntax:
    `this.layerHidden = $('#5508ce43a91b2');`

I'm running Protractor 2.0 and Jasmine2. 

**The error:**
```javascript
- Failed: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=41.0.2272.104)
  (Driver info: chromedriver=2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf),platform=Mac OS X 10.10.2 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 20 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/invalid_selector_exception.html
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: '13.local', ip: '172.16.66.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.2', java.version: '1.7.0_75'
*** Element info: {Using=css selector, value=#5508ce43a91b2}
Session ID: 2c222405e47f430b119e7716791c1db0
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=MAC, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/var/folders/39/2gckmzs959l7x2y1rn_cp9tc0000gn/T/.org.chromium.Chromium.k7tLXw}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=41.0.2272.104, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]
        (Session info: chrome=41.0.2272.104)
        (Driver info: chromedriver=2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf),platform=Mac OS X 10.10.2 x86_64) (WARNING: The server did not provide any stacktrace information)
      Command duration or timeout: 20 milliseconds
      For documentation on this error, please visit: http://seleniumhq.org/exceptions/invalid_selector_exception.html
      Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
      System info: host: '13.local', ip: '172.16.66.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.2', java.version: '1.7.0_75'
      *** Element info: {Using=css selector, value=#5508ce43a91b2}
      Session ID: 2c222405e47f430b119e7716791c1db0
      Driver info: org.openqa.selenium.chrome.ChromeDriver
      Capabilities [{platform=MAC, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/var/folders/39/2gckmzs959l7x2y1rn_cp9tc0000gn/T/.org.chromium.Chromium.k7tLXw}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=41.0.2272.104, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]
          at /Volumes/cerosvm-1/ceros/tests/e2e/node_modules/protractor/node_modules/jasminewd2/index.js:102:16
          at [object Object].promise.ControlFlow.runInFrame_ (/Volumes/cerosvm-1/ceros/tests/e2e/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1877:20)
          at [object Object].promise.Callback_.goog.defineClass.notify (/Volumes/cerosvm-1/ceros/tests/e2e/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:2464:25)
          at [object Object].promise.Promise.notify_ (/Volumes/cerosvm-1/ceros/tests/e2e/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:563:12)

**************************************************
*                    Failures                    *
**************************************************

1) Player SDK Button should hide layer
  - Failed: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=41.0.2272.104)
  (Driver info: chromedriver=2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf),platform=Mac OS X 10.10.2 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 20 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/invalid_selector_exception.html
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: '13.local', ip: '172.16.66.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.2', java.version: '1.7.0_75'
*** Element info: {Using=css selector, value=#5508ce43a91b2}
Session ID: 2c222405e47f430b119e7716791c1db0
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=MAC, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/var/folders/39/2gckmzs959l7x2y1rn_cp9tc0000gn/T/.org.chromium.Chromium.k7tLXw}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=41.0.2272.104, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]
    (Session info: chrome=41.0.2272.104)
    (Driver info: chromedriver=2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf),platform=Mac OS X 10.10.2 x86_64) (WARNING: The server did not provide any stacktrace information)
  Command duration or timeout: 20 milliseconds
  For documentation on this error, please visit: http://seleniumhq.org/exceptions/invalid_selector_exception.html
  Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
  System info: host: '13.local', ip: '172.16.66.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.2', java.version: '1.7.0_75'
  *** Element info: {Using=css selector, value=#5508ce43a91b2}
  Session ID: 2c222405e47f430b119e7716791c1db0
  Driver info: org.openqa.selenium.chrome.ChromeDriver
  Capabilities [{platform=MAC, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/var/folders/39/2gckmzs959l7x2y1rn_cp9tc0000gn/T/.org.chromium.Chromium.k7tLXw}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=41.0.2272.104, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]
      at /Volumes/cerosvm-1/ceros/tests/e2e/node_modules/protractor/node_modules/jasminewd2/index.js:102:16
      at [object Object].promise.ControlFlow.runInFrame_ (/Volumes/cerosvm-1/ceros/tests/e2e/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1877:20)
      at [object Object].promise.Callback_.goog.defineClass.notify (/Volumes/cerosvm-1/ceros/tests/e2e/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:2464:25)
      at [object Object].promise.Promise.notify_ (/Volumes/cerosvm-1/ceros/tests/e2e/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:563:12)
```

**Comment by juliemr** [comment] 2015-03-25 19:55
Interesting! I see the same when I just try to use `document.querySelector('#123')` in the chrome dev tools console. See this SO post about it: http://stackoverflow.com/questions/20306204/using-queryselector-with-ids-that-are-numbers

Oddly, `element(by.id('1abc'))` works fine. So, you can use that as a workaround for the moment, or use the escaping listed in the link above.

I'm going to close this as, strangely, working as intended.

**Closed by juliemr** 2015-03-25 19:55 UTC

**Comment by qualityshepherd** [comment] 2015-03-25 20:00
Ha! Thanks Julie...

**Comment by jsaxon-cars** [comment] 2022-08-19 05:07
The link above describes it.  Here's the TLDR:  It's a fundamental component of a CSS identifier that it NOT start with a number even though it's legal HTML. 
 https://www.w3.org/TR/CSS21/syndata.html#value-def-identifier.  
 
 Somehow I think Chromium's `document.querySelector()` _just_ started enforcing that...
