### ISSUE TITLE
Heads up: Protractor is not working with Firefox 35/36

### ISSUE THREAD

**Issue by ericmdantas** [angular/protractor#1734] opened 2015-01-16 13:31 UTC
Yesterday things were working just fine, but today Firefox got updated and protractor suddenly wouldn't run the tests anymore. It'd just show the page - like it never requested the whole thing - and, after a while, it shows the ```Jasmine spec timeout``` type of error.

Apparently it's something related to the driver, since when I downgraded Firefox to 33.1 and ran the tests again, they worked like a charm.

When they release the compatible version (firefox/driver), do I have to update the ```webdriver-manager``` or will ```protractor``` have to be updated as well? 

Thanks!

**Comment by ValentinH** [comment] 2015-01-16 14:38
Same here!

**Comment by juliemr** [comment] 2015-01-16 19:01
We're taking a look. Here's what I know so far:

This is not an issue just with Protractor. I can do a test using only webdriverJS against FireFox35 and it fails. Here's the test: 

```js

var util = require('util'),
    webdriver = require('selenium-webdriver');

var driver = new webdriver.Builder().
    usingServer('http://localhost:4444/wd/hub').
    withCapabilities({'browserName': 'firefox'}).
    build();

driver.get('http://juliemr.github.io/webdriver-bugs/');

driver.executeAsyncScript(function(cb) {
  window.setTimeout(function() {
    cb();
  }, 30);
});

driver.quit();
```

In the firefox console, I see the error: `Error: Permission denied to access property '0'`

**Comment by juliemr** [comment] 2015-01-16 19:08
Filed issue: https://code.google.com/p/selenium/issues/detail?id=8398

**Comment by ericmdantas** [comment] 2015-01-17 14:51
At some point I got that error too, @juliemr.

Looks like we'll just have to wait, then.

Thanks for looking into it =]

**Comment by ehacke** [comment] 2015-01-17 20:19
:+1: Same issue here.

**Comment by flegall** [comment] 2015-01-20 14:09
Same issue here.

**Comment by byaminov** [comment] 2015-01-20 14:56
:+1: same here

**Comment by juliemr** [comment] 2015-01-20 18:23
My issue was merged into https://code.google.com/p/selenium/issues/detail?id=8390 which is tracking. Note that this is broken on all systems for FireFox 35.

**Comment by Olgagr** [comment] 2015-01-21 11:14
:+1:

**Comment by igorshubovych** [comment] 2015-01-21 13:33
+1
http://stackoverflow.com/questions/27645260/protractor-e2e-tests-run-at-chrome-but-halt-at-firefox

**Comment by pfrandsen** [comment] 2015-01-30 16:00
Temporary "solution" - downgrade to Firefox 34: https://ftp.mozilla.org/pub/mozilla.org/firefox/releases/34.0

**Comment by juliemr** [comment] 2015-02-02 19:22
This has been addressed and will be fixed once the next version of the selenium server is out.

**Comment by adtrsa** [comment] 2015-02-06 10:04
Just out of interest sake.  I am able to get Firefox 35 and selenium to behave properly, even on headless server using the following python script (adapted from http://selenium.googlecode.com/svn/trunk/docs/api/py/index.html):

```
from selenium import webdriver
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.common.keys import Keys
import time
import os
browser = webdriver.Firefox() 
browser.get("https://angularjs.org")
assert "AngularJS" in browser.title
# Uncomment if you need to take screenshot using ImageMagick import.
# Useful to 'prove' your Xvfb or other display works as expected.
#os.system('import -window root test_firefox_selenium.jpg')
browser.close()
```

**Comment by jesusrw** [comment] 2015-02-06 17:21
"...*This has been addressed and will be fixed once the next version of the selenium server is out.*"
Aprox When will this happen? is this related to linux?
or is it better to just **downgrade** [Firefox](https://ftp.mozilla.org/pub/mozilla.org/firefox/releases/34.0/linux-x86_64/en-US/)?


@adtrsa  so its something not related directly to the webdriver? what OS, are you using ? 
Thanks
 Cheers

**Comment by juliemr** [comment] 2015-02-06 17:43
I can't speak to when the next selenium server will be released, but I will update a new version of Protractor when that occurs.  

It is not linux specific, it is for all users of Firefox 35. You can read the full details at https://code.google.com/p/selenium/issues/detail?id=8390

**Comment by acharyaankush** [comment] 2015-02-20 08:41
Just came across this issue while running the tests today...Thank you for the heads up and the details!

**Comment by mryellow** [comment] 2015-02-23 07:53
When you're bashing your head against a wall all day...... It's usually someone elses bug ;-D

Now I can relax, thanks for heads-up, wish I had looked earlier.

**Comment by Ferengee** [comment] 2015-02-24 10:02
I used a firefox protable 34 as downgraded version so I can keep the latest version of firefox on the windows machine I am testing on
I installed firefox portable on an external disk
and added the reference to the binary in the protractor config:
 capabilities: {
    'browserName': 'firefox',
    'firefox_binary': 'h:\\portableapps\\FirefoxPortable\\FirefoxPortable.exe'
  },

**Comment by Risto-Stevcev** [comment] 2015-02-24 16:35
@mryellow Yeah... I spent all night debugging webdriver only to find this wondering why on earth Firefox doesn't work with it. Next time I'll know to check the issue tracker for a finicky library :-/

**Comment by vecernik** [comment] 2015-02-25 15:54
Selenium throws this with FF 36 : ERROR - Unable to start a WebDriver session.
It seems sticking with 34 is only fix now.

**Comment by Tokeiito** [comment] 2015-02-26 08:22
Same issue with Firefox 36

**Comment by ericmdantas** [comment] 2015-02-26 10:12
@vecernik, @Tokeiito: thanks! Updated the title.

**Comment by igorshubovych** [comment] 2015-02-27 14:49
Selenium was upgraded to 2.45.0
https://github.com/SeleniumHQ/selenium/commit/5017cb8e7ca8e37638dc3091b2440b90a1d8686f

Issue is still not fixed.

**Comment by mechevarria** [comment] 2015-02-27 15:52
Just adding to the list of people affected.

**Comment by szimek** [comment] 2015-02-27 17:58
Here's a dev version of Selenium standalone that should work with Firefox 36, though I've tested it only with Firefox 37. Copy the file to `node_modules/protractor/selenium` folder and rename it to `selenium-server-standalone-2.44.0.jar`. I've downloaded it from Selenium CI server (http://ci.seleniumhq.org:8080/job/Build%20All%20Java/5827/).

https://dl.dropboxusercontent.com/u/3526636/selenium-server-standalone-2.45.0.jar

**Comment by juliemr** [comment] 2015-02-27 19:43
Hi all,

This issue is now fixed with the selenium standalone server 2.45.0. It's available from the master branch of Protractor, but we need to cut a release. Also note that Sauce Labs does not yet support the selenium standalone server 2.45.0, so firefox tests there will still fail.

I'm keeping this issue open until it's fully resolved.

**Comment by mechevarria** [comment] 2015-02-28 15:08
I just tried running protractor with Firefox 36.0 and selenium standalone 2.45.0 (renamed the jar like in the post from @szimek), but with no luck.

Firefox 34 Portable works like in the post from @Ferengee.  Another option is to set firefoxPath

    var exports.config = {
      firefoxPath: 'C:/Users/mechevarria/FirefoxPortable/FirefoxPortable'
    }

**Comment by Risto-Stevcev** [comment] 2015-02-28 20:45
A quick fix for linux users to run Firefox 34:
```bash
$ pwd
/home/foo/firefoxDir
$ curl -O https://ftp.mozilla.org/pub/mozilla.org/firefox/releases/34.0/linux-x86_64/en-US/firefox-34.0.tar.bz2
$ tar xfvj firefox-34.0.tar.bz2
$ cd /your/protractor/dir
$ protractor --specs myspec.js --browser firefox --firefoxPath /home/foo/firefoxDir/firefox/firefox
```

**Comment by tullmann** [comment] 2015-02-28 21:10
@Risto-Stevcev one caveat to that download-old-version workaround is that if you give firefox some idle time it will upgrade itself.  I disabled upgrades in user.js (see https://support.mozilla.org/en-US/questions/1003777), and that seems to have worked for me.

**Comment by Risto-Stevcev** [comment] 2015-03-01 09:49
@tullman You can run firefox before testing to turn off autoupdate. If it's updating faster than you can get to the setting, you can just briefly turn your internet off.

**Comment by creydr** [comment] 2015-03-02 09:20
Selenium 2.45 released and works with Firefox 36

**Comment by ericmdantas** [comment] 2015-03-02 10:53
Just downloaded version 2.45 of the selenium server.

I tried to run it manually and then run both Chrome and Firefox (36), but only Chrome runs - just like before.

I'm using Windows, by the way.

**Comment by Tekki** [comment] 2015-03-02 11:13
Did you notice? Issue 1872 is about update to 2.45, and it obviously still doesn't work: https://github.com/angular/protractor/issues/1872

**Comment by ericmdantas** [comment] 2015-03-02 12:59
@Tekki, yeah, noticed that now.

But I did try it because @creydr said it worked somehow.

Let's just wait a bit more then.

**Comment by creydr** [comment] 2015-03-02 13:44
@ericmdantas and @Tekki: somehow it is working at my machine with the new selenium version (but i am running ubuntu)

**Comment by juliemr** [comment] 2015-03-02 18:22
It seems like there is some confusion, so I'd like to clarify.

Protractor uses the Selenium Server to help manage and connect browser drivers. This has just been released at 2.45, and the new version fixes the firefox 35/36 issues. The master branch of Protractor has been upgraded to use Selenium Server @2.45 and this will be pushed in a release soon.

Protractor also uses WebDriverJS (the selenium-webdriver node package). This has also just been released at 2.45, but we are having issues upgrading Protractor, which is what issue #1872 is about. Until those issues are resolved, we will remain at WebDriverJS @2.44.0

**Comment by Tekki** [comment] 2015-03-03 09:57
@juliemr: Thanks for the clarification and for version 1.8. Now everything works fine with Firefox 36 on Win 8.1 + Ubuntu.

**Comment by juliemr** [comment] 2015-03-03 18:23
Oh, and I guess I can close this now that 1.8.0 is out :)

**Comment by Risto-Stevcev** [comment] 2015-03-04 08:10
@juliemr Not sure if this is a Protractor issue or Selenium, but firefox will just hang if I use directConnect mode.

**Comment by Tekki** [comment] 2015-03-04 09:07
@Risto-Stevcev: I can confirm this on Ubuntu 12.04. It depends on the Firefox version.

This works:

    "directConnect" : true,
    "firefoxPath" : "\/opt\/firefox\/34.0b11\/firefox-bin",

The following 2 don't work:

    "firefoxPath" : "\/opt\/firefox\/35.0.1\/firefox-bin",

Error: "A Jasmine spec timed out. Resetting the WebDriver Control Flow."

    "firefoxPath" : "\/opt\/firefox\/36.0\/firefox-bin",

Error: "Timed out waiting for the WebDriver server at http://127.0.0.1:52740/hub"

**Comment by gefilte** [comment] 2015-03-04 17:47
I saw the same thing when I upgraded (both Protractor and Firefox) yesterday, but I presumed it was related to #1872. Is that not the case?

**Comment by BrodaNoel** [comment] 2015-03-04 20:40
@juliemr, I have the same issue on Firefox 30 on Windows XP.
Is there a guide with all the Firefox versions affected?

**Comment by juliemr** [comment] 2015-03-09 17:34
More clarifications - FireFox 35/36 will still hang if you are using directConnect, due to #1872. All other forms of connection should work. I'm re-opening this issue due to this lingering problem.

Sorry for the confusion.

**Comment by juliemr** [comment] 2015-03-18 22:21
With 2.0.0 out, FF should now be working in all forms.

**Closed by juliemr** 2015-03-18 22:21 UTC
Labels: browser: firefox, external bug filed, type: external bug

**Comment by ivanproskuryakov** [comment] 2015-05-06 07:23
Have the same with Firefox 35.0.1 on Mac 10.10.3 (14D136)

**Comment by ericmdantas** [comment] 2015-05-06 10:13
Hello, @ivanproskuryakov.

Updating protractor to 2.0 should do the trick.

**Comment by ivanproskuryakov** [comment] 2015-05-06 10:17
@ericmdantas thanks man! I will try

**Comment by rajeshshegokar111** [comment] 2015-05-27 07:20
Hello,
          I am not able to run protractor test cases with firefox. I tried with 29,30....38 version of firefox
My protractor version is 1.8.0 .  If i update protractor to latest version then it is not running on safari browser..  For chrome it is fine on windows, so what will be the protractor and firefox compatible versions to run protractor test cases. my selenium server standalone version 2.43.1.. chrome driver version 2.13
Thanks in advance

**Comment by bmsoko** [comment] 2015-05-27 14:59
Same as @rajeshshegokar111 around here...
