### ISSUE TITLE
protractor expect method problem !!

### ISSUE THREAD

**Issue by MahmoudSamik** [angular/protractor#3615] opened 2016-10-03 12:59 UTC
i have this line of code 
expect(warning.getText()).toEqual('The GLAccount or Number already exists.');  
but i have a weird problem. the test returns 

![](https://cloud.githubusercontent.com/assets/8050410/19038130/c674508a-8982-11e6-97a4-af57662654f8.PNG)

**Comment by MahmoudSamik** [comment] 2016-10-03 13:02
i have this line of code 
`        expect(warning.getText()).toEqual('The GLAccount or Number already exists.');
` 
but i have a weird problem. the test returns 
![m](https://cloud.githubusercontent.com/assets/8050410/19038130/c674508a-8982-11e6-97a4-af57662654f8.PNG)

**Comment by NickTomlin** [comment] 2016-10-03 16:21
Hi there,

Please follow the [Issue Template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) when opening new issues. Otherwise it's unclear what the issue is and how we can actually help.

I'm going to close this issue, please re-open a new one following the issue template linked above. Thanks! 😄

**Closed by NickTomlin** 2016-10-03 16:21 UTC
