### ISSUE TITLE
PhantomJS crashes at the end of the tests while all tests passed

### ISSUE THREAD

**Issue by thomaswinckell** [angular/protractor#1685] opened 2015-01-06 10:09 UTC
Hello !

I am using Protractor and PhantomJS in a continuous integration process. We build the project on a remote web server and launch E2E tests using Grunt, Protractor and PhantomJS. I am using Jenkins for that. I also use protractor-html-screenshot-reporter to have reports and screenshots when tests failed.

The problem is that even all tests passed (I know it because the reports show me that), sometimes (about 50%) the execution failed because PhantomJS may have died at the end of the tests. It is annoying because, in Jenkins, I am using the return code of the execution to know if the tests passed.

I am using PhantomJS v1.9.8 and Protractor v1.3.1

Here is my Protractor configuration

```
var HtmlReporter = require('protractor-html-screenshot-reporter');

exports.config = {

    onPrepare: function() {
        // Add a screenshot reporter and store screenshots to `e2e/debug`:
        jasmine.getEnv().addReporter(new HtmlReporter({
            baseDirectory: 'e2e/front/debug',
            takeScreenShotsOnlyForFailedSpecs: true
        }));
    },

    specs: ['spec/**/loginSpec.js', 'spec/**/*Spec.js'],

    baseUrl: 'SOME_URL',

    jasmineNodeOpts: {
        showColors: true,
        defaultTimeoutInterval: 30000
    }
};
```

And here is a part of my log file in Jenkins

```

[4mRunning "logDevReportAdmin" task[24m
    admin report can be found at http://SOME_URL/src/test/webapp/e2e/admin/debug/report.html

[4mRunning "protractor:devAdminPhantomjs" (protractor) task[24m
    util.puts: Use console.log instead
Starting selenium standalone server...
    util.puts: Use console.log instead
Selenium standalone server started at http://SOME_URL/wd/hub
    [32m.[0m[32m.[0m[32m.[0m

    Finished in 6.566 seconds
[32m3 tests, 5 assertions, 0 failures
[0m
    util.puts: Use console.log instead
Shutting down selenium standalone server.

[4mRunning "logDevReportFront" task[24m
    front report can be found at http://SOME_URL/src/test/webapp/e2e/front/debug/report.html

[4mRunning "protractor:devFrontPhantomjs" (protractor) task[24m
    util.puts: Use console.log instead
Starting selenium standalone server...
    util.puts: Use console.log instead
Selenium standalone server started at http://SOME_URL/wd/hub
    [32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[31mF[0m
/mnt/jenkins/work/jobs/E2E Tests/workspace/src/test/webapp/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:113
var template = new Error(this.message);
^
UnknownError: Error communicating with the remote browser. It may have died.
    Build info: version: '2.43.1', revision: '5163bce', time: '2014-09-10 16:27:33'
System info: host: 'SOME_IP', ip: 'SOME_IP', os.name: 'Linux', os.arch: 'amd64', os.version: '3.2.0-58-virtual', java.version: '1.7.0_55'
Driver info: driver.version: PhantomJSDriver
at new bot.Error (/mnt/jenkins/work/jobs/E2E Tests/workspace/src/test/webapp/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:113:18)
at Object.bot.response.checkResponse (/mnt/jenkins/work/jobs/E2E Tests/workspace/src/test/webapp/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/response.js:106:9)
at /mnt/jenkins/work/jobs/E2E Tests/workspace/src/test/webapp/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:319:20
at /mnt/jenkins/work/jobs/E2E Tests/workspace/src/test/webapp/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1582:15
at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (/mnt/jenkins/work/jobs/E2E Tests/workspace/src/test/webapp/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1640:20)
at notify (/mnt/jenkins/work/jobs/E2E Tests/workspace/src/test/webapp/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:444:12)
at notifyAll (/mnt/jenkins/work/jobs/E2E Tests/workspace/src/test/webapp/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:422:7)
at resolve (/mnt/jenkins/work/jobs/E2E Tests/workspace/src/test/webapp/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:400:7)
at [object Object].fulfill (/mnt/jenkins/work/jobs/E2E Tests/workspace/src/test/webapp/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:512:5)
at /mnt/jenkins/work/jobs/E2E Tests/workspace/src/test/webapp/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1507:10
==== async task ====
    WebDriver.takeScreenshot()
at [object Object].webdriver.WebDriver.schedule (/mnt/jenkins/work/jobs/E2E Tests/workspace/src/test/webapp/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:302:15)
at [object Object].webdriver.WebDriver.takeScreenshot (/mnt/jenkins/work/jobs/E2E Tests/workspace/src/test/webapp/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:917:15)
at [object Object].to.(anonymous function) [as takeScreenshot] (/mnt/jenkins/work/jobs/E2E Tests/workspace/src/test/webapp/node_modules/protractor/lib/protractor.js:58:25)
at ScreenshotReporter.reportSpecResults (/mnt/jenkins/work/jobs/E2E Tests/workspace/src/test/webapp/node_modules/protractor-html-screenshot-reporter/index.js:141:10)
at [object Object].reportSpecResults (/mnt/jenkins/work/jobs/E2E Tests/workspace/src/test/webapp/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:1901:39)
at [object Object].jasmine.Spec.finishCallback (/mnt/jenkins/work/jobs/E2E Tests/workspace/src/test/webapp/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2470:21)
at [object Object].jasmine.Spec.finish (/mnt/jenkins/work/jobs/E2E Tests/workspace/src/test/webapp/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2475:8)
at [object Object].onComplete (/mnt/jenkins/work/jobs/E2E Tests/workspace/src/test/webapp/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2504:10)
at [object Object].jasmine.Queue.next_ (/mnt/jenkins/work/jobs/E2E Tests/workspace/src/test/webapp/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2219:14)
[31m>> [39m
[31mFatal error: protractor exited with code: 1[39m
```

I hope someone can help me ! Maybe @juliemr :)

Thanks for you help !

**Comment by juliemr** [comment] 2015-01-06 17:37
Closing as a duplicate of #557

**Closed by juliemr** 2015-01-06 17:37 UTC
