### ISSUE TITLE
API view code links broken

### ISSUE THREAD

**Issue by faredis** [angular/protractor#3242] opened 2016-05-24 21:48 UTC
The view code links on the protractor website are broken since moving to typescript.

**Comment by NickTomlin** [comment] 2016-05-24 23:37
This is a duplicate of https://github.com/angular/protractor/issues/3170 (which _should_ be fixed on master).

@cnishina would it be possible to publish the website to incorporate the new fixes?

**Comment by cnishina** [comment] 2016-06-20 16:05
@NickTomlin Getting pretty close to the next release. I think we'll update the website then.

**Comment by juliemr** [comment] 2016-07-13 04:20
fixed now! Huzzah!

**Closed by juliemr** 2016-07-13 04:20 UTC
Labels: component: website, status: fixed for next release, type: docs
