### ISSUE TITLE
 Message:Command `./node_modules/protractor/bin/protractor ./test/protractor.config.js` failed with exit code 1

### ISSUE THREAD

**Issue by devikirankhode** [angular/protractor#3439] opened 2016-08-03 18:33 UTC
Here is my log:
/home/jenkins/workspace/Myproject/Develop/node_modules/selenium-webdriver/error.js:27
super(opt_error);
    ^
WebDriverError: null
    at WebDriverError (/home/jenkins/workspace/Myproject/Develop/node_modules/selenium-webdriver/error.js:27:5)
     at Object.checkLegacyResponse (/home/jenkins/workspace/Myproject/Develop/node_modules/selenium-webdriver/error.js:580:13)
     at /home/jenkins/workspace/Myproject/Develop/node_modules/selenium-webdriver/lib/webdriver.js:64:13
     at Promise.invokeCallback_ (/home/jenkins/workspace/Myproject/Develop/node_modules/selenium-webdriver/lib/promise.js:1329:14)
     at TaskQueue.execute_ (/home/jenkins/workspace/Myproject/Develop/node_modules/selenium-webdriver/lib/promise.js:2790:14)
     at TaskQueue.executeNext_ (/home/jenkins/workspace/Myproject/Develop/node_modules/selenium-webdriver/lib/promise.js:2773:21)
    at asyncRun (/home/jenkins/workspace/Myproject/Develop/node_modules/selenium-webdriver/lib/promise.js:2652:27)
     at /home/jenkins/workspace/Myproject/Develop/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
 From: Task: WebDriver.createSession()
     at acquireSession (/home/jenkins/workspace/Myproject/Develop/node_modules/selenium-webdriver/lib/webdriver.js:62:22)
    at Function.createSession (/home/jenkins/workspace/Myproject/Develop/node_modules/selenium-webdriver/lib/webdriver.js:295:12)                                                          at Builder.build (/home/jenkins/workspace/Myproject/Develop/node_modules/selenium-webdriver/builder.js:458:24)
    at Local.DriverProvider.getNewDriver (/home/jenkins/workspace/Myproject/Develop/node_modules/protractor/built/driverProviders/driverProvider.js:37:33)
    at Runner.createBrowser (/home/jenkins/workspace/Myproject/Develop/node_modules/protractor/built/runner.js:182:43)
    at /home/jenkins/workspace/Myproject/Develop/node_modules/protractor/built/runner.js:255:30
    at _fulfilled (/home/jenkins/workspace/Myproject/Develop/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/jenkins/workspace/Myproject/Develop/node_modules/q/q.js:863:30)
  at Promise.promise.promiseDispatch (/home/jenkins/workspace/Myproject/Develop/node_modules/q/q.js:796:13)
  at /home/jenkins/workspace/Myproject/Develop/node_modules/q/q.js:604:44
 E/launcher - Process exited with error code 1
'test:functional' errored after 25 s
Error in plugin 'gulp-shell'
**Message:**
Command `./node_modules/protractor/bin/protractor ./test/protractor.config.js` failed with exit code 1

**Comment by NickTomlin** [comment] 2016-08-03 20:06
Hi there,

Please follow the [Issue Template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) when opening new issues. Otherwise it's unclear what the issue is and how we can actually help.

I'm going to close this issue, please re-open a new one following the issue template linked above. Thanks! 😄

**Closed by NickTomlin** 2016-08-03 20:06 UTC
