### ISSUE TITLE
F[launcher] BUG: launcher exited with 1 tasks remaining

### ISSUE THREAD

**Issue by vivekbrahmadandi** [angular/protractor#2956] opened 2016-02-18 13:32 UTC
when i am running protractor suite with --suite through command , getting this issue
while some of the suites are running or some of them opening the browser immediately it exists by throwing the above issue.

I've defined suites like this
suites: {
        TestSuite: './specs/TestSuite.js',
        NDCreationAndApprove: './specs/NDEnrollAndApprove.js',
        CreateMRAndActivate: './specs/CreateMRAndActivate.js',
        NDCreationAndReject: './specs/NDEnrollAndReject.js',
        NDActivationAndLogin: './specs/NDActivationAndLogin.js',
        NDActivation: './specs/NDActivation.js',
        NDActivation1: './specs/NDActivation1.js'
    },

**Comment by vivekbrahmadandi** [comment] 2016-02-18 13:32
I can see this issue in protractor 3.1.1

**Comment by NickTomlin** [comment] 2016-02-18 14:54
Hi there, 

Can you provide a few more details:

- Node Version: 
- Browser(s): 
- Operating System and Version
- Your protractor configuration file
- A relevant example test to help us reproduce this 

Thanks!

**Comment by vivekbrahmadandi** [comment] 2016-02-18 14:56
Hi
node :v4.2.0
browser :chrome and firefox latest
os:windows 7

**Comment by NickTomlin** [comment] 2016-02-18 14:58
By normal protractor example do you mean the [example spec and configuration file](https://github.com/angular/protractor/tree/master/example)? 

If you do not, could you please provide some code that reproduces this issue so we can isolate the problem? Thanks!

**Comment by vivekbrahmadandi** [comment] 2016-02-18 15:01
Yes, i dont know why this issue comes , recetly i reinstall windows 7

**Comment by NickTomlin** [comment] 2016-02-19 15:17
I haven't had time to investigate this but I/someone should try this on a windows VM to see if it's reproducible. The fact that the example spec is not working is worrisome.

**Comment by NickTomlin** [comment] 2016-02-22 00:04
I have not been able to reproduce this on windows. I've been able to pass `--suite` to protractor 3.1.1 on a Windows 7 VM and run the example spec with both Chrome and FF. Here's my config:

```
 suites: {
    test: ['./example_spec.js'],
    another: ['./another_spec.js']
  }
```

I don't see this being an issue of having a larger configuration. Could you publish an example repository that reproduces the problem? My suspicion is that this is related to the testing environment/tests themselves and not protractor.

**Comment by vivekbrahmadandi** [comment] 2016-02-23 12:55
I can see this issue after running tests after some hours 

var MerchantLoginPage = require('../pages/merchant/LoginPage');
var MerchantHomePage = require('../pages/merchant/HomePage');
var CreateResellerPage = require('../pages/merchant/CreateResellerPage');
var Utility = require('../common/CommonUtils');
var database = require('../common/database');
var parentNameWithId;
var mobileNumberWithoutPrefix;
/*var parentName = database.getMerchantName(global.merchantId);
var merchantMobileNumber = database.generateMobileNumber();
Promise.resolve(parentName).then(function(name) {
    parentNameWithId = global.merchantId + ' - ' + name;
    console.log(parentNameWithId);
});
Promise.resolve(merchantMobileNumber).then(function(mobileNumber) {
    merchantMobileNumber = mobileNumber;
    mobileNumberWithoutPrefix = merchantMobileNumber.substr(3);
});
*/

describe('MR Creation And Activate', function() {
    var utility = new Utility();
    var merchantLoginPage = new MerchantLoginPage();
    var merchantHomePage = new MerchantHomePage();
    var createResellerPage = new CreateResellerPage();
    var utility = new Utility();
    browser.get(global.muiUrl);

    afterEach(function() {
        merchantHomePage.clickLogoutLink();
    });

    it('Create MR', function() {
        merchantLoginPage.signIn(global.merchantId, global.merchantPassword);
        merchantHomePage.clickResellerLink();
        browser.sleep(5000);
        merchantHomePage.clickCreateResellerLink();
        browser.sleep(5000);
        utility.selectOption(createResellerPage.merchant_level, 'Sales Team');
        browser.sleep(5000);
        utility.selectOption(createResellerPage.parentMerchant_selected, parentNameWithId);
        browser.sleep(5000);
        createResellerPage.inputMerchantName('mrtest');
        browser.sleep(5000);
        createResellerPage.inputMerchantMobileNumber(mobileNumberWithoutPrefix);
        browser.sleep(5000);
        createResellerPage.inputDescription('test');
        browser.sleep(5000);
        createResellerPage.clickNextButton();
        browser.sleep(5000);
        createResellerPage.getMerchantLevel().then(function(merchantLevel) {

        });

        createResellerPage.getParentMerchant().then(function(parentMerchant) {

        });
        createResellerPage.getMerchantName().then(function(merchantName) {

        });
        createResellerPage.getMerchantMobileNumber().then(function(merchantMobileNumber) {

        });
        createResellerPage.getDescription().then(function(description) {

        });
        createResellerPage.clickSaveButton();
        createResellerPage.getResponseMessage();
        //Sales-Team has been successfully created.
    });
});

**Comment by vivekbrahmadandi** [comment] 2016-02-23 13:11
Why it is causing this one, from where which files the statement is thrown 
F[launcher] BUG: launcher exited with 1 tasks remaining

**Comment by vivekbrahmadandi** [comment] 2016-02-24 10:39
Is this issue is getting only for me

**Comment by NickTomlin** [comment] 2016-02-24 14:57
Unfortunately flakiness like this is pretty common in selenium testing suites. It can be any number of things in your application stack, an error in chromedriver. 

The best advice I can give is to try and isolate it down to the smallest case (so remove variables until you can reliably reproduce the issue).

I'm going to close this because it's about debugging and not an issue with Protractor core. I'd suggest following up on StackOverflow or Gitter for help during the debugging process. Thanks, and good luck!

**Closed by NickTomlin** 2016-02-24 14:57 UTC
Labels: status: needs investigation, windows

**Comment by vivekbrahmadandi** [comment] 2016-02-24 15:12
Thanks Nick , I'm able to debug the issue .will post the issue cause

**Comment by edi9999** [comment] 2018-09-26 14:53
I have this same issue, is there any way to know which task is still "remaining" ??
