### ISSUE TITLE
Protractor failed to drag and drop elements

### ISSUE THREAD

**Issue by wangfeiv** [angular/protractor#2293] opened 2015-07-01 07:57 UTC
I tried to use protractor to simulate dragAndDrop, but it did not work, and there was no any error about it, below is my test code:

this.dragAndDropDashboardTab = function(source, target) {
    // Way-1: it did not work
    // browser.actions().dragAndDrop(source, target).perform();
    // browser.actions()
    //       .mouseDown(source)
    //       .mouseMove(target)
    //       .mouseUp()
    //       .perform();
    // Way-2: it did not work
    // browser.actions().dragAndDrop(source, target).perform();
  };

Who will tell me the work around? And would you like to help me fix this issue?

**Comment by juliemr** [comment] 2015-07-01 17:41
Duplicate of https://github.com/angular/protractor/issues/1205 or maybe https://github.com/angular/protractor/issues/583 if you are using Chrome.

**Closed by juliemr** 2015-07-01 17:41 UTC

**Comment by marcoliceti** [comment] 2015-08-11 12:54
@juliemr just like @wangfeiv I tried both:

``` javascript
browser.actions().dragAndDrop(draggable_element, target_element).perform();
```
and:

``` javascript
browser.actions().
   mouseDown(draggable_element).
   mouseMove(target_element).
   mouseUp().
perform();
```

where `draggable_element` and `target_element` are properly retrieved, i.e. this expectations are satisfied:

``` javascript
expect(draggable_element.isPresent()).toEqual(true);
expect(target_element.isPresent()).toEqual(true);
```

`draggable_element` is a `div` with an AngularJS directive that adds `draggable=true`, while `draggable_element` is a `div` with an AngularJS directive that handles the drop event by adding a row with some text inside a table within the same `div`. Here is a screenshot:

![schermata da 2015-08-11 14 17 51](https://cloud.githubusercontent.com/assets/1493439/9197361/d815114c-4033-11e5-9463-f5c1a4c0eba6.png)

The full code of my spec looks like this:

``` javascript
var draggable_element = element(...);
var target_element = element(...);
expect(draggable_element.isPresent()).toEqual(true);
expect(target_element.isPresent()).toEqual(true);
browser.actions().dragAndDrop(draggable_element, target_element).perform();
expect(element.all(by.css('tr')).count()).toEqual(1);
```

The last expectation fails: `Expected 0 to equal 1.`

I've read [#1205](https://github.com/angular/protractor/issues/1205), but it seems to me only a discussion about how to improve the syntax. Instead, I would like to know _if_ and _how_ I can test drag and drop.

Also, where should I search actions documentation? The [Official API](https://angular.github.io/protractor/#/api?view=webdriver.WebDriver.prototype.actions) is _really_ too short.

About [#583](https://github.com/angular/protractor/issues/583), my test is failing both in Chrome and in Firefox. My OS is Ubuntu Gnome 14.04.

Note that I'm 100% sure that my directives work fine. I checked with a couple of demo apps and with several unit-tests.

**Comment by EvanBurbidge** [comment] 2016-01-21 09:19
@marcoliceti  did you ever figure this out currently reading through trying to figure out how to drag and drop an element and cannot get it to work for me! My code is pretty much the same but cannot find a way to get it working.

**Comment by marcoliceti** [comment] 2016-01-21 14:14
@EvanBurbidge: nope :-/

In the end I removed Protractor tests from my project, since it's very hard to test non-trivial stuff like drag & drop and it's also hard to get help, since it's usually not clear if issues are related to Protractor itself or to Selenium.

**Comment by pidupuis** [comment] 2016-02-29 16:12
That's a shame, this is an important feature...

**Comment by krasevych** [comment] 2016-07-15 16:56
I have the same problem(

**Comment by binhvtle** [comment] 2018-08-01 02:02
I got the same issue. I saw the content of the page has been "selected when clicking the mouse down, hold and move". Is there any solution for this case.
