### ISSUE TITLE
getCurrentUrl() protractor tests failing on Internet Explorer 11 (latest)

### ISSUE THREAD

**Issue by elgalu** [angular/protractor#778] opened 2014-05-06 01:38 UTC
I added IE11 to `/spec/multiConf.js` and I could confirm an IE issue when testing AJAX-changed urls:

```
Failures:

  1) protractor library should allow a mix of using protractor and using the driver directly
   Message:
     Expected 'http://localhost:8000/index.html' to equal 'http://localhost:8000/index.html#/form'.
   Stacktrace:
     Error: Failed expectation
    at null.<anonymous> (/usr/local/lib/node_modules/protractor/spec/basic/lib_spec.js:36:11)

  2) protractor library should allow a mix of using protractor and using the driver directly
   Message:
     Expected 'http://localhost:8000/index.html' to equal 'http://localhost:8000/index.html#/repeater'.
   Stacktrace:
     Error: Failed expectation
    at null.<anonymous> (/usr/local/lib/node_modules/protractor/spec/basic/lib_spec.js:40:11)

Finished in 7.078 seconds
10 tests, 23 assertions, 2 failures
```

To recreate just run `npm test` agains IE11

The tests that fails is `it('should allow a mix of using protractor and using the driver directly'` at `/spec/basic/lib_spec.js`

I could also recreate on TravisCI - SauceLabs during a PR:
https://travis-ci.org/angular/protractor/builds/24499725#L764

**Comment by juliemr** [comment] 2016-07-13 20:46
@sjelin can you confirm whether this is still an issue?

**Comment by sjelin** [comment] 2016-12-21 13:40
@cnishina windows

**Comment by cnishina** [comment] 2016-12-23 00:37
Closing this as not reproducible. Test steps to reproduce:

- Replace Firefox for Internet Explorer in spec/multiConf.js on the master branch. 
- Internet explorer version 11.576.14393.0
- Using selenium standalone server 2.53.1, chromedriver 2.26 and IEDriver 32-bit version 2.53.1
- Ran test 10 times. Did not see this error.

**Closed by cnishina** 2016-12-23 00:37 UTC
Labels: browser: IE, fixit: untriaged, OS: windows, type: external bug needs to be filed

**Comment by abdulmoizeng** [comment] 2018-01-11 19:47
Hi @cnishina @juliemr 
I am still facing this issue on following versions
- IE 10
- IE driver 64 bit ( 3.8.0 recommended version : http://www.seleniumhq.org/download/)

same issue on browser stack IE 10 as well, however It works fine on IE 11.

**Comment by wswebcreation** [comment] 2018-01-13 06:33
@abdulmoizeng 

Protractor will never support / fix this because the browser is not supported by Microsoft since 2016. It's for all versions of IE (https://venturebeat.com/2016/01/12/microsoft-ends-support-for-ie8-ie9-ie10-and-windows-8/)
