### ISSUE TITLE
Can't run protractor tests on Jenkins

### ISSUE THREAD

**Issue by clipsett** [angular/protractor#3385] opened 2016-07-18 20:16 UTC
Bug report
---

- Node Version: `4.4.0`
- Protractor Version: `4.0.0`
- Browser(s): `phantomjs`
- Operating System and Version `Windows 10 and Linux`
- Configuration file: 
exports.config = {

  getPageTimeout: 5000,

  specs: ['../tests/login_t.js'],

  framework: 'jasmine',

  rootElement: '.iASK',

  jasmineNodeOpts: {
      showColors: true,
      print: function() {}
  },

  capabilities: {
        'browserName': 'phantomjs',
  },

  resultJsonOutputFile: 'student/configuration/testResults.json',

  onPrepare: function() {
      var SpecReporter = require('jasmine-spec-reporter');
      // add jasmine spec reporter
      jasmine.getEnv().addReporter(new SpecReporter({displayStacktrace: 'all'}));
  }
};
- Test file:
describe('Login page', function() {
  it('should have a title', function() {
    browser.get('http://localhost:5000/student');

    expect(browser.getTitle()).toEqual('Login');
  });
});

- Output:
[15:04:26] I/local - Starting selenium standalone server...
[15:04:26] I/launcher - Running 1 instances of WebDriver
[15:04:29] I/local - Selenium standalone server started at http://10.1.1.82:59698/wd/hub
[15:04:29] E/launcher - "process.on('uncaughtException'" error, see launcher
[15:04:29] E/launcher - Process exited with error code 199

- I run http-server -p 5000 to serve my files on port 5000. Then I run the test with protractor conf.js, and get the error above, error code 199.

- localhost:5000/student

Feature Request
---

- Reasons for adopting new feature
- Is this a breaking change? (How will this affect existing functionality)

**Comment by cnishina** [comment] 2016-07-18 22:23
Closing this since it appears to possibly be a support question on how to set up Jenkins to run Protractor tests. After reading the issue, I cannot tell if the issue is the output, a feature request, or a setup question. Please look at the CHANGELOG.md for more information on breaking changes.

In addition, there is already an issue created for the `E/launcher` log message. This would be a duplicate, please see: 
https://github.com/angular/protractor/issues/3384

for more information.

**Closed** 2016-07-18 22:23 UTC
