### ISSUE TITLE
1.4.0 does not seem to work with PhantomJS

### ISSUE THREAD

**Issue by gweax** [angular/protractor#1512] opened 2014-11-10 08:06 UTC
I know, PhantomJS is not officially supported by Protractor, but since everything worked in 1.3.1 I decided to report this issue nonetheless. Feel free to close it as invalid (a short notice on the browser-setup page of the docs would be nice, though).

My protractor tests started to fail with 1.4.0 with this stacktrace:
```
Starting selenium standalone server...
Selenium standalone server started at http://172.31.195.6:53427/wd/hub
[launcher] Error: UnknownError: org.openqa.selenium.browserlaunchers.Proxies
    at new bot.Error (/Users/matthias/workspace/my-app/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:113:18)
    at Object.bot.response.checkResponse (/Users/matthias/workspace/my-app/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/response.js:106:9)
    at /Users/matthias/workspace/my-app/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:152:24
    at /Users/matthias/workspace/my-app/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1582:15
    at webdriver.promise.ControlFlow.runInNewFrame_ (/Users/matthias/workspace/my-app/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
    at notify (/Users/matthias/workspace/my-app/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:465:12)
    at notifyAll (/Users/matthias/workspace/my-app/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:442:7)
    at resolve (/Users/matthias/workspace/my-app/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:420:7)
    at fulfill (/Users/matthias/workspace/my-app/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:535:5)
    at /Users/matthias/workspace/my-app/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1582:15
==== async task ====
WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (/Users/matthias/workspace/my-app/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:149:22)
    at Function.webdriver.WebDriver.createSession (/Users/matthias/workspace/my-app/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:123:30)
    at Builder.build (/Users/matthias/workspace/my-app/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/builder.js:294:22)
    at LocalDriverProvider.getDriver (/Users/matthias/workspace/my-app/node_modules/grunt-protractor-runner/node_modules/protractor/lib/driverProviders/local.js:121:9)
    at /Users/matthias/workspace/my-app/node_modules/grunt-protractor-runner/node_modules/protractor/lib/runner.js:222:41
    at _fulfilled (/Users/matthias/workspace/my-app/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/Users/matthias/workspace/my-app/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/Users/matthias/workspace/my-app/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/q/q.js:759:13)
    at /Users/matthias/workspace/my-app/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/q/q.js:573:44
```
I use grunt-protractor-runner, as you can see. My e2e.conf.js looks like that:
```
exports.config = {
    "capabilities": {
        "browserName": "phantomjs",
        "phantomjs.binary.path": require("phantomjs").path,
        "phantomjs.ghostdriver.cli.args": ["--loglevel=DEBUG"]
    },
    "specs": [
        "e2e/**/*.js"
    ]
};
```

When using Chrome as a Browser, everything works fine.

**Comment by ehlerskon** [comment] 2015-01-07 11:39
+1

@laurelnaiad thanks for this hack, works fine for me!

**Comment by senayar** [comment] 2015-01-28 10:47
You can download last JAR Selenium version here : http://www.seleniumhq.org/download/ and follow the instruction here : https://github.com/detro/ghostdriver#register-ghostdriver-with-a-selenium-grid-hub

Only way I found to use phantomJS with the last Selenium version

**Comment by juliemr** [comment] 2015-10-01 00:07
I'm aggressively closing issues that we are unable to reproduce, are support issues specific to one test, or deal with integrations with other projects that we don't directly support. If you feel you have a question, please see https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions. If you still have a bug report or feature request, please open a new issue. Thank you!

**Closed by juliemr** 2015-10-01 00:07 UTC
Labels: browser: phantomjs, type: external bug
