### ISSUE TITLE
map() gives FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

### ISSUE THREAD

**Issue by segg3r** [angular/protractor#2789] opened 2015-12-18 17:43 UTC
Hi. Happens from huge upgrade to 3.0.0 from 1.8.0, that we previously used.

Before i had such code:

```javascript
return element(by.css('.br-widget-content .highcharts-container')).all(by.css('.highcharts-series')).map(function(elm, index) {
  return new Pie(elm);
});
```
, which now seems to produce memory leak and gives FATAL ERROR: CALL_AND_RETRY_LAST in the end.

Workaround is just to manually map elements:

```javascript
.then(function(elms) {
	return elms.map(function(elm) {
		return new Pie(elm);
	});
})
```

I use Node.js 4.2.3.

**Comment by NickTomlin** [comment] 2015-12-18 23:57
Interesting. What is `Pie` here? Do you see this behavior when returning something else from the map?

**Comment by segg3r** [comment] 2015-12-19 09:06
Hi. Pie is basically a wrapper around element, which has further mapping methods (i had to "unmap" them all) for getting inner elements and their attributes. 

```javascript
var Pie = function(el) {
	var PieSector = $action('highchart.PieSector');
	
	this.el = el;
	
	this.getPieSectors = function() {
		return this.el.all(by.css('path')).map(function(elm, index) {
			return new PieSector(elm, function() {
				return el.all(by.css('path')).get(index);
			});
		});
	};
	
	this.getFirstPieSector = function () {
		return new PieSector(this.el.all(by.css('path')).get(0));
	};
};
```
and PieSector does the same...
etc., etc.

I figured out from ElementArrayFinder.prototype.map, that it uses webdriver.promise.fullyResolved. So it's possible, that there are some cyclical references in all that huge chain of wrappers that i have. Apparently it's bug in my local code.
For now i think i can live with just simple map workaround.

**Comment by segg3r** [comment] 2015-12-19 09:24
```javascript
this.el = el;
```
as it turned out, this was the problem. Which does not make much sense to me, but fixable.

**Comment by sjelin** [comment] 2015-12-21 20:44
Simpler reproduction:

```js
element.all(by.css('div')).map(function(el, index) {
    return el;
});
```

**Comment by juliemr** [comment] 2016-01-14 01:56
I think this is probably the same root problem as #2227 

Closing as a duplicate of that so we can concentrate work there.

**Closed by juliemr** 2016-01-14 01:56 UTC
Labels: status: needs investigation, type: bug
