### ISSUE TITLE
Auto starting selenium server does not work with VPN

### ISSUE THREAD

**Issue by jlin412** [angular/protractor#2613] opened 2015-10-16 13:24 UTC
If we remove seleniumAddress in conf file, it should automatically start selenium server.
However, I have been noticing that it doesn't work with vpn.  It stuck at starting server and it eventually time out.  Does anyone experience the same?

**Comment by NickTomlin** [comment] 2015-10-16 13:56
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by jlin412** [comment] 2015-10-16 14:14
I don't think so.  It just start failing after introducing automatic
selenium server start.  I believe that it is a valid bug.

**Comment by NickTomlin** [comment] 2015-10-16 14:26
There's nothing reproducible or actionable in your issue (I use protractor and selenium behind a VPN without problems). I think these sorts of things are best handled outside of the issues queue until we can actually isolate what the issue is (I use protractor and selenium server behind a VPN without issue). Please feel free to update your issue with more details and an isolated problem, but try to keep debugging/discovery questions in more productive channels. Keeping the issue queue clean makes it easier to actually solve problems once we know what they are. 

Hopefully that makes sense. I don't mean to come off as dismissive or harsh; I'm just trying to get you help in the most productive way :)

**Comment by rbirbeck** [comment] 2015-10-19 16:25
FWIW, I am experiencing the same issue - I'd happily help try and identify the underlying problem (in the appropriate channel of course :wink: ).

**Comment by szikszail** [comment] 2015-10-19 17:27
I can use protractor, with vpn too. It seems to me that it could be some wrong configuration in your vpn somewhere or in your firewall.

**Comment by juliemr** [comment] 2015-10-20 07:22
As Nick said, we're able to run on vpn fine, we can't reproduce this to investigate. I'm going to close this particular issue, but @rbirbeck @jlin412 if you have a set of steps we can use to repro on a particular VPN, please go ahead and open a new issue listing those. Thanks!!

**Closed by juliemr** 2015-10-20 07:22 UTC
Labels: status: needs investigation

**Comment by marcstober** [comment] 2016-09-29 12:30
I know this is a closed issue, and I'll repost this elsewhere if needed, but I'm having this issue as well. The issue is that protractor is using a VPN-assigned IP address to connect to the Selenium server (e.g, 172.x.xx) when automatically started in standalone mode. For whatever reason the server is accessible as "localhost" or "127.0.0.1" but not using the IP address assigned by the VPN adapter. It also responds to local NAT address (e.g., 192.168.x.x). 

It would be nice if you could specify in the protractor config an address for that standalone server. (Ideally you would fix your VPN issue, but that might not always be feasible.) For example, by adding a "standalone: true" which would let you specify a seleniumServerAddress even in standalone mode. An added benefit is that it could be make the config files more clear that you are in standalone or not, rather than being inferred from other properties being set:

{
  standalone: true,
  seleniumServerAddress: 'http://localhost:4444/wd/hub'
}

**Comment by marcstober** [comment] 2016-09-29 15:49
To follow up on my previous comment (for anyone who finds this issue searching for "protractor vpn issue"), you can add `localSeleniumStandaloneOpts` to the config as follows to get it to work:

    exports.config = {
        localSeleniumStandaloneOpts: {
            loopback: true
        },
    }

See also this change to Selenium which was made to help deal with this issue: https://github.com/SeleniumHQ/selenium/issues/1066
