### ISSUE TITLE
"restartBrowserBetweenEachTest: true" with jasmine 2 restart browser extra one more time 

### ISSUE THREAD

**Issue by Saurabh06** [angular/protractor#3280] opened 2016-06-18 07:25 UTC
When i am using "restartBrowserBetweenEachTest: true" in conf with jasmine 2, having two "it" in spec then it restart the browser 3 times but i want 2 time only as their are 2 "it". how to resolve that problem.??

**Comment by NickTomlin** [comment] 2016-06-18 12:50
Hi there,

Please follow the [Issue Template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) when opening new issues. Otherwise it's unclear what the issue is and how we can actually help.

I'm going to close this issue, please re-open a new one following the issue template linked above. Thanks! 😄

**Closed by NickTomlin** 2016-06-18 12:50 UTC
