### ISSUE TITLE
not reporting line number in test file

### ISSUE THREAD

**Issue by cjroth** [angular/protractor#1935] opened 2015-03-17 22:21 UTC
I'm getting a lot of `No element found...` errors in my tests that don't have the line number in my tests where they are failing. They only show the line numbers from jasmine, protractor, and selenium.

```
      - Failed: No element found using locator: By.cssSelector(".user-role")
          at /Users/chris/f/fedora/node_modules/protractor/node_modules/jasminewd2/index.js:104:16
          at /Users/chris/f/fedora/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1582:15
          at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (/Users/chris/f/fedora/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
          at notify (/Users/chris/f/fedora/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:465:12)
          at notifyAll (/Users/chris/f/fedora/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:442:7)
          at resolve (/Users/chris/f/fedora/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:420:7)
          at reject (/Users/chris/f/fedora/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:545:5)
          at /Users/chris/f/fedora/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1582:15
          at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (/Users/chris/f/fedora/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
          at notify (/Users/chris/f/fedora/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:465:12)
          at notifyAll (/Users/chris/f/fedora/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:442:7)
          at resolve (/Users/chris/f/fedora/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:420:7)
          at [object Object].reject (/Users/chris/f/fedora/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:545:5)
          at /Users/chris/f/fedora/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1529:10
          at newFrame.onAbort (/Users/chris/f/fedora/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1679:7)
          at [object Object].webdriver.promise.Frame_.notify_ (/Users/chris/f/fedora/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1914:5)
          at [object Object]._onTimeout (/Users/chris/f/fedora/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1887:13)
```

**Comment by juliemr** [comment] 2015-03-17 23:19
Duplicate of https://github.com/angular/protractor/issues/1768

**Closed by juliemr** 2015-03-17 23:19 UTC
