### ISSUE TITLE
Cannot use 'should' assertion style with mocha / chai / chai-as-promised

### ISSUE THREAD

**Issue by phuvo** [angular/protractor#633] opened 2014-03-22 10:48 UTC
I tried to use `myElement.getText().should.eventually.equal("foo")` as in the [chai-as-promised manual](http://chaijs.com/plugins/chai-as-promised), but got `TypeError: Cannot read property 'eventually' of undefined`. This is not a problem with `chai-as-promised` either, because `myElement.getText().should.equal("foo")` failed with a similar error. Using `expect` works as expected, though.

``` js
var chai = require('chai');
chai.use(require('chai-as-promised'));
var should = chai.should();

describe('Home', function() {
  it('should say hello', function() {
    browser.get('/');
    $('h1').getText().should.eventually.equal('Hello, world');
  });
});
```

**Comment by vladei** [comment] 2015-03-31 12:36
@domenic I get the following error when i'm trying to use the code. Can you plz help ? : )

TypeError: Property description must be an object: undefined
   Stacktrace:
     TypeError: Property description must be an object: undefined
    at Function.defineProperty (native)
    at Object.<anonymous> (/Users/deauth/Projects/node/100mentors/webapp/e2e/main/main.spec.js:16:8)
    at require (module.js:380:17)

**Comment by jodytate** [comment] 2015-05-22 02:50
@vladei I received a similar error until I confirmed the following as the correct order: 

    var chai = require('chai');
    var should = chai.should();
    var chaiAsPromised = require('chai-as-promised');
    chai.use(chaiAsPromised);

    Object.defineProperty(
      protractor.promise.Promise.prototype,
      'should',
      Object.getOwnPropertyDescriptor(Object.prototype, 'should')
    );

**Comment by scottohara** [comment] 2016-07-26 00:49
Note that as of protractor 4.0.0, the workaround above no longer seems to be required (partly due to https://github.com/angular/protractor/pull/3214).

Protractor no longer exposes a Promise object of it's own, and instead defers (no pun intended) to the `ManagedPromise` object provided by `selenium-webdriver`.

(Note: if you need to work directly with Promises in protractor 4.0.0, such as `protractor.promise.all()`, you now need to [use the WebDriver promise directly](http://stackoverflow.com/questions/38381292/failed-cannot-read-property-all-of-undefined)), e.g.

```javascript
var promise = require('selenium-webdriver').promise;
promise.all([promise1, promise2, promise3])
```

It would seem that the WebDriver promise inherits from `Object.prototype`, so initializing `chai` / `chai-as-promised` is enough to bestow a `should` property onto the Promise object, e.g.


```javascript
// protractor.conf.js

onPrepare() {
  // Load chai assertions
  const chai = require("chai");

  // Load chai-as-promised support
  chai.use(require("chai-as-promised"));

  // Initialise should API (attaches as a property on Object)
  chai.should();
}
```

**Comment by juliemr** [comment] 2016-12-22 00:20
Sweet, closing as fixed.

**Closed by juliemr** 2016-12-22 00:20 UTC
Labels: fixit: untriaged, framework: mocha, PRs plz!
