### ISSUE TITLE
IE - Browser launched URL not loading

### ISSUE THREAD

**Issue by krthknan** [angular/protractor#5362] opened 2019-11-25 10:00 UTC
No error message in the console. The browser remains open until manually stop the execution.
Protractor Version: 5.4.2
Webdriver-manager version: 12.1.6
Node version: 10.13.0
I have tried the below IE driver versions: IEDriverServer3.150.1, IEDriverServer3.150.0, IEDriverServer3.141.59
Selenium server version: 3.141.59

Kindly help me.

**Comment by IgorSasovets** [comment] 2019-11-29 10:23
Hi, @krthknan ! Look at these issues: https://github.com/angular/protractor/issues/5314 , https://github.com/angular/protractor/issues/4725

**Comment by Harsha509** [comment] 2019-12-02 05:36
Hi @krthknan , i think the issue is resolved in your post mentioned in selenium https://github.com/SeleniumHQ/selenium/issues/7811

**Closed** 2019-12-04 08:49 UTC

**Comment by ashishgoel88** [comment] 2021-03-29 07:21
I am facing similar issue on Firefox as well. Can you please suggest me how did you make it work on Firefox?
On chrome, everything is working fine.
