### ISSUE TITLE
Protractor not working with Firefox using Selenium standalone server.  Works if using directConnect: true

### ISSUE THREAD

**Issue by tommyz0123** [angular/protractor#3150] opened 2016-04-21 20:43 UTC
Bug report
---

- Node Version: `v4.1.2`
- Protractor Version: `2.4.0`
- Browser(s): `Firefox 44, 45`
- Operating System and Version `Mac 10.11.4`
- Your protractor configuration file

`exports.config = {
  seleniumAddress: 'http://localhost:4444/wd/hub',
  specs: ['tests/*.js'],
  baseUrl: 'http://localhost/',
  framework: 'jasmine2',
  //directConnect: true,

  capabilities: {
    browserName: 'firefox'
  },
...
`

- A relevant example test: Any simple test that opens browser and navigates to a web page.
- Output from running the test: Firefox opens, but it doesn't load page.  Eventually, it will error out
- Steps to reproduce the bug:

1. start selenium stand alone server
2. run test
3. browser will open, but doesn't navigate to page
4. eventually errors out.

- The URL you are running your tests against (if relevant)

Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver

/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:108
  var template = new Error(this.message);
                 ^
UnknownError: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
:1452825183000,"updateDate":1452825183000,"applyBackgroundUpdates":1,"skinnable":true,"size":8164,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"44.0","maxVersion":"44.0"}],"targetPlatforms":[]}
1461270371565	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1461270371565	addons.xpi	DEBUG	Updating XPIState for {"id":"web2pdfextension@web2pdf.adobedotcom","syncGUID":"pK2loL5dv2Vj","location":"app-system-local","version":"15","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":"chrome://web2pdfextension/skin/C_AdobeLogo_48x48.png","icon64URL":"chrome://web2pdfextension/skin/C_AdobeLogo_64x64.png","defaultLocale":{"name":"Adobe Acrobat DC - Create PDF","description":"Converts a web page to PDF","creator":"Adobe Systems Incorporated","homepageURL":"http://www.adobe.com/"},"visible":true,"active":false,"userDisabled":true,"appDisabled":false,"descriptor":"/Library/Application Support/Mozilla/Extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/web2pdfextension@web2pdf.adobedotcom","installDate":1449871153000,"updateDate":1449871153000,"applyBackgroundUpdates":1,"bootstrap":false,"size":167926,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"4.0","maxVersion":"46.0"}],"targetPlatforms":[],"multiprocessCompatible":false,"signedState":2}
1461270371566	DeferredSave.extensions.json	DEBUG	Save changes
1461270371566	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1461270371566	addons.xpi-utils	DEBUG	Updating add-on states
1461270371566	addons.xpi-utils	DEBUG	Writing add-ons list
1461270371573	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1461270371573	addons.manager	DEBUG	Provider finished startup: XPIProvider
1461270371573	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1461270371573	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1461270371574	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1461270371574	addons.manager	DEBUG	Starting provider: GMPProvider
1461270371577	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1461270371577	addons.manager	DEBUG	Provider finished startup: GMPProvider
1461270371577	addons.manager	DEBUG	Starting provider: PluginProvider
1461270371578	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1461270371578	addons.manager	DEBUG	Provider finished startup: PluginProvider
1461270371578	addons.manager	DEBUG	Completed startup sequence
1461270371764	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1461270371764	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1461270371765	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1461270371902	DeferredSave.extensions.json	DEBUG	Write succeeded
1461270371902	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1461270371902	DeferredSave.extensions.json	DEBUG	Starting timer
1461270371904	addons.repository	DEBUG	No addons.json found.
1461270371904	DeferredSave.addons.json	DEBUG	Save changes
1461270371906	DeferredSave.addons.json	DEBUG	Starting timer
1461270371920	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1461270371920	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1461270371920	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1461270371939	DeferredSave.extensions.json	DEBUG	Starting write
1461270371965	DeferredSave.addons.json	DEBUG	Starting write
1461270371968	DeferredSave.extensions.json	DEBUG	Write succeeded
1461270371978	DeferredSave.addons.json	DEBUG	Write succeeded

    at new bot.Error (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:108:18)
    at Object.bot.response.checkResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/response.js:109:9)
    at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:160:24
    at [object Object].promise.ControlFlow.runInFrame_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1857:20)
    at [object Object].goog.defineClass.notify (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2448:25)
    at [object Object].promise.Promise.notify_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:564:12)
    at Array.forEach (native)
    at [object Object].promise.Promise.notifyAll_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:553:15)
    at goog.async.run.processWorkQueue (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/run.js:130:15)
    at process._tickCallback (node.js:357:9)
From: Task: WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:157:22)
    at Function.webdriver.WebDriver.createSession (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:131:30)
    at [object Object].Builder.build (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/builder.js:445:22)
    at [object Object].DriverProvider.getNewDriver (/usr/local/lib/node_modules/protractor/lib/driverProviders/driverProvider.js:38:7)
    at [object Object].Runner.createBrowser (/usr/local/lib/node_modules/protractor/lib/runner.js:180:37)
    at /usr/local/lib/node_modules/protractor/lib/runner.js:256:21
    at _fulfilled (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:759:13)
    at /usr/local/lib/node_modules/protractor/node_modules/q/q.js:525:49
[launcher] Process exited with error code 1

Feature Request
---

- Reasons for adopting new feature
- Is this a breaking change? (How will this affect existing functionality)
cannot run using selenium server.

**Comment by spengilley** [comment] 2016-04-22 10:11
I can second this. Having exactly the same problem.

**Comment by juliemr** [comment] 2016-04-22 22:12
Cannot reproduce with FireFox 45.0.1 and the same OS.

What version of the selenium server are you running? Can you make sure it's up to date?

**Comment by NickTomlin** [comment] 2016-04-22 22:50
@spengilley @tommyz0123 are you both using Protractor `2.x`? I haven't been able to reproduce this using `3.x`

**Comment by tommyz0123** [comment] 2016-04-23 01:28
@NickTomlin Yes, I'm using 2.4.0.  I start the selenium server using "webdriver-manager start".  One thing I tried that works is to start it from my config by setting "seleniumServerJar".  But, I need to run grid, so this won't help.

**Comment by tommyz0123** [comment] 2016-04-23 01:29
@NickTomlin how do you update to 3.x?  I ran "webdriver-manager update" and it says i'm already up-to-date.

**Comment by NickTomlin** [comment] 2016-04-23 21:37
@tommyz0123 You can upgrade protractor by editing your project's `package.json` or globally via `npm install -g protractor@latest`

**Comment by NickTomlin** [comment] 2016-04-25 23:03
I'm going to go ahead and close this since there hasn't been any activity and a version upgrade should hopefully sort things.

**Closed by NickTomlin** 2016-04-25 23:03 UTC
Labels: browser: firefox, status: needs more info

**Comment by tommyz0123** [comment] 2016-04-25 23:15
yes. upgrading to 3.x fixed the problem for me.

**Comment by spengilley** [comment] 2016-05-25 12:57
Unfortunately upgrading to version 3 isn't an option for us. We are using Angular 1.2.29 to support IE8. Could this not be patched in version 2?

**Comment by alexfromapex** [comment] 2017-01-03 22:13
This is happening to me on protractor 3.10.9 even after running `webdriver-manager update`

**Comment by karolmie1** [comment] 2017-01-16 12:03
I nave this problem on protractor 5

**Comment by NickTomlin** [comment] 2017-01-16 18:18
@karolmie1 @alexfromapex 

Could you open separate issues? Thanks!

**Comment by makwanaparth94** [comment] 2017-05-08 13:02
Protractor Version : 5.1.1
Firefox Version : 45.x

Not able to run protractor script on firefox version
What are the solution?

**Comment by wswebcreation** [comment] 2017-05-08 13:08
@makwanaparth94 , why use FireFox 45?
Secondly, as far as I know FireFox 45 isn't supported by Protractor 5.1.1 with Selenium 3. Can't you upgrade to 53?

**Comment by heathkit** [comment] 2017-05-08 18:22
Protractor 5.x requires Selenium 3 and Firefox 52 or greater. The changes made to Firefox's automation prevent us from easily support old and new Firefox in the same Protractor release.

If you need to test on Firefox 45, you're stuck with Protractor 4.x

**Comment by makwanaparth94** [comment] 2017-05-29 13:10
@wswebcreation I updated it with latest version and now it's running
