### ISSUE TITLE
Firefox screenshots not respecting window dimensions. 

### ISSUE THREAD

**Issue by jamessimo** [angular/protractor#2637] opened 2015-10-27 08:45 UTC
Hey guys, I cant seem to find any existing issues like this on github / stackoverflow / googlecode

I set the screen width height too 1366 X 768  and when I take a screenshot with **Chrome** the outputted image is **1366px x 768px** which is expected. 

When I take a screenshot with the exact same spec.js script on **Firefox** the screenshot is **1410px X 10228px**, it seems that screenshot captures everything on the DOM regardless of window size/dimension where Chrome only captures whats on the window.

Watching the test run the window dimensions seem fine (1366px x 768px) , the page does have overflow: scroll set.

Firefox version is 41.0.2

**Comment by NickTomlin** [comment] 2015-10-27 13:21
I believe this is Selenium issue, but I can definitely reproduce. Using `takeScreenshot` results in a viewport sized screenshot for chrome but a full page sized screenshot for firefox.

```
it('takes a screenshot', function () {
  var width = 1024;
  var height = 768;
  browser.driver.manage().window().setSize(width, height);
  browser.get('/');

  browser.takeScreenshot().then(function(png) {
    var stream = require('fs').createWriteStream('screenshot.png');
    stream.write(new Buffer(png, 'base64'));
    stream.end();
  });
});
```

I'm not sure if this is a regression in the way that Firefox Handles `takeScreenshot` or some other issue. We should do some investigation and raise an issue on the Selenium project.

**Comment by sjelin** [comment] 2015-10-27 15:51
Duplicate of https://github.com/angular/protractor/issues/2400

**Closed by sjelin** 2015-10-27 15:51 UTC
