### ISSUE TITLE
webdriver-manager  update --ie32 is not zipping the correct ie driver in selenium folder

### ISSUE THREAD

**Issue by vivekbrahmadandi** [angular/protractor#3050] opened 2016-03-22 14:13 UTC
http://grab.by/OXjU

after running the command webdriver-manager update --ie32 , it is download the driver but 
while it is unzipping it is creating as 0 File type .

Attached the url of screenshot

**Comment by cnishina** [comment] 2016-03-22 17:57
It looks like webdriver-manager failed to download the iedriver 32-bit edition. The file that currently exist is probably not the complete download but webdriver-update will currently skip the download. The quick solution is to do a `webdriver-manager clean` to remove the files and then try `webdriver-manager update --ie32` again.

Feature request added to webdriver-manager (work in progress): https://github.com/cnishina/webdriver-manager/issues/7

**Comment by cnishina** [comment] 2016-03-23 13:59
The instructions above should resolve your current issue. The issue is tracked in a different repository. Closing this issue.

**Closed by cnishina** 2016-03-23 13:59 UTC
Labels: status: needs investigation
