### ISSUE TITLE
Protractor test does not work for Angular 2 (version 2.4.6).

### ISSUE THREAD

**Issue by uslerss** [angular/protractor#4086] opened 2017-02-10 14:44 UTC
Nice community. 
Thanks for the quick response.

**Comment by jan-molak** [comment] 2017-02-13 15:59
Same problem with [Angular Quickstart](https://github.com/angular/quickstart).

Steps to reproduce:
- clone https://github.com/angular/quickstart
- upgrade Protractor to 5.1.1
- run `npm run e2e`
- see `Could not find Angular on page http://localhost:8080/ : retries looking for angular exceeded`

**Comment by NickTomlin** [comment] 2017-02-24 14:03
Hi there,

Please follow the [Issue Template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) when opening new issues. Otherwise it's unclear what the issue is and how we can actually help.

I'm going to close this issue, please re-open a new one following the issue template linked above. Thanks! 😄

**Closed by NickTomlin** 2017-02-24 14:03 UTC
