### ISSUE TITLE
Protractor drag and drop does not happen again on the same element

### ISSUE THREAD

**Issue by anudeep-mj** [angular/protractor#3117] opened 2016-04-12 00:01 UTC
Hi guys, I am running into a problem using the drag and drop functionality. 
So I use the draganddrop function as follows:

`browser.actions().dragAndDrop(element(by.id('widget-icon-0')), template.next(0,0)).mouseUp().perform();  
browser.actions().dragAndDrop(element(by.id('widget-icon-0')), template.next(1,0)).mouseUp().perform();  
browser.actions().dragAndDrop(element(by.id('widget-icon-0')), template.next(1,1)).mouseUp().perform();`

I notice that, the drag and drop works the first and second time but not the third time. I double checked the destination element and it is fine. On investigation, it means, I am not able to drag and drop an already dragged element again.

Is this a known issue ?
## Bug report
- Node Version: `4.2.1`
- Protractor Version: `2.57`
- Browser(s): `Chrome`
- Operating System and Version `Mac OSX El Capitan`
- Your protractor configuration file: 
  `exports.config = {  
  allScriptsTimeout: 11000,  
  specs: [  
              'e2e/multipWidgets.js'  
  ],  
  capabilities: {  
      //'browserName': 'firefox'  
      'browserName': 'chrome'  
  },  
  directConnect: true,  
  // add parameter here
  params: {  
      baseUrl: 'http://localhost:3000/authoring.html',  
      baseUrl2: 'http://www.google.com'  
  },  
  //https://github.com/jasmine/jasmine/issues/704 to enable support for beforeAll and afterAll  
  framework: 'jasmine2',  
  jasmineNodeOpts: {  
      defaultTimeoutInterval: 30000  
  }  
  };`
- Output from running the test: The test passes without any errors

Feature request: Dragging and dropping an already dragged element.

**Comment by juliemr** [comment] 2016-07-14 20:19
Almost certainly an issue w/ ChromeDriver, we should make a repro and file a bug.

**Comment by mgiambalvo** [comment] 2016-12-19 23:47
Likely related to #583

**Comment by mgiambalvo** [comment] 2016-12-20 01:08
Closing this as a duplicate of #583. This is still an issue with chromedriver.

**Closed by mgiambalvo** 2016-12-20 01:08 UTC
Labels: status: duplicate, status: external bug filed, status: needs investigation

**Comment by symmetriccurve** [comment] 2017-04-28 04:13
@anudeep-mj, I'm trying to run a basic drag and drop. Please can you throw some light on what exactly "template" does ?

**Comment by anudeep-mj** [comment] 2017-04-28 05:59
Oh that was some custom code from my end. It has nothing to do with protractor unfortunately :(

but i did get the drag and drop working with:
browser.actions().dragAndDrop(css-id1, css-id2).perform()

**Comment by symmetriccurve** [comment] 2017-04-28 06:03
Can you please help me on a simple use case. I wouldn't take much of your time. Please let me know so I can send you a meeting link. Please
