### ISSUE TITLE
Test failing while running for CI in Codeship

### ISSUE THREAD

**Issue by rossimoze** [angular/protractor#1950] opened 2015-03-20 11:52 UTC
## Desc

The same tests that are supposed to pass on localhost, are failing while running on Condeship.

It's a known bug?

**Comment by smahalingam** [comment] 2015-03-20 11:59
Can you paster your failure log here please ?. Is it failing due to element not clickable ?

**Comment by juliemr** [comment] 2015-03-23 17:30
We don't have any tests running on with Codeship, so it's hard to say. Do you think that there is a problem with Protractor here? It would be great if you could add some more info, and if you have a reason to suspect that the issue is Protractor and not Codeship.

**Comment by azangru** [comment] 2015-03-25 22:31
We run e2e tests with Protractor on Codeship on a regular basis, and I can confirm that there have been problems lately. Moreover, Protractor has been behaving weirdly on our local machines as well. The locators, quite unpredictably, have started to miss page elements we were testing for.

The problems have started to appear about a week ago; same time Protractor v.2.0.0 was released. When we downgraded to Protractor v.1.8.0, the problems disappeared, both on Codeship and on our local machines. Perhaps, the OP's problem comes from the mismatch between Protractor versions on Codeship and on localhost; localhost using the older and more reliable version of Protractor and Codeship using v.2.0.0 every time it creates a build.

**Comment by juliemr** [comment] 2015-03-25 22:42
@azangru if you can reliably reproduce any of these issues with 2.0, we'd love to see them. Our own locator tests have been working perfectly with 2.0, and we did not make any big changes that should affect how locating elements works, so it may be due to an issue with the new versions of our dependencies (selenium-webdriver).

**Comment by azangru** [comment] 2015-03-25 23:36
I can't specifically create a minimal failing example, but here is one of the longest-standing and most consistent issues we were having:

Here’s a piece of html mixed with Angular directives. It is a "Name" section of a form, with an "Add new" button below.

```
            <div class="panel-col panel-col-white col-md-12 panel-name">
                <h3>Name</h3>
                <div class="field-block" ng-repeat="name in data.name">
                    <patient-fhir-name ng-model="name"></patient-fhir-name>
                </div>
                <div class="field-block row">
                    <button class="btn btn-lg btn-primary" type="button" ng-click="add('name')">Add more</button>
                </div>
            </div>
```

The test checks that clicking the "Add new" button will add fields for another name. Here’s the Cucumber step that was failing:

`When I click on the "Add more" button in the "name" section`

And the step definition:

```
    this.When(/^I click on the "([^"]*)" button in the "([^"]*)" section$/, function(text, section, callback){
        browser.waitForAngular().then(function(){
            return element.all(by.repeater(section + " in data."+section));
        }).then(function(items){
            sectionsLength = items.length;
            return element(by.cssContainingText(".panel-"+section+" .btn", text)).click();
        }).then(callback, callback.fail);
    });
```

And the error when using Protractor v.2.0.0:

```
When I click on the "Add more" button in the "name" section # tests/e2e/demographics.feature:10
Then I should get one more field for "name"                 # tests/e2e/demographics.feature:11
NoSuchElementError: No element found using locator: by.cssContainingText(".panel-name .btn", "Add more")
```

On v.1.8.0, the test passes without a hiccup.

**Comment by juliemr** [comment] 2015-04-10 22:33
Unable to reproduce, and I don't think that we can test against codeship issues, so I'm closing this for now. Please open a new issue if you have a general, reproducible test case.

**Closed by juliemr** 2015-04-10 22:33 UTC
Labels: needs: more info
