### ISSUE TITLE
error code ELIFECYCLE

### ISSUE THREAD

**Issue by srizvi1** [angular/protractor#1993] opened 2015-03-31 20:15 UTC
I am new and trying to understand why do I get lots of NPM ERR! after the tests have run. Any help would be appreciated. 

npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "protractor"
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! angular-seed@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-seed@0.0.0 protractor script 'protractor e2e-tests/protractor.conf.js'.
npm ERR! This is most likely a problem with the angular-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor e2e-tests/protractor.conf.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-seed
npm ERR! There is likely additional logging output above.

Does anyone know what does ELIFECYCLE mean? 
![screen shot 2015-03-31 at 4 10 52 pm](https://cloud.githubusercontent.com/assets/11632919/6928203/8b60ddda-d7c0-11e4-8050-ebe769d55ec4.png)

![screen shot 2015-03-31 at 4 13 47 pm](https://cloud.githubusercontent.com/assets/11632919/6928281/fee66694-d7c0-11e4-83d9-8dddeedee429.png)

**Comment by juliemr** [comment] 2015-04-02 18:22
Duplicate of https://github.com/angular/angular-seed/issues/254 - this is an issue with angular-seed.

**Closed by juliemr** 2015-04-02 18:22 UTC
