### ISSUE TITLE
Firefox's getAllWindowHandles ignores tabs opened with ctrl-click

### ISSUE THREAD

**Issue by prbaron** [angular/protractor#2715] opened 2015-11-17 11:24 UTC
Hello,
I spotted that `browser.getAllWindowHandles()` does not give the same value on Chrome and Firefox.

Based on this test : 

```
'use strict';

describe('', function () {

  it('', function () {
    browser.sleep(3000);


    var firstLink = Locator.elementByTagName('a');
    browser.getWindowHandle().then(function (handles) {
      console.log('handle', handles); // 1
    });

    // for Windows
    // browser.actions().keyDown(protractor.Key.CONTROL).click(firstLink).keyUp(protractor.Key.CONTROL).perform();
    browser.actions().keyDown(protractor.Key.COMMAND).click(firstLink).keyUp(protractor.Key.COMMAND).perform();

    browser.getAllWindowHandles().then(function (handles) {
      console.log('handles', handles, handles.length); // 2 
      return browser.switchTo().window(handles[1]); 
    })
    .then(function () {
      browser.get('http://juliemr.github.io/protractor-demo/')
    });

    browser.getWindowHandle().then(function (handles) {
      console.log('handle', handles); //3
    });
  });
});
```

I have the following logs for Chrome : 

```
1. CDwindow-C54C22C0-3F83-4114-ABF9-7A5EFD4BB43F
2. Array [
  'CDwindow-C54C22C0-3F83-4114-ABF9-7A5EFD4BB43F',
  'CDwindow-DD5DAC61-DDF4-4880-BCA9-AD3A754C9836' ] 2
3. CDwindow-DD5DAC61-DDF4-4880-BCA9-AD3A754C9836
```

Here is for Firefox : 

```
1. {ca4f411a-a853-e34b-abd3-c9e01bbc56a0}
2. Array [ '{ca4f411a-a853-e34b-abd3-c9e01bbc56a0}' ] 1
```

Then the tests with the message `Failed: null value in entry: name=null`.

**Comment by prbaron** [comment] 2015-12-02 16:52
Hi,

Here is a project to see the problem : https://github.com/prbaron/protractor-demo-tab.

It is working on Chrome, but not on Firefox.

**Comment by juliemr** [comment] 2016-02-09 20:38
Confirmed - this looks like a bug with firefox driver. 

See also http://stackoverflow.com/questions/33874788/getwindowhandles-return-one-window-handle-if-multiple-tabs-are-open-in-single-wi

**Comment by juliemr** [comment] 2016-02-09 20:44
Opened a bug w/ selenium: https://github.com/SeleniumHQ/selenium/issues/1614

**Comment by juliemr** [comment] 2016-02-09 21:01
Selenium issue was closed as working as intended. I'll leave this open and just list it as blocked.

**Comment by juliemr** [comment] 2016-12-22 00:09
I'm going to go ahead and close this since the external bug is filed and I don't think it's providing much value to keep track of it in our repo as well.

**Closed by juliemr** 2016-12-22 00:09 UTC
Labels: browser: firefox, fixit: untriaged, status: external bug filed

**Comment by abhinaba1080** [comment] 2019-11-16 07:51
Adding some expected condition make life easy. 

Here is a method written for retrieving all browser handle title as a string. You can easily tweak the code and make it work for you in any condition. 
 

    /**
       * this method helps to get all window titles
       */
      async getAllRedirectedBrowserWindowTitles() {
        const title: string[] = [];
        await browser.wait(
          async () => {
            return (await browser.getAllWindowHandles()).length >= 2;
          },
          5000,
          `Only one browser handle found. There is no other browser handle to iterate`
        );
        const _windowHandles: string[] = await browser.getAllWindowHandles();
        const _parentHandle: string = _windowHandles[0];
        for (const guid of _windowHandles) {
          if (guid !== _parentHandle) {
            await browser.switchTo().window(guid);
            await browser.wait(
              async () => {
                return (await browser.getTitle()) ? true : false;
              },
              5000,
              `Child browser title not loaded`
            );
            title.push(await browser.getTitle());
            await browser.close();
          }
        }
        await browser.switchTo().window(_parentHandle);
        return title;
      }

Now, you just need to call this method from anywhere in your code:

    await getAllRedirectedBrowserWindowTitles(); //this will return the list of window title
