### ISSUE TITLE
no error thrown when pattern/file not found

### ISSUE THREAD

**Issue by Brandon-C** [angular/protractor#2079] opened 2015-04-22 17:44 UTC
When running a test through grunt, protractor will return a status code of 0 even if the file does not exist. This causes grunt to return a "pass", which is false. We would like protractor to return a 1 if it does not find a spec file, which would give us the appropriate failure message. Is this an intentional design decision?

Here's an example of the console output:
```console
$ grunt --specs=mistake.js
WARNING - pattern /var/lib/jenkins/workspace/mistake.js did not match any files.
[launcher] Running 0 instances of WebDriver
Done, without errors.
Finished: SUCCESS
$ echo $?
0
```
It looks like a warning is logged on line 101 of configParser.js which is where we would ideally throw the appropriate exit error.

```javascript
if (patterns) {
    for (var i = 0; i < patterns.length; ++i) {
      var matches = glob.sync(patterns[i], {cwd: cwd});
      if (!matches.length && !opt_omitWarnings) {
        log.warn('pattern ' + patterns[i] + ' did not match any files.');
      }
      for (var j = 0; j < matches.length; ++j) {
        resolvedFiles.push(path.resolve(cwd, matches[j]));
      }
    }
  }
```

Any suggestions on how to deal with this?

**Comment by juliemr** [comment] 2015-04-22 22:29
This is working as intended, and the same behavior as Karma, Jasmine, and other test runners as far as I know. Nothing failed = success, even if nothing was matched. Is parsing the warning sufficient?

**Comment by juliemr** [comment] 2015-04-27 22:59
I'm going to close this as working as intended.

**Closed by juliemr** 2015-04-27 22:59 UTC
