### ISSUE TITLE
restartBrowserBetweenTests=true does not work properly for cucumber framework

### ISSUE THREAD

**Issue by jlin412** [angular/protractor#1817] opened 2015-02-16 19:27 UTC
I added restartBrowserBetweenTests=true in conf.js.  It will pass the first scenario and the second scenario on I am getting error:

```
      Error: This driver instance does not have a valid session ID (did you call WebDriver.quit()?) and may no longer be used.

      ==== async task ====
      Protractor.waitForAngular()
          at World.<anonymous> (/Users/linj/redbox_spa/redbox_angular/test/e2e/features/time/step_definitions/time_login_steps.js:36:15)
    And I click on 
```
I am trying it manually in the hook.js rather setting restartBrowserBetweenTests=true using the following code: 
```
    var browser2 = browser.forkNewDriverInstance();
  
    browser.driver.quit().then(function() {
      browser = browser2;
    });
```
It is the same result.

**Comment by henrygrover** [comment] 2015-03-26 20:32
I am experiencing the same issue.  In order to get around an "Are you sure you want to leave?" dialog, I set up Cucumber after hooks to close the browser at the end of running each scenario.  With the restartBrowserBetweenTests set to true, I was expecting it to generate a new browser immediately afterwards and avert any issues.  Instead, though, it throws the same valid session ID error mentioned above.

What makes it especially confusing is that Protractor does seem to successfully launch a new browser for consecutive scenarios (or at least for a second one).  The new browser appears to work, running all of the test steps, before that error is thrown.

**Comment by cjroth** [comment] 2015-04-03 19:35
I'm experiencing this with Jasmine 2.2 as well.

**Comment by jonasflesch** [comment] 2015-07-02 17:53
Same here.

**Comment by varunneelakantan** [comment] 2015-09-09 22:21
I am seeing the same issue. Any solutions?

**Comment by dannypk** [comment] 2015-09-28 15:48
+1

**Comment by sjelin** [comment] 2015-09-28 20:30
Duplicate of https://github.com/angular/protractor/issues/2001

**Closed by sjelin** 2015-09-28 20:30 UTC
Labels: framework: cucumber
