### ISSUE TITLE
Firefox Timed out waiting for the WebDriver server at http://127.0.0.1:51759/hub

### ISSUE THREAD

**Issue by yashwp** [angular/protractor#5132] opened 2019-01-25 08:39 UTC
When I running `ng e2e -s false` command for my Angular application, the console is throwing the below error

```
(node:170720) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[13:49:50] I/direct - Using FirefoxDriver directly...
[13:49:50] I/launcher - Running 1 instances of WebDriver
[13:49:51] I/update - chromedriver: file exists F:\Commutatus\yop-v3\node_modules\webdriver-manager\selenium\chromedriver_2.24win32.zip
[13:49:51] I/update - chromedriver: unzipping chromedriver_2.24win32.zip
[13:49:52] I/update - chromedriver: v2.24 up to date
[13:49:52] I/update - selenium standalone: file exists F:\Commutatus\yop-v3\node_modules\webdriver-manager\selenium\selenium-server-standalone-2.53.1.jar
[13:49:52] I/update - selenium standalone: v2.53.1 up to date
[13:49:55] W/file_manager - geckodriver-v0.9.0-win64.zip expected length undefined, found 2202503
[13:49:55] W/file_manager - removing file: F:\Commutatus\yop-v3\node_modules\webdriver-manager\selenium\geckodriver-v0.9.0-win64.zip
[13:49:55] I/downloader - geckodriver: downloading version v0.9.0
[13:49:55] I/downloader - curl -o F:\Commutatus\yop-v3\node_modules\webdriver-manager\selenium/geckodriver-v0.9.0-win64.zip https://github.com/mozilla/geckodriver/releases/download/v0.9.0/geckodriver-v0.9.0-win64.zip
[13:50:13] I/update - geckodriver: unzipping F:\Commutatus\yop-v3\node_modules\webdriver-manager\selenium\geckodriver-v0.9.0-win64.zip
[13:50:37] E/launcher - Timed out waiting for the WebDriver server at http://127.0.0.1:61450/hub
[13:50:37] E/launcher - Error: Timed out waiting for the WebDriver server at http://127.0.0.1:61450/hub
    at onError (F:\Commutatus\yop-v3\node_modules\selenium-webdriver\http\util.js:87:11)
    at ManagedPromise.invokeCallback_ (F:\Commutatus\yop-v3\node_modules\selenium-webdriver\lib\promise.js:1379:14)
    at TaskQueue.execute_ (F:\Commutatus\yop-v3\node_modules\selenium-webdriver\lib\promise.js:2913:14)
    at TaskQueue.executeNext_ (F:\Commutatus\yop-v3\node_modules\selenium-webdriver\lib\promise.js:2896:21)
    at asyncRun (F:\Commutatus\yop-v3\node_modules\selenium-webdriver\lib\promise.js:2775:27)
    at F:\Commutatus\yop-v3\node_modules\selenium-webdriver\lib\promise.js:639:7
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: WebDriver.createSession()
    at Function.createSession (F:\Commutatus\yop-v3\node_modules\selenium-webdriver\lib\webdriver.js:329:24)
    at new Driver (F:\Commutatus\yop-v3\node_modules\selenium-webdriver\firefox\index.js:386:38)
    at Direct.getNewDriver (F:\Commutatus\yop-v3\node_modules\protractor\built\driverProviders\direct.js:75:26)
    at Runner.createBrowser (F:\Commutatus\yop-v3\node_modules\protractor\built\runner.js:198:43)
    at F:\Commutatus\yop-v3\node_modules\protractor\built\runner.js:277:30
    at _fulfilled (F:\Commutatus\yop-v3\node_modules\q\q.js:834:54)
    at F:\Commutatus\yop-v3\node_modules\q\q.js:863:30
    at Promise.promise.promiseDispatch (F:\Commutatus\yop-v3\node_modules\q\q.js:796:13)
    at F:\Commutatus\yop-v3\node_modules\q\q.js:556:49
    at runSingle (F:\Commutatus\yop-v3\node_modules\q\q.js:137:13)
[13:50:37] E/launcher - Process exited with error code 199
```

my **protractor.conf.ts**

```
// Protractor configuration file, see link for more information
// https://github.com/angular/protractor/blob/master/lib/config.ts

/*global jasmine */
const SpecReporter = require('jasmine-spec-reporter');

exports.config = {
  allScriptsTimeout: 11000,
  specs: [
    './e2e/**/*.e2e-spec.ts'
  ],
  capabilities: {
    'browserName': 'firefox'
  },
  directConnect: true,
  baseUrl: 'http://localhost:4000/',
  framework: 'jasmine',
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 300000,
    print: function () {
    }
  },
  useAllAngular2AppRoots: true,
  beforeLaunch: function () {
    require('ts-node/register')
  },
  onPrepare: function () {
    jasmine.getEnv().addReporter(new SpecReporter());
  }
};
```
I don't what's wrong. Firefox version `v64.x`

**Comment by cnishina** [comment] 2019-01-25 19:21
@yashwp This again, should be added to your StackOverflow question. If your StackOverflow question was closed create a new one again with the sample app we discussed on gitter. Also from reading gitter, it is not reproducible? Also Firefox might not work with directConnect.

Maybe trying the following:

* Does direct connect work with Chrome?
* Can you reproduce this with a selenium server + firefox?

If Chrome works with direct connect and selenium server + geckodriver works with firefox, it must be that direct connect for firefox is broken. It might be that geckodriver has a bug, geckodriver + selenium-webdriver compatibility is broken, or Protractor needs to review a different way to hook up Firefox with selenium-webdriver. Please spend some time to investigate this. Again, I still do not know what this `-s false` flag does in the Angular cli. I wrote that as a comment previously.

**Comment by yashwp** [comment] 2019-01-26 04:06
@cnishina -s false means don't serve the application, it is already serving in other console instance.

**Comment by cnishina** [comment] 2019-01-28 21:38
I see. So did you try the above? I have some comments that should be addressed.

**Comment by cnishina** [comment] 2019-03-24 15:53
Closing this issue due to staleness.

**Closed by cnishina** 2019-03-24 15:53 UTC
Labels: status: needs more info
