### ISSUE TITLE
Could not find testability for element when use elementor or element explorer

### ISSUE THREAD

**Issue by jalal1** [angular/protractor#3465] opened 2016-08-10 15:31 UTC
Hello, 

I am trying to run elementor, in order to locate elements on my page. But i always got the same message :

 ERROR: TypeError: Cannot create property 'stack' on string 'Error while waiting for Protractor to sync with the page: "Could not find testability for element."'

![image](https://cloud.githubusercontent.com/assets/1554493/17559758/02a1971e-5f28-11e6-8701-f21282841c00.png)

![image](https://cloud.githubusercontent.com/assets/1554493/17559775/0d507338-5f28-11e6-9feb-1634299d0e78.png)

Same error when trying to using Element explorer. 

![image](https://cloud.githubusercontent.com/assets/1554493/17559890/8dce41d4-5f28-11e6-93e9-c888ca4ec23c.png)
## Bug report
- Node Version: `6.2.0`
- Protractor Version: `4.0.3`
- Browser(s): `Chrome`
- Operating System and Version `Windows 7`
- Your protractor configuration file
- A relevant example test
- Output from running the test
- Steps to reproduce the bug
- The URL you are running your tests against (if relevant)
## Feature Request
- Reasons for adopting new feature
- Is this a breaking change? (How will this affect existing functionality)

**Comment by juliemr** [comment] 2016-09-13 05:32
I'm gonna be a stickler here - this isn't a bug. The issue is that you're not giving element explorer enough information to tell how your angular application is set up. You can fix this by passing in a config, which has a `rootElement` property that is an element underneath your angular application. 

But agreed that this behavior is difficult to understand - see comments in the linked issue. We're looking into simplifying.

**Comment by cnishina** [comment] 2016-12-19 22:40
Investigated: I also agree that more information should be passed to elementExplorer. For an Angular 2 app, the `useAllAngular2AppRoots` flag should be set in your Protractor config.  Another way to do this is in the elementExplorer console to set `browser.rootEl = '';`. 

Elementor does not allow you to pass in a config file so for Angular 2 apps, it appears that Elementor does not support it. It appears that there is already an issue for this in Elementor. https://github.com/andresdominguez/elementor/issues/47

Since this is not an issue with Protractor, I'm going to close this issue.

**Closed by cnishina** 2016-12-19 22:40 UTC
Labels: type: bug
