### ISSUE TITLE
browser.get() doesn't work in Safari with Selenium 2.45+

### ISSUE THREAD

**Issue by gmhenderson** [angular/protractor#2111] opened 2015-05-05 17:34 UTC
I'm experiencing an issue where browser.get() times out in Safari 100% of the time. I believe the root issue is described well in #2028. This issue was closed, but as far as I can tell, the root problem remains.

Is anyone else experiencing this?

Safari 8.0.4
WebDriver 2.45.0
OS X 10.10.2

**Comment by am-karl** [comment] 2015-05-06 12:09
Have the same problem here, using 
Safari 8.0.5
Webdriver 2.45.0
OSX 10.10.3

**Comment by eduardomb** [comment] 2015-05-07 13:58
+1

Protractor 2.0.0
Safari 8.0.5
Webdriver 2.45.0
OSX 10.10.3

**Comment by marcelross** [comment] 2015-05-11 15:40
Same here

Protractor: 2.0.0
OS: Windows 7
Webdriver: 2.45.0
Safari: 5.1.7

**Comment by sjelin** [comment] 2015-05-11 18:16
@eduardomb How confident are you that the problem is `window.location.replace`?  We would conceivably find some way to detect that we're on a new page (e.g. add some random property to the `<html>` tag), but I don't like the idea much because

a) It's a hack around an external bug
b) It doesn't even sound like you're sure there isn't some other underlying problem
c) The URL method is very reliable

**Comment by eduardomb** [comment] 2015-05-18 21:42
I'm not 100% positive the problem is `window.location.replace`. I did narrowed the problem down to this command a while ago but you are right, I'm not sure there isn't some other underlying problem.

I'll try to do some new experiments tomorrow and post the details here.

**Comment by eduardomb** [comment] 2015-05-20 14:41
@sjelin the problem is `executeScript` does not execute when the page is `about:blank` in Safari. I don't know why this happens, but it only happens in Safari, so it might be an external bug in SafariDriver.

To illustrate that problem, I've changed the `resetUrl` to http://google.com and the tests run just fine. (https://github.com/eduardomb/protractor/commit/46ebd896af625f975395d3c27b977c7724f9f563)

You can confirm that it works by running:
`cd /tmp/`
`git clone https://github.com/eduardomb/protractor protractor`
`cd protractor`
`git checkout safari_hack`
`npm install`
`./bin/webdriver-manager update`
`./bin/webdriver-manager start &> /dev/null &`
`npm start &> /dev/null &`
`export TEST_BROWSER_NAME=safari`
`npm test`

**Comment by juliemr** [comment] 2015-05-20 16:18
FYI, our tests run on safari on Travis happily: https://travis-ci.org/angular/protractor/jobs/63260687#L309

But that's running with selenium standalone 2.44.0, so it might be a problem with the 2.45 version.

**Comment by eduardomb** [comment] 2015-05-20 19:24
It might be it, @juliemr. Thanks! But how is it possible to use the latest protractor with selenium 2.44.0? Isn't protractor `>=2` incompatible with this version?  I've tried to downgrade selenium and now the tests fails with the message _Unimplemented function: "then"_.

**Comment by juliemr** [comment] 2015-05-20 19:46
@eduardomb it's confusing, but there's two things that can be called 'Selenium'
- the `selenium-webdriver` node module, aka WebDriverJS
- The selenium standalone server, which is downloaded via `webdriver-manager update`
They have versions which roughly follow each other. You can downgrade the selenium standalone server and still work with the latest version of Protractor, but you can't downgrade WebDriverJS.

**Comment by jmbarbier** [comment] 2015-05-20 22:24
I can confirm the issue and the fact that for a simple browser.get :

- protractor 2.1.0 + selenium-standalone 2.45.0 + safari webdriver extension 2.45 : **fails**
- protractor 2.1.0 + selenium-standalone 2.44.0 + safari webdriver extension 2.45 : **works**

**Comment by juliemr** [comment] 2015-05-20 22:31
Thanks for actually doing the test. I wonder if Safari can accept the data url that all the other browsers use now.

**Comment by eduardomb** [comment] 2015-05-21 18:14
Thanks a lot, @juliemr. I've downgraded selenium-standalone to 2.44.0 and tests are running perfectly on Safari. :)

**Comment by eduardomb** [comment] 2015-05-25 22:41
@juliemr I've wrote a simple [script](http://pastebin.com/G6Wgb41D) using selenium-standalone 2.45 and Safari in order to reproduce the bug and open an issue on Selenium project.

To my surprise, the script is able to successfully execute a `driver.get('about:blank')` followed by a `window.location.replace('http://google.com')`. Now, I'm not sure whether this is an external bug or not.

It would be nice if someone more  familiarized with selenium could figure this out. The script runs pretty much the same commands in `Protractor.get`.

Steps to run the script:
`mkdir /tmp/selenium-tst/`
`cd /tmp/selenium-tst/`
`npm install selenium-webdriver selenium-standalone`
`java -jar ./node_modules/selenium-standalone/.selenium/selenium-server/2.45.0-server.jar &> /dev/null &`
`curl -L http://pastebin.com/raw.php\?i\=G6Wgb41D > script.js`
`node script.js`

**Comment by spatchamatla** [comment] 2015-05-27 19:55
Im having the same problem, its working fine with safari extension v2.38.0 but when i upgraded the safari extension to v2.45 it fails.
@eduardomb can you tell me how to dowgrade back to either safari extension v2.38.0 or downgrade the selenium-standalone to 2.44.0

**Comment by eduardomb** [comment] 2015-05-28 11:56
@spatchamatla you can simply download selenium-standalone 2.44.0 [here](https://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar) and instead of running the usual `webdriver-manager start` you should run `java -jar selenium-server-standalone-2.44.0.jar`.

**Comment by spatchamatla** [comment] 2015-05-28 13:08
@eduardomb
Protractor 2.1.0
Safari 8.0.6
Webdriver 2.45.0
OSX 10.10.3

i tried with selenium-server-standalone-2.44.0 and when i run the script it navigates to the first URL but when it try to navigate to second url, it displays only **about:blank** and it times out with 
```
ScriptTimeoutError: Timed out awaiting response to command "executeScript" after 30001 ms (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 30.10 seconds
Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
System info: host: 'mac.local', ip: '<>', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_45'
Driver info: org.openqa.selenium.safari.SafariDriver
Capabilities [{browserName=safari, takesScreenshot=true, javascriptEnabled=true, version=8.0.6, cssSelectorsEnabled=true, platform=MAC, secureSsl=true}]
Session ID: null
```
its not even navigating to second URL.Im using browser.get() to navigate to the URLs. i tested both url's manually and with chrome as well.
```
java.lang.NullPointerException
	at org.openqa.selenium.remote.RemoteWebDriver.getCurrentUrl(RemoteWebDriver.java:319)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:101)
	at com.sun.proxy.$Proxy1.getCurrentUrl(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver.getCurrentUrl(EventFiringWebDriver.java:164)
	at org.openqa.selenium.remote.server.handler.GetCurrentUrl.call(GetCurrentUrl.java:30)
	at org.openqa.selenium.remote.server.handler.GetCurrentUrl.call(GetCurrentUrl.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:168)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
Is there any where i can download safari extension v2.38.0?

**Comment by eduardomb** [comment] 2015-05-28 13:59
@spatchamatla it should have worked. Not sure if this will solve your problem, but you can try to run my protractor fork that uses selnium-standalone 2.44.0:
`cd /tmp/`
`git clone https://github.com/eduardomb/protractor`
`cd protractor`
`git checkout selenium244`
`npm install`
`./bin/webdriver-manager update`
`./bin/webdriver-manager start`

Then use a new window to run your tests:
`/tmp/protractor/bin/protractor /path/to/your/test.js`

**Comment by spatchamatla** [comment] 2015-05-28 15:01
@eduardomb I tried with your branch still the same. what safari Extension are you using? Im using safari Extension v2.45.0
I'm trying to uninstall protractor using ```npm uninstall  protractor```, is there a way to uninstall protractor completely so that i can reinstall it again?

**Comment by abhirep** [comment] 2015-06-23 10:58
Hello everyone,
Has anyone found a solution for this

**Comment by spatchamatla** [comment] 2015-07-27 14:28
i gave some spec in which i can replicate the bug, Unable to navigate to URL in Safari #2346

**Comment by hhaamm** [comment] 2015-09-14 13:06
Same problem here.

Safari 8.0
WebDriver 2.45.0
Selenium 2.44.0
 OS X Yosemite

**Comment by juliemr** [comment] 2015-09-25 00:19
Possibly related?

https://code.google.com/p/selenium/issues/detail?id=7176

**Comment by jlin412** [comment] 2016-01-14 05:21
I download and install 2.48 version of safari driver.
It seems to work.
http://selenium-release.storage.googleapis.com/index.html?path=2.48/

**Comment by johwer** [comment] 2016-05-21 17:02
Starting with Selenium 2.48.0, you must manually install the SafariDriver browser extension.
I also had open up restrictions for localhost.
https://github.com/SeleniumHQ/selenium/wiki/SafariDriver

**Comment by juliemr** [comment] 2016-07-14 18:04
Looks like we need to give Safari some love. @mgiambalvo assigning you arbitrarily :)

**Comment by evanjmg** [comment] 2016-07-15 17:00
Could you explain what open up restrictions to localhost means? I still can't get this work on Protractor Version 4.0.0 and the latest selenium web driver. I have 2.48.0 installed and enabled in my extensions and selenium keeps looking for......... WebDriverError: Failed to connect to SafariDriver after 10058 ms
[safari 2.48.0 #21] Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'

**Comment by mgiambalvo** [comment] 2016-08-23 01:01
I've had issues getting the Safari extension working properly. It's worth noting that their links to the Safari extension go to their release page, but only the 2.48 release has the extension prebuilt. I found that, while I do have the extension installed and trusted, the browser started by webdriver may or may not have the extension.

It looks like there's a new driver for Safari coming with Sierra. See this issue from SeleniumHQ https://github.com/SeleniumHQ/selenium/issues/2475

**Comment by mgiambalvo** [comment] 2016-08-23 22:16
Duplicate of #2816. See also [selenium/1313](https://github.com/SeleniumHQ/selenium/issues/1313) and [selenium/1185](https://github.com/SeleniumHQ/selenium/issues/1185). Unfortunately, I don't think there's anything we can do about this. Trying it out on my own, I found the Webdriver Safari extension would randomly not work when starting a new Safari instance.

Hopefully, the new Safari driver in Webdriver 3.0 will work better.

**Closed by mgiambalvo** 2016-08-23 22:16 UTC
Labels: browser: safari, status: duplicate, status: external bug filed

**Comment by evilaliv3** [comment] 2020-03-02 20:21
Do you know if this bug is still present?

I'm still not able to get safary 12 to work on GlobaLeaks: https://travis-ci.org/globaleaks/GlobaLeaks/jobs/657420618

It fails with: "[18:56:51] E/browser - Could not find Angular on page http://localhost:9000/ : angular never provided resumeBootstrap"
