### ISSUE TITLE
Empty `it` throws an error

### ISSUE THREAD

**Issue by mzgol** [angular/protractor#1852] opened 2015-02-25 14:06 UTC
Jasmine allows the following syntax:
```js
it('should do sth');
```
and treats the test as skipped. It works this way in Karma but breaks in Protractor 1.7.0:
```
  Message:
    Error: undefined is not a function
  Stack:
    Error: undefined is not a function
        at Error (native)
        at validateFunction (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/protractor/node_modules/jasminewd2/index.js:32:36)
        at /Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/protractor/node_modules/jasminewd2/index.js:114:16
        at Suite.<anonymous> (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/test/e2e/spec/accounts-locale-sync.js:37:5)
        at Object.<anonymous> (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/test/e2e/spec/accounts-locale-sync.js:5:1)
        at Module._compile (module.js:444:26)
        at Object.Module._extensions..js (module.js:462:10)
```

**Comment by joaovieira** [comment] 2015-04-07 15:22
Using `pending()` also fails the test (not error though) @ `protractor 2.0.0` and `jasminewd2 0.0.3`:

```
- Failed: => marked Pending
      at /Users/joaovieira/Documents/EVRYTHNG/dashboard/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/jasminewd2/index.js:102:16
...
```

**Comment by sjelin** [comment] 2015-06-08 16:40
This bug appears to be caused by `require('jasminewd2');`

**Comment by sjelin** [comment] 2015-10-05 18:05
External bug fixed in next version.

**Closed by sjelin** 2015-10-05 18:05 UTC
Labels: status: external bug filed, type: bug, type: external bug
