### ISSUE TITLE
ElementExplorer does not work after upgrading to 2.0.0

### ISSUE THREAD

**Issue by igorshubovych** [angular/protractor#1948] opened 2015-03-19 15:06 UTC
After upgrading to protractor 2.0.0, elementExplorer stopped working
```
> browser.get('https://angularjs.org')
SyntaxError: evalmachine.<anonymous>:1
rowser.get('https://angularjs.org'
```
Screenshot
![Alt text](https://monosnap.com/file/E9Hhe6WlHYOsiapV2KAjF5lpoar0OS.png)

**Comment by igorshubovych** [comment] 2015-03-19 15:14
BTW,

elementExplorer in protractor 1.8.0 just hangs forever (ok, i cancelled it after waiting for 5 minutes).

**Comment by hankduan** [comment] 2015-03-19 18:00
duplicate of https://github.com/angular/protractor/issues/1890. Can you try with node 0.10.30? Please post correspondence in the linked issue.

**Closed by hankduan** 2015-03-19 18:00 UTC

**Comment by juliemr** [comment] 2015-03-19 19:18
I'm not sure the first issue is a duple of #1890, but I can't reproduce it. It looks like a problem with how we're trimming the input strings.

@igorshubovych what OS are you running on?

**Comment by hankduan** [comment] 2015-03-19 21:15
The first issue is related as well. The problem is fixed here: https://github.com/angular/protractor/pull/1898. Node changed the input for the repl server. 

@igorshubovych did you update node when you upgraded protractor?

**Comment by igorshubovych** [comment] 2015-03-21 22:24
Yes, it is duplicate of #1890. I see it is working with 0.10.

**Comment by Yukonjess101** [comment] 2015-03-23 20:36
I'm seeing the same behavior currently in 2.0.  I'm running:

Win 8.1 x64
node 0.12.0
npm 2.7.1

I do recall it working normally when Node 0.10.33 was installed.  I did upgrade my node version when I upgraded Protractor.  Is the best approach at the moment to downgrade node to 10?

Thanks!

**Comment by hankduan** [comment] 2015-03-23 20:39
Yes node 0.10.30 or lower

**Comment by shattenjager** [comment] 2015-05-28 00:54
I tried to downgrade to 0.10.29 but still is not working. I get SyntaxError: evalmachine.<anonymous>:1 on my Win machine. I also tried to install an older version of Protractor but I don't know how, since I use npm. My current version is 2.1.0. Also get this error not using elementExplorer but the debug mode triggered by a browser.pause() method, then I used repl to switch to the interactive mode, from there I can do only a browser.get() but can't manage to interact with any element.
