### ISSUE TITLE
Timeout expired waiting for async script in IE11

### ISSUE THREAD

**Issue by vivekbrahmadandi** [angular/protractor#3208] opened 2016-05-10 08:55 UTC
Timeout exception in IE11  browser randomly, where it is working fine in other browser(chrome and firefox).
what might be causing this exception to be thrown only in IE11?

**Comment by NickTomlin** [comment] 2016-05-11 15:29
Hi there,

Please follow the [Issue Template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) when opening new issues. Otherwise it's unclear what the issue is and how we can actually help.

I'm going to close this issue, please re-open a new one following the issue template linked above. Thanks! 😄

**Closed by NickTomlin** 2016-05-11 15:29 UTC
