### ISSUE TITLE
protractor unable to select a dropdown option

### ISSUE THREAD

**Issue by dotjose** [angular/protractor#2657] opened 2015-11-02 12:45 UTC
Hi there, I have been working on protractor and I have got such unbeatable situation. Protractor can not select a drop down option. It only takes the default value and proceed to the next test specs. I have write my tests like this.

     element(by.id('general-title-two')).$('[value="pastor"]').click();
I'm using firefox browser and I see the element is clicked but after the click option I didn't see the drop down value is changed. Is there anybody who can help?

**Comment by NickTomlin** [comment] 2015-11-02 13:30
I believe this is a duplicate of [480](https://github.com/angular/protractor/issues/480). You should be able to use one of the workarounds in that thread in the time being. Chrome should work just fine.

**Closed** 2015-11-02 18:17 UTC
Labels: status: duplicate

**Comment by Monica-Samaiya** [comment] 2017-05-26 06:57
Hello, I am selecting value from ui-select (drop-down) in protractor but once It is clicking on next button, that drop-down is loosing it's value, So anyone can tell me where I am going wrong?

**Comment by wswebcreation** [comment] 2017-05-26 07:05
Hi @Monica-Samaiya 

First of all be aware that you asking a question on an already closed issue. The change that it will be answered is very small.

Secondly, your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
