### ISSUE TITLE
Not able to locate the element in the <g> tag as it is based on and id and has been used in couple of pages.

### ISSUE THREAD

**Issue by Sourlyf** [angular/protractor#3194] opened 2016-05-02 12:52 UTC
Code : 

<a class="dropdown-toggle" data-toggle="dropdown" href="">
<svg viewBox="0 0 24 24" height="24" width="24">
<g id="svgHelp" fill="none" stroke-linejoin="round" stroke-linecap="round" stroke-width="1.5" stroke="#fff">
<path d="M11 1c5.523 0 10 4.477 10 10s-4.477 10-10 10-10-4.477-10-10 4.477-10 10-10z">
<path d="M10.811 12.818v-.909c1.463 0 2.727-1.265 2.727-2.727 0-1.463-1.265-2.727-2.727-2.727-1.085 0-2.129.812-2.538 1.746">
<path d="M11 15.545v.909">
</g>
</svg>
</a>

a class="dropdown-toggle" data-toggle="dropdown" href="">
<svg viewBox="0 0 24 24" height="24" width="24">
<g id="svgSettings" fill="none" stroke-width="1.5" stroke="#fff" stroke-linecap="round">
<path d="M21 12.818v-3.636h-2.965c-.172-.665-.434-1.293-.775-1.871l2.096-2.096-2.571-2.571-2.096 2.096c-.578-.341-1.205-.603-1.871-.775v-2.965h-3.636v2.965c-.665.172-1.293.434-1.871.775l-2.096-2.096-2.571 2.571 2.096 2.096c-.341.578-.603 1.205-.775 1.871h-2.965v3.636h2.965c.172.665.434 1.293.775 1.871l-2.096 2.096 2.571 2.571 2.096-2.096c.578.341 1.205.603 1.871.775v2.965h3.636v-2.965c.665-.172 1.293-.434 1.871-.775l2.096 2.096 2.571-2.571-2.096-2.096c.341-.578.603-1.205.775-1.871h2.965z">
<path d="M8.273 11c0-1.506 1.221-2.727 2.727-2.727 1.506 0 2.727 1.221 2.727 2.727 0 1.506-1.221 2.727-2.727 2.727-1.506 0-2.727-1.221-2.727-2.727z">
</g>
</svg>

**I have to optain svgSettings and get it clicked but i am not able to by the following code using protractor :

 var u = element(by.css('.dropdown-toggle')).element(by.tagName('g'));
		  u.click();**

**Comment by NickTomlin** [comment] 2016-05-02 20:13
Hi there,

Please follow the [Issue Template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) when opening new issues. Otherwise it's unclear what the issue is and how we can actually help.

I'm going to close this issue, please re-open a new one following the issue template linked above. Thanks! 😄

**Closed by NickTomlin** 2016-05-02 20:13 UTC
