### ISSUE TITLE
browser.explore() doesn't exist

### ISSUE THREAD

**Issue by Devgaze** [angular/protractor#4111] opened 2017-02-23 14:45 UTC
Bug report
---

- Node Version: `v6.9.5 `
- Protractor Version: `5.1.1`
- Angular Version: `2.4.3`
- Browser(s): `Chrome`
- Operating System and Version `macOs Sierra 10.12.3 (16D32)`

Your protractor configuration file
---
```javascript
/**
 * @author: @AngularClass
 */

require('ts-node/register');
var helpers = require('./helpers');

// creds
var creds = require('../.tip.credentials.json');

// screenshot reporter
var HtmlScreenshotReporter = require('protractor-jasmine2-screenshot-reporter');
var reporter = new HtmlScreenshotReporter({
  dest: 'e2e-report/screenshots',
  filename: 'mgmt-console.html',
  fixedScreenshotName: true,
  takeScreenshotsOnlyOnFailures: false,
  userCss: 'my-report-styles.css',
  pathBuilder: function(currentSpec, suites, browserCapabilities) {
    // will return chrome/your-spec-name.png
    return browserCapabilities.get('browserName') + '/' + currentSpec.fullName.split(' ').join('-');
  },
  metadataBuilder: function(currentSpec, suites, browserCapabilities) {
    return { id: currentSpec.id, os: browserCapabilities.get('browserName') };
  }
});

exports.config = {
  baseUrl: 'http://localhost:3000/',

  // use `npm run e2e`
  specs: [
    helpers.root('src/**/**.e2e.ts'),
    helpers.root('src/**/*.e2e.ts')
  ],
  exclude: [],

  framework: 'jasmine2',

  allScriptsTimeout: 110000,

  jasmineNodeOpts: {
    showTiming: true,
    showColors: true,
    isVerbose: false,
    includeStackTrace: false,
    defaultTimeoutInterval: 400000
  },
  directConnect: true,

  capabilities: {
    'browserName': 'chrome',
    'chromeOptions': {
      'args': ['show-fps-counter=true']
    }
  },

  beforeLaunch: function() {
    // setup report before any starts
    return new Promise(function(resolve){
      reporter.beforeLaunch(resolve);
    });
  },

  afterLaunch: function(exitCode) {
    // close report at this point
    return new Promise(function(resolve){
      reporter.afterLaunch(resolve.bind(this, exitCode))
    });
  },

  onPrepare: function() {
    // omitted for brevity 
    ....
  },

  /**
   * Angular 2 configuration
   *
   * useAllAngular2AppRoots: tells Protractor to wait for any angular2 apps on the page instead of just the one matching
   * `rootEl`
   */
   useAllAngular2AppRoots: true
};

```

A relevant example test
---
```javascript
// app.e2e.ts
describe('App', () => {

  let appPage;
  
  beforeAll(() => {
    appPage = new AppPage();
    appPage.load();
    console.log('\x1Bc');
  });

  // cleaned up version 

  it('should find `menu` component', () => {
    browser.explore();
    expect(appPage.hasMenu()).toBeTruthy();
  });

});

// app.e2e-page.ts
export class AppPage {
  menuElement;

  constructor(){
    this.menuElement = element(by.css('.menu'));
  }
  load(){
    browser.get('/');
  }

  hasMenu(){
    return this.menuElement.isPresent();
  }
}

```

Output from running the test
---
```bash
...

[14:22:33] D/launcher - Running with --troubleshoot
[14:22:33] D/launcher - Protractor version: 5.1.1
[14:22:33] D/launcher - Your base url for tests is http://localhost:3000/
Report destination:   e2e-report/screenshots/mgmt-console.html
[14:22:33] I/launcher - Running 1 instances of WebDriver
[14:22:33] I/direct - Using ChromeDriver directly...
[14:22:35] D/runner - WebDriver session successfully started with capabilities Capabilities {
  'acceptSslCerts' => true,
  'applicationCacheEnabled' => false,
  'browserConnectionEnabled' => false,
  'browserName' => 'chrome',
  'chrome' => { chromedriverVersion: '2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9)',
  userDataDir: '/var/folders/cg/cwn0yp852fx0lyl35brm075r0000gn/T/.org.chromium.Chromium.wA0VFy' },
  'cssSelectorsEnabled' => true,
  'databaseEnabled' => false,
  'handlesAlerts' => true,
  'hasTouchScreen' => false,
  'javascriptEnabled' => true,
  'locationContextEnabled' => true,
  'mobileEmulationEnabled' => false,
  'nativeEvents' => true,
  'networkConnectionEnabled' => false,
  'pageLoadStrategy' => 'normal',
  'platform' => 'Mac OS X',
  'rotatable' => false,
  'takesHeapSnapshot' => true,
  'takesScreenshot' => true,
  'unexpectedAlertBehaviour' => '',
  'version' => '56.0.2924.87',
  'webStorageEnabled' => true }
[14:22:35] D/runner - Running with spec files /dev/web/mgmt-console-web-app/src/app/app.e2e.ts,/dev/web/mgmt-console-web-app/src/app/app.e2e.ts
[14:22:43] E/launcher - Error: TSError: ⨯ Unable to compile TypeScript
src/app/app.e2e.ts (26,13): Property 'explore' does not exist on type 'IBrowser'. (2339)

...
```

I did look up on this both on SO and Issues, but no luck. Apologies if this is a duplicate or in an inappropriate place.

Thanks in advance.

**Comment by stefan--** [comment] 2017-03-03 21:39
Hi there, 
looking at at the `ProtractorBrowser` class declaration file, I am also missing `browser.manage()` and thus `browser.manage().addCookie()`. Now that the Protractor API differs from the Selenium-Webdriver API ([DefinitelyTyped Selenium-Webdriver addCookie() declaration](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/555ea54770b8576162e761e344de969d6e960869/selenium-webdriver/index.d.ts#L3326)) it neither helps to install the `@types/selenium-webdriver` types. Am I missing something?

**Comment by NickTomlin** [comment] 2017-03-05 04:08
Interesting, I'm not able to reproduce with a [small example](https://github.com/NickTomlin/protractor/tree/ts-explore-issues/exampleTypescript):

```javascript
require('ts-node/register');

module.exports.config = {
  framework: 'jasmine',
  directConnect: true,
  capabilities: {
    browserName: 'chrome'
  },
  specs: [ 'spec.ts' ],

  // You could set no globals to true to avoid jQuery '$' and protractor '$'
  // collisions on the global namespace.
  noGlobals: true
};
```

```typescript
import {browser, element, by, By, $, $$, ExpectedConditions} from 'protractor';

describe('App', () => {
  let appPage;

  it('should allow usage of `browser.explore`', () => {
    browser.get('http://angularjs.org');
    // manage works as well
    browser.explore();

    expect($('input').isPresent()).toEqual(true);
  });
});
```

What typescript version are you using?

**Comment by Devgaze** [comment] 2017-03-06 10:28
I'm using Typescript 2.0.10.
I just tested your example and it truly does work, well partially because when I try to fetch an element by id, it gets stuck and eventually timeout.

Check below:

```bash
➜  prt npm test

> prt@1.0.0 pretest /dev/web/prt
> npm run tsc


> prt@1.0.0 tsc /dev/web/prt
> tsc


> prt@1.0.0 test /dev/web/prt
> protractor conf.js

[10:20:19] I/launcher - Running 1 instances of WebDriver
[10:20:19] I/direct - Using ChromeDriver directly...
Started
[10:20:25] I/protractor -
[10:20:25] I/protractor - ------- Element Explorer -------
[10:20:25] I/protractor - Starting WebDriver debugger in a child process. Element Explorer is still beta, please report issues at github.com/angular/protractor
[10:20:25] I/protractor -
[10:20:25] I/protractor - Type <tab> to see a list of locator strategies.
[10:20:25] I/protractor - Use the `list` helper function to find elements by strategy:
[10:20:25] I/protractor -   e.g., list(by.binding('')) gets all bindings.
[10:20:25] I/protractor -
Starting debugger agent.
Debugger listening on [::]:5858
>
element(by.id(''))         element(by.css(''))        element(by.name(''))       element(by.binding(''))
element(by.xpath(''))      element(by.tagName(''))    element(by.className(''))

> element(by.id('the-basics'))





> element(by.id('the-basics'))FA Jasmine spec timed out. Resetting the WebDriver Control Flow.
A Jasmine spec timed out. Resetting the WebDriver Control Flow.


Failures:
1) App should find `menu` component
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at ontimeout (timers.js:365:14)
        at tryOnTimeout (timers.js:237:5)
        at Timer.listOnTimeout (timers.js:207:5)
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at ontimeout (timers.js:365:14)
        at tryOnTimeout (timers.js:237:5)
        at Timer.listOnTimeout (timers.js:207:5)

1 spec, 1 failure
Finished in 87.107 seconds

[10:21:49] I/launcher - 0 instance(s) of WebDriver still running
[10:21:49] I/launcher - chrome #01 failed 1 test(s)
[10:21:49] I/launcher - overall: 1 failed spec(s)
[10:21:49] E/launcher - Process exited with error code 1
npm ERR! Test failed.  See above for more details.
➜  prt
```

Thanks for you reply anyway @NickTomlin

**Comment by NickTomlin** [comment] 2017-03-06 14:44
Interesting, thanks for reporting back! Let's focus on the typing issue first and then we can always create a second issue for the hanging inside `browser.explorer`. Do you feel like it is resolved? I'm not sure what differs between our repos but it sounds like an issue with an out of date typings dep?


@stefan-- I'm able to use `browser.manage` as well, can you reproduce using my small example, or produce an example of your own? If you are able to do so, please open up an additional issue. Thanks!

**Comment by Devgaze** [comment] 2017-03-06 15:09
@NickTomlin yes, I left it open for you to make a decision whether to keep it in loop or not. I have setup debugging inside VSCode which is actually more user friendly to my QA team than dealing with the terminal :). 

So finally by replicating your small example, this is what I have in my `package.json`
```json
```

**Comment by NickTomlin** [comment] 2017-03-06 23:39
Ah, that's due to my example being slightly out of date. https://github.com/angular/protractor/commit/4752ad1287af536c6dd442dd8c74546f978627d9 fixes this issue by pinning the jasmine typings. 

I'm going to go ahead and close this since the original issue doesn't seem to be a problem any more. Please feel free to open up a new issue for the hanging in the explorer (or let me know if this is still an issue and I can re-open it).

Thanks! 😄

**Closed by NickTomlin** 2017-03-06 23:39 UTC
