### ISSUE TITLE
Screenshot is not saved when test case throws an Error

### ISSUE THREAD

**Issue by badiale** [angular/protractor#2690] opened 2015-11-09 20:02 UTC
Following this [FAQ](https://github.com/angular/protractor/blob/master/docs/faq.md#how-can-i-get-screenshots-of-failures), we took screenshots of our test cases on version 1.8.0.
But on upgrading to the lastest version, the screenshot stopped to work on test cases which throw erros.
We used this to abort the test when one expectation can invalidate the complete test case, evicting a cascading failure.

To illustrate this scenario, I made a [simple git project](https://github.com/badiale/ProtractorSaveScreenshot), with three test cases:
1. one wich fails a expectation and a screenshot is successfully taken;
2. one wich fails with an error, but no screenshot is taken, or an empty image is generated;
3. one wich is ignored, but if you enable it, the second case will have a correct screenshot taken.

The problem seems to be that the protractor process is closed before the file is completely saved, but I'm not sure.

**Comment by juliemr** [comment] 2015-11-10 19:08
Yes, this is because the runner process has finished, so Protractor is cleaning up without knowing to wait. (See https://github.com/angular/protractor/blob/master/lib/launcher.js#L257). I'm not sure if this counts as a bug, or just an annoying side effect - usually, we do want to make sure that the process quits and doesn't hang unexpectedly. Additionally, when running in one process (which we do if there's no sharding requested, and which is desirable for debugging), we actually can't wait on the process to exit because we've got other waits and things we need to do.

The easy way around this is to have a `onCleanUp` or `afterLaunch` task which flushes all of your outputs and returns a promise when that's all done.

We should mention this in the FAQ example. Changing the type of this issue to 'docs'.

**Comment by juliemr** [comment] 2016-07-14 19:14
Closing as dupe of https://github.com/angular/protractor/issues/1938

**Closed by juliemr** 2016-07-14 19:14 UTC
Labels: type: docs
