### ISSUE TITLE
bug in mouseMove (IE Only)

### ISSUE THREAD

**Issue by JayFreeman** [angular/protractor#1034] opened 2014-07-04 15:41 UTC
I have a dropdown menu that is accessed by a caret. 
The caret is hidden until the mouse hovers over it.
When the caret is clicked, the dropdown menu is shown.

I use the following code in protractor to show the caret:

ptor.actions().mouseMove(ptor.findElement(protractor.By.id('caret'))).perform();

I then use findElement to click the caret, and another findElement to click a menu item.

In firefox and chrome, everything works perfectly. In InternetExplorer however, the menu flashes briefly and the menu item cannot be clicked.

If I kill the test (or add a browser sleep), it seems that any mouse movements over other carets on the page cause the same brief flash.

Is this a bug with the IEDriver? Like I said chrome and firefox work perfectly.

**Comment by juliemr** [comment] 2015-10-01 00:13
I'm aggressively closing issues that we are unable to reproduce, are support issues specific to one test, or deal with integrations with other projects that we don't directly support. If you feel you have a question, please see https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions. If you still have a bug report or feature request, please open a new issue. Thank you!

**Closed by juliemr** 2015-10-01 00:13 UTC
Labels: browser: IE, type: external bug
