### ISSUE TITLE
sendKeys() doesn't insert text because focus is on the address bar (firefox only)

### ISSUE THREAD

**Issue by tundo91** [angular/protractor#1511] opened 2014-11-07 20:14 UTC
Hi there,
i'm testing a form login contained in a modal. 

I'm using the Page Object so i get the element by this:
```javascript
    this.getRegistrationUserName = function () {
      return element(by.css('#registrationModalView.modal form[name="regForm"] #input_last_name'));
    };
```

**Sometimes** ```sendKeys(string)``` function execute but the input text-box isn't filled up by the *string*!
I can say that *execute* since  ```this.getRegistrationUserName().sendKeys(name).then(function() {console.log("done!");} )``` actually prints *done!*)
The weird is that i notice this issue just for the first input text-box of the form.

After looking #562 seems that executing ```.clear()``` on the text-box make ```sendKeys()``` working well.

Configuration:

- protractor 1.4.x
- chromedriver: 2.9

**Comment by hankduan** [comment] 2015-03-22 22:41
@tundo91 Can you bring up the staging app at 'https://staging.eversnapapp.com/view' again (or let me know where it has moved to)? Webdriver just started looking at the issue, and it would be helpful if it is up again.

**Comment by tundo91** [comment] 2015-03-23 08:45
I'm sorry but I'm not longer in that project i cannot do it :(

**Comment by hankduan** [comment] 2015-03-23 19:12
I'm going to close this issue since I haven't seen any other reproducible reports of this, and I cannot provide a reproducible example to selenium.

**Closed by hankduan** 2015-03-23 19:12 UTC
Labels: browser: firefox, external bug filed

**Comment by grese** [comment] 2017-04-13 05:11
I'm experiencing this exact same behavior on Firefox 52.

**Comment by koventhan123** [comment] 2020-01-07 05:35
i am not able to enter value in Text box field using sendKeys in Safari browser of appium. Any solutions ?
