### ISSUE TITLE
Element explorer doesn't work on Node 8

### ISSUE THREAD

**Issue by monkpit** [angular/protractor#4307] opened 2017-06-01 16:06 UTC
Bug report
---

- Node Version: `8.0.0`
- Protractor Version: `5.1.2`
- Angular Version: `n/a`
- Browser(s): `Chrome / chromedriver 2.29.0`
- Operating System and Version `Mac Sierra 10.12.5`
- Your protractor configuration file `n/a`

After installing node v8.0.0 and npm v5.0.0, reinstalling protractor globally and running `webdriver-manager update`, I cannot run `protractor --elementExplorer` because I receive the following error:

```
protractor --elementExplorer
(node:76684) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[11:04:10] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[11:04:11] I/protractor -
[11:04:11] I/protractor - ------- Element Explorer -------
[11:04:11] I/protractor - Starting WebDriver debugger in a child process. Element Explorer is still beta, please report issues at github.com/angular/protractor
[11:04:11] I/protractor -
[11:04:11] I/protractor - Type <tab> to see a list of locator strategies.
[11:04:11] I/protractor - Use the `list` helper function to find elements by strategy:
[11:04:11] I/protractor -   e.g., list(by.binding('')) gets all bindings.
[11:04:11] I/protractor -
module.js:487
    throw err;
    ^

Error: Cannot find module '_debugger'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/protractor/built/debugger/debuggerCommons.js:1:82)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

If I revert back to node 7.10.0 I don't get this error.

**Comment by NickTomlin** [comment] 2017-06-01 18:16
I don't think we are currently testing against node 8 so it makes sense that this may be broken. Thanks for bringing this up!

**Comment by NickTomlin** [comment] 2017-06-01 18:17
I'll try to dig into this in the next few days but a PR to fix this would be very welcome!

**Comment by monkpit** [comment] 2017-06-01 18:45
_debugger and the legacy CLI debugger were removed in Node 8: https://github.com/nodejs/node/commit/90476ac6ee

**Comment by GvS666** [comment] 2017-06-28 07:25
Any updates on this?

**Comment by bakasmarius** [comment] 2017-07-25 14:05
Could we please know what are the plans for Node 8 support? :)

**Comment by will-l-h** [comment] 2017-08-26 17:57
With Node v8 set to enter LTS in October, maybe we could get an update?

https://github.com/nodejs/LTS#lts-schedule1

**Comment by rodrigc** [comment] 2017-09-06 01:30
According to https://nodejs.org/en/docs/guides/debugging-getting-started/#legacy-debugger ,
the node.js team is migrating users to the new inspect API.

**Comment by uriah-ascend** [comment] 2017-10-06 14:48
Are there plans from the team to get this working again with either the inspect API or something other approach?

**Comment by wzup** [comment] 2017-10-25 03:29
Same error https://github.com/node-inspector/node-inspector/issues/1025#issuecomment-339202842
4 month already

**Comment by phenomnomnominal** [comment] 2017-11-03 08:42
I've started having a look into this. Here are a bunch of guesses about how updating this might work:

As far as I can tell, the changes need to happen in [debuggerCommons.js](https://github.com/angular/protractor/blob/a0a1fac8568f2bfbd6d5721db438aed390e30d23/lib/debugger/debuggerCommons.js)

Rather than `require('_debugger');` it needs to use `require('inspector');` ([docs here](https://nodejs.org/dist/latest-v8.x/docs/api/inspector.html)). You can then open the inspector, create a session, connect to it, and then use `session.post` and the [Chrome DevTools Protocol](https://chromedevtools.github.io/devtools-protocol/v8/Debugger/) to send the messages to add the breakpoints. 

I'll have a crack at a PR when I get some time.

**Comment by yxliang01** [comment] 2017-11-03 10:24
@phenomnomnominal Hey that's great! May I know when you are available for making the PR? Since this functionality is so useful, would be great if it can be created soon. It will speed up our development so much.
Thanks!

**Comment by qiyigg** [comment] 2017-11-06 22:46
@phenomnomnominal  Hi, we are planing to support node 8.0 recently, what's your current plan of fixing this issue?

**Comment by phenomnomnominal** [comment] 2017-11-06 23:03
Only what I outlined above. I was planning on having a crack at it this evening.

**Comment by qiyigg** [comment] 2017-11-07 00:19
@phenomnomnominal that's great, thanks a lot!

**Comment by qiyigg** [comment] 2017-11-12 04:50
@phenomnomnominal Hi, any updates so far?

**Comment by phenomnomnominal** [comment] 2017-11-12 04:59
I started having a go, but I was having issues with Selenium when trying to run the tests (any tips?). I’m going to have some more time Tuesday night. The new API is quite different, but I don’t foresee any real issues.

**Comment by qiyigg** [comment] 2017-11-12 06:51
ok, thanks a lot. I am supposed to have some time after Monday, maybe I can also look into it after that.

**Comment by phenomnomnominal** [comment] 2017-11-14 11:19
I got... somewhere? Turns out debugging the debugger isn't as straightforward as I'd have hoped. @qiyigg did you have a chance to look at anything?

**Comment by qiyigg** [comment] 2017-11-15 18:46
I will look into it today, thanks!

**Comment by phenomnomnominal** [comment] 2017-11-15 19:59
I’ll have some more time this evening too, we can compare notes later.

**Comment by Lilly2016** [comment] 2017-11-23 00:11
Hi, any progress on this issue in the last week? It's still occurring.

**Comment by qiyigg** [comment] 2017-11-23 00:26
For protractor debugger/explorer, we decided not to support it in node 8.
1. Protractor debugger/explorer mainly designed to debug test in control flow; but control flow is something we don't encourage(Especially we have native async/await in node 8) and will be eventually deprecated.
2. After investigating, we found it might need much effort to fix it and not worth doing that according to reason 1. 
3. We are working on providing new debugging documents for node 8 using native async/await and chrome inspector tool, which will give better experience than original debugger.
4. @phenomnomnominal If you have some breakthrough about this, we'd like to review it.  Thanks for your effort.

**Comment by KellyR-STCU** [comment] 2017-12-07 06:40
Do you have some kind of ETA for this?  We're chomping at the bit for it where I work.  Trying to teach some people about e2e testing and we don't have a way to go into debug mode and actually execute code in the context where the failure occurs.  If there is a way this can be done outside of this please let me know.

**Comment by qiyigg** [comment] 2017-12-07 19:44
@KellyR-STCU 
Hi, 
For node version < 8, you can use the original debugging process/tools.
For node version >=8, you can follow the new debugging process, which uses Node.js native async/await to handle asynchronous call(so that we don't need rely on control flow and old debugger), and use chrome inspector(or any other node debugger) to debug

We have some documents to describe how to debug with native async/await and chrome inspector 
[debugging with control flow disabled](https://github.com/angular/protractor/blob/master/docs/debugging.md#disabled-control-flow)
[how to use async/await](https://github.com/angular/protractor/blob/master/docs/async-await.md)

Hope it helps

**Comment by monkpit** [comment] 2017-12-08 00:06
@qiyigg what about elementExplorer?

**Comment by qiyigg** [comment] 2017-12-08 00:33
@monkpit  it won't work in Node 8 for the same reason. We don't have a complete substitute for that, but you can open and use chrome development tool during debugging, it won't conflict with protractor debugging as we encountered before.

**Comment by uriah-ascend** [comment] 2017-12-13 16:37
The solution is also a bit of a problem since it requires rewriting existing tests because "you cannot use a mix of async/await and the control flow".  It would be nice if you could specify which approach to take per test so that switching didn't require updating all existing tests.

**Comment by qiyigg** [comment] 2017-12-14 23:44
@uriah-ascend 
yes, I have to admit that it's not a perfect solution. But as I mentioned above, control flow is something that will be eventually [removed](https://github.com/SeleniumHQ/selenium/issues/2969). Convert our tests to async/await is something we should do gradually, and it does give us better debugging experience.
I guess one way you could do is to have a separate test config for new tests, and then convert them gradually.

**Comment by smoke** [comment] 2017-12-15 15:12
@qiyigg is there some guide or documentation how to convert to async/await?

**Comment by uriah-ascend** [comment] 2017-12-15 17:03
Pretty good info in those two links he provided titled **debugging with control flow disabled** and 
**how to use async/await**

**Comment by uriah-ascend** [comment] 2017-12-15 17:04
The first one is probably more of a step by step for conversion.

**Comment by wootsaejao** [comment] 2018-01-07 10:03
After having issue with `browser.pause()` on Node 8.

I followed [Disabled Control Flow](https://github.com/angular/protractor/blob/master/docs/debugging.md#disabled-control-flow).

Instead of running `node --inspect-brk bin/protractor <config_file>` and do debugging in the browser, I use `node inspect $(which protractor) <config_file>` follow by `debug> cont` in the terminal. 

Now I have `browser.pause()` equivalent. 

i.e. use `debugger` in place of `browser.pause()`

**Comment by barroudjo** [comment] 2018-01-12 15:26
Just to check: we have a large protractor codebase, which can't be converted to async/await all at once. A good way to go about this is to first convert all the "async" protractor actions using promise chaining right ? This way things should work whether control flow is enabled or not.
Thanks !

**Comment by barroudjo** [comment] 2018-01-12 18:58
The problem is that we share a lot of functions between tests, so if we migrate these functions to async await we'll be breaking all the tests that use them and that haven't been migrated to async await (hint: A LOT). And if we keep two versions of the same function we risk having them diverge.
So it seems to me that either we move everything to promise chaining as an intermediate step before moving to async/await, or we set up babel to transpile our test codebase, so that we can write async/await and have it transpiled to something that can be run either with control flow or without.
Does anyone know if this has been done before ?
In any case it seems it would be a good idea to give migrations paths for large codebases on the readme...

**Comment by qiyigg** [comment] 2018-01-16 18:58
Make sense, actually we are thinking about it recently.
I've talked to an internal team who migrated large code base to async/await.
They found that it will introduced subtle bugs and race conditions if they changed common utils to promise chain and they already gave up to do that.
They did copy some common utils and translate them into async/await. I don't know whether it is the best solution, but as you mentioned, it will have some diverge risk
We are also working on writing some migration tool to make it easier, but the tools perhaps won't work externally.

Anyway, we are working on migration plan recently, and should give some migration advice in somewhere in the near future.

**Comment by barroudjo** [comment] 2018-01-17 10:36
Thanks you for your reply, it's good to know that it is an issue that is
being looked into !
I think it would be a good idea to create a specific issue for how to
migrate large codebases, so that people see it's being worked on.

**Comment by Xotabu4** [comment] 2018-01-31 17:34
Hi guys! Any workaround exist?
```
protractor - 5.2.2
nodejs - 9.3
```


```
protractor --elementExplorer
(node:72438) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[19:15:43] I/local - Starting selenium standalone server...
[19:15:44] I/local - Selenium standalone server started at http://172.29.148.101:58279/wd/hub
[19:15:45] I/protractor -
[19:15:45] I/protractor - ------- Element Explorer -------
[19:15:45] I/protractor - Starting WebDriver debugger in a child process. Element Explorer is still beta, please report issues at github.com/angular/protractor
[19:15:45] I/protractor -
[19:15:45] I/protractor - Type <tab> to see a list of locator strategies.
[19:15:45] I/protractor - Use the `list` helper function to find elements by strategy:
[19:15:45] I/protractor -   e.g., list(by.binding('')) gets all bindings.
[19:15:45] I/protractor -
module.js:557
    throw err;
    ^

Error: Cannot find module '_debugger'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/protractor/built/debugger/debuggerCommons.js:1:82)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
[19:15:45] I/local - Shutting down selenium standalone server.
MB-219751:~ olekh$ 

```

**Comment by benjaminapetersen** [comment] 2018-02-08 02:46
Also experiencing the `Error: Cannot find module '_debugger'`, OSX.

**Comment by ajklotz** [comment] 2018-05-02 16:09
This issue has been open for almost a year. Still no progress?

**Comment by mraible** [comment] 2018-05-02 16:14
@ajklotz I can confirm it still only works with Node 7. I've been using [nvm](https://github.com/creationix/nvm) to switch between Node versions in order to use element explorer. It's a pain, but it works!

**Comment by rodrigc** [comment] 2018-05-02 20:35
@ajklotz @monkpit @mraible If you are able to run with Node 8 or higher, I recommend that you try to do the following:

1.  Watch this video "Protractor: A New Hope" https://youtu.be/6aPfHrSl0Qk?t=1051 , specifically starting around *17:31*
2.  Switch to using Node 8 or higher
3.  Convert your tests to use the ES2017 async/await keywords: https://github.com/angular/protractor/blob/master/docs/async-await.md
4.  Add `SELENIUM_PROMISE_MANAGER: false,` to your protractor.conf.js
5.  Use the new `debugger` function and use chrome inspector to debug: https://github.com/angular/protractor/blob/master/docs/debugging.md#disabled-control-flow

I have done this with my own Protractor tests and confirm that it works.

**Comment by rodrigc** [comment] 2018-05-02 21:36
@ajklotz @monkpit @mraible Here is an example where I converted Protractor tests to use async/await: https://github.com/buildbot/buildbot/pull/4074/files

Anything that returns a Promise, you stick an `await` in front of it such as:

* `.click()`
* `.browser.wait()`
* `.browser.get()`
* `.getText()`

If a function has a call to `await`, then the function signature must have `async` in front of it.

If you call a function with `async`, then you must `await` it.

It takes a while but once you do it, then it works.

**Comment by monkpit** [comment] 2018-05-05 18:59
@rodrigc My tests area already using async/await, the point of this issue is that from the command line, `protractor --elementExplorer` doesn't work unless you use node 7.

**Comment by benjaminapetersen** [comment] 2018-05-07 13:38
FWIW, seems like a language feature like `async/await` should be irrelevant anyway. Perhaps a swap as a stop-gap fix makes sense, but Protractor doesn't imply dependence on that style.

**Comment by rodrigc** [comment] 2018-05-07 17:27
@monkpit Yes you are absolutely right.  The root cause of your problem is that on this line: https://github.com/angular/protractor/blob/master/lib/debugger/debuggerCommons.js#L1 , the `_debugger` module is imported, which is unavailable on node8.  Anything that uses `debuggerCommons.js` will thus not work on node8, including `elementExplorer`.

So, if you want to use node8 or higher and debug with protractor, the key is to use `async/await` and follow the steps at: https://github.com/angular/protractor/blob/master/docs/debugging.md

The old debugging stuff won't work.

**Comment by monkpit** [comment] 2018-05-07 22:46
Either it’s not going to get fixed (that’s fine, I can use the workaround) or it will be updated to use node 8+ (that’s also fine). But I would love to see an official response one way or the other.

**Comment by wswebcreation** [comment] 2018-05-08 05:33
@monkpit 

I think the answer lies in [this comment](https://github.com/angular/protractor/issues/4307#issuecomment-346507942) of @qiyigg. 

> For protractor debugger/explorer, we decided not to support it in node 8...

From what I've heard from @qiyigg when I talked to him the current focus in the team is lying on _disabling control flow in Protractor tests_.

I'm going to close this issue for now. It's still open for discussion.

**Closed by wswebcreation** 2018-05-08 05:33 UTC
Labels: PRs plz!, status: needs investigation

**Comment by rodrigc** [comment] 2018-05-08 06:25
@qiyigg I have started using the new `debugger` with chrome inspector, and node8 and it works well.

Can the protractor team start marking the documentation for the old debugging code which uses `debuggerCommon.js` as  **DEPRECATED**?  I agree with @monkpit that things are a bit confusing now where the code does not work with node8, but it is not marked as deprecated.  Ultimately this old debugging code should just be deleted if it is never going to get fixed with node8.

**Comment by rodrigc** [comment] 2018-05-08 07:50
@qiyigg I would suggest to make that warning in **bold** and **ALL CAPS**.  It is a bit hard to catch on that page, because there are a lot of words.

**Comment by activedecay** [comment] 2018-09-21 20:51
i'm really happy with the new debugger because i can use intellij to run my tests. this is way better than the element explorer (which i rather liked) but using my IDE to debug tests is a huge win.

**Comment by woppa684** [comment] 2018-10-10 09:04
@qiyigg I work at a company that makes large production pinters. Because we changed all our UI's to use Angular (hurray!) we decided to use Protractor for the UI E2E tests (also hurray). Apart from these E2E tests we also have real end to end tests that work on an actual running system. All the test cases for that test system are specified in the Microsft TFS testing framework and we use a DSL to write them. This DSL loads the page objects we wrote for our UI's through an interactively started protractor (so the element explorer) and calls methods on them to execute its tests.

So far so good, you would say, we have thousands of these tests and they run really "as a user". What I make out of this conversation is that element explorer is dropped with the new node (and the new node is mandatory for upgrading Angular). This also means that all of a sudden our en tire test base would stop working. 

I get the change with async / wait and we will rewrite our page objects obviously to support it, but there's not real alternative to remotely insert protractor commands right? I will always have to passs in "a  test" that only calls "debugger", and directly communicate with chrome to call a command on my page objects and then run to the next "debugger" call which I then probably will have to run in a while loop.

Were scenario's like these not supported? Won't they be? Or am I just missing something ... To me, debugging errors in your tests/code is something entirely different than remotely instructing test commands. The latter is something element explorer used to facilitate :)

**Comment by woppa684** [comment] 2018-10-10 13:17
To at least share what my current solution is, I have written this test, which is the only system test I run with protractor (CompletableFuture is a helper class obviously):

```ts
jasmine.DEFAULT_TIMEOUT_INTERVAL = 3600000; // arbitrary large timeout
(global as any).systemTestsDone = new CompletablePromise<void>();

describe('TestHelper', () => {
  it('should provide a way to interactively run tests', async () => {
    await (global as any).systemTestsDone;
  });
});
```

```
node --inspect .\node_modules\protractor\bin\protractor .\systemTests\protractor.conf.js
```

This test then keeps running while I connect my (C#) WS client that acts as a bridge between the test specs, and the page objects. This bridge then instructs the browser to load the page objects and the tests start executing.

The last command I send to the browser is of course
```ts
global.systemTestsDone.complete()
```
so that the test completes normally. I don't think this is really awful, the only strange thing is that I now have to abuse a test to get into an interactive mode. If more people are missing functionality like this it might be a good idea to include it in protractor again. I don't mean an entire devtools protocol but the option to leave protractor running while you, for example, use the console of chrome or visual studio code as "element explorer".

**Comment by qiyigg** [comment] 2018-10-10 22:56
add @vikerman, who will take over the Protractor stuff.

**Comment by woppa684** [comment] 2018-10-15 07:48
@vikerman Should I make a feature request out of the above comments? 

In short, what I would like to have in protractor (since `--elementExplorer` is no longer working with recent node.js versions) is a mode that just starts protractor, ignores spec files and just keeps running until some manual method call (something like `protractor.exit()`?). We could start protractor in this mode with `node --inspect`, load some page objects and connect an external test runner to the debugger protocol and run the tests interactively.

**Comment by gforceg** [comment] 2018-11-20 20:37
I downgraded to node v6 to get this to work and now I can't run my angular 6 app because node 6 isn't supported in angular 6+. Node 7 is end of life so I'd like to avoid using it and I'm not even sure it would work.

Is there a good work around that I can follow to get a protractor REPL w/o having to run two versions of node?

**Comment by yashwp** [comment] 2018-12-15 07:16
I'm having the same error in the console. I'm following these instructions given here
https://github.com/angular/protractor/blob/master/docs/debugging.md#enabled-control-flow

but still same error is coming 👎

**Comment by ernestoaparicio** [comment] 2018-12-24 20:05
So is this the end for browser.pause() / browser.debugger().  Appears we should be moving away from control flow and using node debugger.
https://github.com/angular/protractor/blob/master/docs/debugging.md

**Comment by ariskay** [comment] 2019-01-09 01:01
Using NVM to switch to node version 7.10.1 fixed the browser.pause() issue for me.

**Comment by suman90** [comment] 2019-04-24 14:23
I understand that async/await is the way forward, and using Webstorm to debug tests with breakpoints is absolutely seamless, but where I feel the absence of elementExplorer is its extended usage in the [elementor](https://www.npmjs.com/package/elementor) package, which was a delightful way to interactively test out parts of code on the fly (in the omnibox) instead of running the entire test from scratch.
With the given debugging process for nodejs 8+, the commands from the console do not resolve promises while the inspector is paused at a breakpoint, which I realise is counter-intuitive, but all this has meant a subtle increase in time spent on writing/debugging tests, and loss of a widely used feature (going by number of responses on this thread). 
Are there any plans to have a substitute for the old elementExplorer feature in protractor?

**Comment by vespertilian** [comment] 2019-05-01 22:46
@woppa684 Suggestion is working nicely for me. Thanks @woppa684. I just moved to node 10+ which has repl-await (so you can just await in the console)

Added all my config files for reference, hopefully it helps someone:

#### Special interactive debug spec - interactive.e2e.ts

```ts
import { LoginPage } from './src/pages/login.po';
import { AppPage } from './src/pages/app.po';
import { SwitchProfileSideSheet } from './src/side-sheets/switch-profile-side-sheet.po';
import { sel } from '../src/testing/get-component';

const login = new LoginPage();
const app = new AppPage();
const switchProfileSideSheet = new SwitchProfileSideSheet();

// add my own page objects to the global object so I can use them interactively.
global['sel'] = sel;
global['po'] = {
  login,
  app,
  switchProfileSideSheet,
};

(global as any).systemTestsDone = new Promise(function(_resolve, _reject) {
  global['finishInteractiveDebug'] = _resolve;
});

describe('TestHelper', () => {
  it('should provide a way to interactively run tests', async () => {
    await (global as any).systemTestsDone;
  });
});
```

#### package.json
```json
    "e2e-interactive": "node --experimental-repl-await --inspect-brk ./node_modules/.bin/protractor ./e2e/protractor.interactive.conf",
```

#### protractor.interactive.conf.js
```js
// Protractor configuration file, see link for more information
// https://github.com/angular/protractor/blob/master/lib/config.ts

// standard protractor config
const baseConfig = require('./protractor.conf');
const configCopy = Object.assign({}, baseConfig.config);

const oneDayInMilliSeconds = 1000 * 60 * 60 * 24;
// set timeout to a huge number
// so it's not an issue when we pause in the debugger
configCopy.allScriptsTimeout = oneDayInMilliSeconds;
configCopy.jasmineNodeOpts.defaultTimeoutInterval = oneDayInMilliSeconds;
// just load our interactive specs
configCopy.specs = ['./interactive.e2e.ts'];

console.log('interactive config', configCopy);
exports.config = configCopy;
```

**Comment by odikusar** [comment] 2019-09-18 08:57
I use `browser.sleep(100000)` instead of `browser.pause()`
