### ISSUE TITLE
Uknown error when closing standalone selenium-webdriver on CI

### ISSUE THREAD

**Issue by Crevil** [angular/protractor#2728] opened 2015-11-20 10:03 UTC
# Problem
When running Protractor on AppVeyor I get an error when closing the selenium webdriver.
```
C:\projects\appveyor-protractor-test-app\node_modules\protractor\node_modules\selenium-webdriver\lib\atoms\error.js:108
  var template = new Error(this.message);
                 ^
UnknownError: Can't obtain updateLastError method for class com.sun.jna.Native
    at new bot.Error (C:\projects\appveyor-protractor-test-app\node_modules\protractor\node_modules\selenium-webdriver\lib\atoms\error.js:108:18)
    at Object.bot.response.checkResponse (C:\projects\appveyor-protractor-test-app\node_modules\protractor\node_modules\selenium-webdriver\lib\atoms\response.js:109:9)
    at C:\projects\appveyor-protractor-test-app\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:379:20
    at [object Object].promise.Promise.goog.defineClass.invokeCallback_ (C:/projects/appveyor-protractor-test-app/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1337:14)
    at [object Object].promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.executeNext_.execute_ (C:/projects/appveyor-protractor-test-app/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2776:14)
    at [object Object].promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.executeNext_ (C:/projects/appveyor-protractor-test-app/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2758:21)
    at goog.async.run.processWorkQueue (C:\projects\appveyor-protractor-test-app\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\async\run.js:124:15)
    at process._tickCallback (node.js:368:9)
[launcher] Process exited with error code 1
```

The setup works on my local setup and protractor exits as expected.

# Setup
Protractor handles the selenium server with the `seleniumServerJar` option in `protractor.config`.
On AppVeyor the projects is build and deployed on a local IIS server.
The tests run fine and the results is as expected.

## Repository and build logs
See this [repository with a minimalistic setup](https://github.com/Crevil/AppVeyor-Protractor-test-app) for complete setup and [AppVeyor build](https://ci.appveyor.com/project/Crevil/appveyor-protractor-test-app/build/1.0.2) for details on the run.

Here is a snippet of my local protractor log on the same build.
```
C:\Users\BSO\Documents\Git repos\AppVeyor-Protractor-test-app>node_modules\.bin\protractor
protractor.conf.js --troubleshoot
DEBUG - Running with --troubleshoot
DEBUG - Protractor version: 3.0.0
DEBUG - Your base url for tests is http://localhost:47602/
DEBUG - Attempting to find the chromedriver binary in the default location used
by webdriver-manager
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
Selenium standalone server started at http://192.168.5.153:42594/wd/hub
DEBUG - WebDriver session successfully started with capabilities Object {
  caps_:
   Object {
     applicationCacheEnabled: false,
     rotatable: false,
     mobileEmulationEnabled: false,
     chrome:
      Object {
        userDataDir: 'C:\\Users\\BSO\\AppData\\Local\\Temp\\scoped_dir7528_8065'
 },
     takesHeapSnapshot: true,
     databaseEnabled: false,
     handlesAlerts: true,
     hasTouchScreen: false,
     version: '46.0.2490.86',
     platform: 'WIN8_1',
     browserConnectionEnabled: false,
     nativeEvents: true,
     acceptSslCerts: true,
     'webdriver.remote.sessionid': '4a77a2b8-79ff-491f-8152-8595a2bd5a4a',
     locationContextEnabled: true,
     webStorageEnabled: true,
     browserName: 'chrome',
     takesScreenshot: true,
     javascriptEnabled: true,
     cssSelectorsEnabled: true } }
DEBUG - Running with spec files C:\Users\BSO\Documents\Git repos\AppVeyor-Protra
ctor-test-app\AppVeyor-Protractor-test-app\index.e2e.spec.js
Started
.
1 spec, 0 failures
Finished in 1.415 seconds
Shutting down selenium standalone server.
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #1 passed
```

**Comment by NickTomlin** [comment] 2015-11-20 14:46
Thanks for creating a detailed example and explanation! 

I'm not familiar with AppVeyor, but the fact that this works fine locally and some quick searching seems to point to an environmental issue, particularly with [Java](http://stackoverflow.com/q/21679004/1048479)? I'd probably reach out to the AppVeyor folks and see if they can offer any assistance in debugging/configuring the build environment. 

If it turns out to be an issue with the protractor internals we should definitely resume the conversation here. Thanks!

**Comment by FeodorFitsner** [comment] 2015-11-23 19:14
Hi Nick,

AppVeyor developer is here. Thanks for looking into that. Can you give a hint what might be wrong with AppVeyor environment? Looks like [that thread](http://stackoverflow.com/questions/21679004/jna-unsatisfiedlinkerror-works-when-i-set-java-library-path-to-a-bogus-value) is related to Linux. I'm sure many customers would benefit from being able to run Protractor on AppVeyor environment!

**Comment by NickTomlin** [comment] 2015-11-23 21:10
@FeodorFitsner I won't be able to help much until later this evening, but i'd be happy to offer any assistance I can. 

I totally blanked on the fact that AppVeyor is windows only. The problem should be (hopefully) similar enough though.

1. What version of JNA is running on the AppVeyor boxes?
2. If it's JNA < 4 that is probably the issue. If that works fantastic!
3. If not, we should do some digging and probably coordinate in the [gitter](https://gitter.im/angular/protractor) channel when my schedule frees up

You can use the [example](https://github.com/angular/protractor/tree/master/example) files to test this (i'll try to get an AppVeyor project set up later for testing).

**Comment by FeodorFitsner** [comment] 2015-11-23 21:18
Thanks willing to help with that. No rush here.

I don't think we ever installed JNA explicitly on build workers. I thought it's something going along with Oracle's Java distributive, but looks like it's kind of a library: https://github.com/java-native-access/jna that should go with an app.

**Comment by NickTomlin** [comment] 2015-11-25 20:25
@FeodorFitsner @Crevil 

I've been able to reproduce this with a smaller project without browserstack [here](https://github.com/NickTomlin/protractor-appveyor-example). It looks like even though JNA is a dependency of selenium it will delegate to the system's version of JNA unless explicitly told not to (i'm not a Windows nor Java expert, so take that with a grain of salt). I haven't been able to find how to figure out which version of JNA is installed on these boxes. 

I think this is more of a windows/selenium issue than a protractor one. I'm reaching a point of diminishing returns in terms of my expertise here but i'd be happy to continue to coordinate things if you want a second pair of eyes.

**Comment by FeodorFitsner** [comment] 2015-11-26 18:09
Thanks for looking into that and the sample!

**Comment by NickTomlin** [comment] 2015-12-11 23:54
@sjelin I think we can close this? I'd like to work on getting AppVeyor tests running (so we can check windows in an automated way instead of having to boot up a VM) and I can follow up things on the AppVeyor side or open another more targeted issue.

**Comment by FeodorFitsner** [comment] 2015-12-12 00:26
Yeah, thank you!

**Closed** 2015-12-12 00:58 UTC
Labels: mobile, status: needs investigation, windows

**Comment by FeodorFitsner** [comment] 2016-02-10 02:14
I've managed to fix the issue with JNA on AppVeyor.

To make it work configure `-Djna.nosys=true` option for Selenium process in `protractor.conf.js`:

```
    localSeleniumStandaloneOpts: {
        args: ['-Djna.nosys=true']
    },
    ...
```

Full `protractor.conf.js` reference: https://github.com/angular/protractor/blob/fa0c692414fa98721dff80202ef95e9b3ccadebb/docs/referenceConf.js#L38-L46

**Comment by Crevil** [comment] 2016-02-10 06:13
Great news! Thank you.
