### ISSUE TITLE
$('css_path').isPresent() does not call waitForAngular()

### ISSUE THREAD

**Issue by jlin412** [angular/protractor#3386] opened 2016-07-18 20:37 UTC
$('css_path').isPresent() does not call waitForAngular()
It seems to be a bug to me.
I was assuming that all protractor function wrapper call for waitForAngular().
Please shed some light.

**Comment by NickTomlin** [comment] 2016-07-18 23:06
Hi there,

Please follow the [Issue Template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) when opening new issues. Otherwise it's unclear what the issue is and how we can actually help.

Thanks 😄

**Comment by jlin412** [comment] 2016-07-19 03:10
This is an usually general code question.  I am using 3.1.1 protractor version.  Rest of information are not relevant like browser/platform/conf.

To reproduce:
And I put console.log in waitForAngular(); inside of protractor.js.
And call $('css_path').isPresent();
And I am not getting console.log output.

**Comment by juliemr** [comment] 2016-07-20 20:25
`isPresent` will indeed wait for angular. Perhaps you've put the log in the wrong place, or are editing the wrong file. In any case, I'm closing this as not an issue - please open a new issue if you still believe there is a problem and can create a reproducible example.

**Closed by juliemr** 2016-07-20 20:25 UTC
