### ISSUE TITLE
treat multiple elements at elementFinder as error, its flaky test code

### ISSUE THREAD

**Issue by SebastianSolidwork** [angular/protractor#5166] opened 2019-02-27 08:13 UTC
I expect a selector/elementFinder to find one element and not multiples. To me its an error and bad code if an elementFinder finds more than one element. Its an open door for possible misbehaviors.
If i want the current behavior for multiple elements of elementFinder (taking the first one), i should decide and code that by my own.

> W/element - more than one element found for locator

I see this normal 'warning' just as a normal console output with white text, which can be easily overseen. Especial if the number of tests gets higher and is executed with a CI server. I do not want to look through hundred(s) of console logs of successful tests to see if there is a 'warning'.

Maybe this should be configurable to provide a backward compatibility. 

As 'just' a tester i don't fell firm enough to provide a pull request. :-( I'm still new to JS and TS.

**Comment by cnishina** [comment] 2019-03-24 16:04
I think this is the behavior we wanted. Alternatively, you could do an element.all and then get the count. If it is more than one you can then throw errors. Closing this issue since this is as intended.

**Closed by cnishina** 2019-03-24 16:04 UTC

**Comment by SebastianSolidwork** [comment] 2019-03-25 12:54
I want to have my different behavior by default. I don't want to code that at any occurrence of element.all.
Sad, one more point which drives me away from protractor.

Could you explain me what are the advantages of the actual behavior? Why is this intended?
I know it's intended, but i questioning the intention.
This issue was about that too:
https://github.com/angular/protractor/issues/2417

**Comment by cnishina** [comment] 2019-03-25 14:46
I believe this is the same behavior as selenium-webdriver. Anyway, here's my thoughts on why this is how it is:

As a person writing a test, I would still want a web element returned and a warning message that there is more than one web element. The test might still work since it is the first element but the warning is telling me that I might want to think about using an element array finder instead. If the test passes, most people will accept the warning because these tests are running in CI. If the behavior is not as expected (when getting the first web element), hopefully you will have assertions around it and it will fail.

I am going to think about this idea a little more. Hopefully you stick with Protractor a little longer. I'll add these thoughts in my rewrite. https://github.com/cnishina/protractor-lite Right now you cannot extend an element object because it is global; however, in my rewrite, I'm removing the global objects and you basically can instantiate the ElementFinder object. Since the constructor is pretty easy, you could then extend some of the functionality.

**Comment by tymfear** [comment] 2019-03-25 14:57
To extend an element you could use this https://github.com/Xotabu4/protractor-element-extend package.

**Comment by SebastianSolidwork** [comment] 2019-03-25 15:20
@cnishina Thanks, i couldn't hoped for more.

My experience is that most people oversee warnings like this, at least when it comes at a later time. Especial in CI.
Lets say there are 100 test cases. 10 are having real problems/errors. Do you look through the protocols of the other 90 just for that protractor warning?
I think it's quite easy to oversee the warning. 
People seldom know upfront if there will come later more elements. It's about the unpredictability of complex systems.
Maybe the coder of the app will know this in advance because he knows the code. But a dedicated software tester like me don't knows much about the code.

And a test can pass evens if its behavior is wrong, because of the changed number of elements. Shouldn't happen that often and is more a signal for real a bad test code. Bad can happen.
I only trust passed tests when i really know what they are doing. I feel uncomfortable if they potentially can do things i didn't expect them to do.
