### ISSUE TITLE
Style guide is incorrect regarding to the page objects

### ISSUE THREAD

**Issue by cambiph** [angular/protractor#2908] opened 2016-02-05 14:35 UTC
As per [my question](http://stackoverflow.com/questions/35226507/element-not-found-when-following-the-page-object-style-guide#35226585), the style guide needs to be updated. The answer of @alecxe solves the problem.

**Comment by alecxe** [comment] 2016-02-05 14:39
@andresdominguez FYI.

**Comment by andresdominguez** [comment] 2016-02-05 23:53
I do not think there is anything wrong with the style guide as it is. In the style guide we recommend declaring element finders and functions. An [ElementFinder](http://www.protractortest.org/#/api?view=ElementFinder) will not execute until you call a function on it, like `getText()`, `isPresent()`, etc.

When you mention "initialize some fields", what are you actually doing? Please update your question with the code that is causing a problem.

**Comment by alecxe** [comment] 2016-02-06 00:39
@andresdominguez I suspect the OP is trying to do something with the found elements right inside the constructor. That would explain why my advice to move the page object initializations to `beforeEach()` helped. Let's wait for the code. Thanks for looking into this.

**Comment by andresdominguez** [comment] 2016-02-06 16:32
@sjelin can you close this one as "Intended behavior"?

**Closed** 2016-02-06 18:00 UTC
Labels: type: docs

**Comment by cambiph** [comment] 2016-02-08 07:14
Here's the code, as requested:

```javascript
var LoginPage = function() {
  this.form = browser.driver.findElement(by.name('ldap_login_form'));
  this.usernameInput = browser.driver.findElement(by.id('username'));
  this.passwordInput = browser.driver.findElement(by.id('password'));

  this.get = function() {
    browser.driver.get('http://xxxxxxx');
  };

  this.login = function(username, password) {
    this.usernameInput.sendKeys(username);
    this.passwordInput.sendKeys(password);
    this.form.submit();
  };
};

module.exports = LoginPage;
```

```javascript
var LoginPage = require('./page-objects/consulent/LoginPage.js');

describe('SMP+', function() {

  var loginPage = new LoginPage();

  it('Login', function() {
    console.log('------------------->' + loginPage)
    loginPage.get();
    loginPage.login('vdabcor1', 'ldv');
  });
});
```

**Comment by andresdominguez** [comment] 2016-02-09 19:55
If you are using a non-angular app I would recommend you to do:

```javascript
browser.ignoreSynchronization = true;
```

And then use standard element finders:

```javascript
var LoginPage = function() {
  this.form = element(by.name('ldap_login_form'));
  this.usernameInput = $('#username');
  this.passwordInput = $('#password');

  this.get = function() {
    browser.get('http://xxxxxxx');
  };

  this.login = function(username, password) {
    this.usernameInput.sendKeys(username);
    this.passwordInput.sendKeys(password);
    this.form.submit();
  };
};

module.exports = LoginPage;
```

**Comment by cambiph** [comment] 2016-02-10 06:01
I bypassed it by just putting the whole code in an onPrepare function in the conf-file.
No need for pageobjects for the non-angular pages then.
