### ISSUE TITLE
Is there any conflict between angular and Protractor?

### ISSUE THREAD

**Issue by RunningV** [angular/protractor#3318] opened 2016-06-30 02:57 UTC
When a use angular i scarcelly use selector to get dom node, but if i use protractor to write e2e test , i need to get dom node by selectors frequentlly. I think it is conflict . how do u solve the problem when the component template was changed then lead to test fail?

**Comment by NickTomlin** [comment] 2016-06-30 10:28
Hi there,

Please follow the [Issue Template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) when opening new issues. Otherwise it's unclear what the issue is and how we can actually help.

I'm going to close this issue, please re-open a new one following the issue template linked above. Thanks! 😄

**Closed by NickTomlin** 2016-06-30 10:28 UTC
