### ISSUE TITLE
restart() clears local data

### ISSUE THREAD

**Issue by avdd** [angular/protractor#2871] opened 2016-01-26 07:10 UTC
Can I restart the browser while maintaining the local storage?

**Comment by sjelin** [comment] 2016-01-26 20:12
Seems line a bug to me.  Reproduction:

```js
describe('', function() {                                                                                                                                                                                    
  it('', function() {                                                                                                                                                                                        
    browser.get('http://www.angularjs.org');                                                                                                                                                                 
                                                                                                                                                                                                             
    browser.executeScript('localStorage.x = "y";');                                                                                                                                                          
    expect(browser.executeScript('return localStorage.x')).toBe('y');                                                                                                                                        
    browser.restart();                                                                                                                                                                                       
    browser.get('http://www.angularjs.org');                                                                                                                                                                 
    expect(browser.executeScript('return localStorage.x')).toBe('y');                                                                                                                                        
  });                                                                                                                                                                                                        
});                                                                                                                                                                                                          
```

**Comment by juliemr** [comment] 2016-01-27 17:40
I think this is working as intended - when you restart the browser, you're getting a completely new session. You should use `refresh` if that's your intention.

**Comment by juliemr** [comment] 2016-01-27 17:40
Closing as working as intended.

**Closed by juliemr** 2016-01-27 17:40 UTC
Labels: WebDriver issue/feature

**Comment by avdd** [comment] 2016-01-27 19:51
Well my intention is to test that my offline app properly persists its state across browser restarts.  There seems to be no way to test that.

**Comment by juliemr** [comment] 2016-01-27 20:20
It depends on your browser at that point - for Chrome, for example, you can use an existing profile using `user-data-dir` in your chrome options - see here: https://sites.google.com/a/chromium.org/chromedriver/capabilities

**Comment by sjelin** [comment] 2016-01-27 22:13
Definitely not a webdriver issue/feature - we wrote restart.  I don't see how this is working as intended.  LocalStorage is not cleared when you restart the browser.  If `browser.restart` is supposed to be the equivalent of uninstalling/reinstalling the browser and deleting all local data, we should give it a better name.

**Comment by juliemr** [comment] 2016-01-27 22:54
Whenever webdriver starts a browser, it starts a clean session (that's why you don't have your chrome profile, favorites etc). Suggestions for a better name?

**Comment by sjelin** [comment] 2016-01-27 23:17
A couple ideas:

* `browser.reset`
* `browser.factoryReset`
* `browser.restartSession`
* `browser.clean`
* `browser.clearData`

**Comment by juliemr** [comment] 2016-01-29 01:21
I like `restartSession`. But I don't want to do a breaking change release just for this issue. Can we change the name to `restartSession` and just have `reset` delegate to that for now?

**Comment by sjelin** [comment] 2016-01-29 02:14
We can but tbh I'm not that satisfied with `restartSession`.  I know I suggested it yesterday but today it just seems opaque.  Give me another day to think

**Comment by JaxxAnik** [comment] 2018-05-09 18:07
And two years have passed since...

**Comment by fergardi** [comment] 2019-02-14 15:58
I'm dealing with this situation as well.

My app uses sessionStorage to store the user session.

When I pass the login test, and continue to the next spec one, `browser.get(url)` restarts the browser and clears the localStorage an sessionStorage. Then, when landing the new URL, the guard sees the user as not logged in and redirects to the login page again.

I cannot use `browser.setLocation(relativeUrl)` due to requisites (not having has /#/ mode in URL), so any workaround for this?
