### ISSUE TITLE
protractor devuelve el error: Fatal error: protractor exited with code: 1

### ISSUE THREAD

**Issue by adisleydis** [angular/protractor#1171] opened 2014-08-06 17:11 UTC
Hola Julie, espero que me puedas ayudar. Yo estoy tratando de ejecutar las pruebas e2e en phantomjs en un servidor de integración continua, y hoy me dio este error, te voy a poner toda la salida, he buscado soluciones pero ya no sé que más debo hacer :( 

Running "protractor:phantom" (protractor) task
Using the selenium server at http://localhost:4444/wd/hub
[31mF[0m[31mF[0m[31mF[0m[32m.[0m[32m.[0m[32m.[0m[31mF[0m[31mF[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[31mF[0m
/var/lib/go-agent/pipelines/Test-Integracion/sniese-ui/repo/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:109
  var template = new Error(this.message);
                 ^
UnknownError: Session [bb23f4c0-1d81-11e4-9fee-e3269f0ce29c] was terminated due to FORWARDING_TO_NODE_FAILED
    at new bot.Error (/var/lib/go-agent/pipelines/Test-Integracion/sniese-ui/repo/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:109:18)
    at Object.bot.response.checkResponse (/var/lib/go-agent/pipelines/Test-Integracion/sniese-ui/repo/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/response.js:106:9)
    at /var/lib/go-agent/pipelines/Test-Integracion/sniese-ui/repo/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:277:20
    at /var/lib/go-agent/pipelines/Test-Integracion/sniese-ui/repo/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1243:15
    at webdriver.promise.ControlFlow.runInNewFrame_ (/var/lib/go-agent/pipelines/Test-Integracion/sniese-ui/repo/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1531:20)
    at notify (/var/lib/go-agent/pipelines/Test-Integracion/sniese-ui/repo/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:354:12)
    at notifyAll (/var/lib/go-agent/pipelines/Test-Integracion/sniese-ui/repo/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:323:7)
    at resolve (/var/lib/go-agent/pipelines/Test-Integracion/sniese-ui/repo/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:301:7)
    at fulfill (/var/lib/go-agent/pipelines/Test-Integracion/sniese-ui/repo/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:421:5)
    at /var/lib/go-agent/pipelines/Test-Integracion/sniese-ui/repo/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1398:10
==== async task ====
WebDriver.takeScreenshot()
    at webdriver.WebDriver.schedule (/var/lib/go-agent/pipelines/Test-Integracion/sniese-ui/repo/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:268:15)
    at webdriver.WebDriver.takeScreenshot (/var/lib/go-agent/pipelines/Test-Integracion/sniese-ui/repo/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:871:15)
    at to.(anonymous function) [as takeScreenshot] (/var/lib/go-agent/pipelines/Test-Integracion/sniese-ui/repo/node_modules/grunt-protractor-runner/node_modules/protractor/lib/protractor.js:53:25)
    at ScreenshotReporter.reportSpecResults (/var/lib/go-agent/pipelines/Test-Integracion/sniese-ui/repo/node_modules/protractor-screenshot-reporter/index.js:123:10)
    at jasmine.NestedResults.totalCount [as reportSpecResults] (/var/lib/go-agent/pipelines/Test-Integracion/sniese-ui/repo/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:1901:39)
    at jasmine.Spec.finishCallback (/var/lib/go-agent/pipelines/Test-Integracion/sniese-ui/repo/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2470:21)
    at jasmine.Spec.finish (/var/lib/go-agent/pipelines/Test-Integracion/sniese-ui/repo/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2475:8)
    at null.onComplete (/var/lib/go-agent/pipelines/Test-Integracion/sniese-ui/repo/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2504:10)
    at jasmine.Queue.next_ (/var/lib/go-agent/pipelines/Test-Integracion/sniese-ui/repo/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2219:14)
>> 
Fatal error: protractor exited with code: 1

**Comment by juliemr** [comment] 2015-01-06 20:15
Duplicate of https://github.com/angular/protractor/issues/557

**Closed by juliemr** 2015-01-06 20:15 UTC
Labels: phantomjs problem
