### ISSUE TITLE
Option to disable uncaughtException listener

### ISSUE THREAD

**Issue by calendir** [angular/protractor#3553] opened 2016-09-14 13:39 UTC
Please add an option to disable the `uncaughtException` listener from lib/launcher.ts:182 since it interferes with Cucumber as described in #3491.

Quick recap:
Protractor's `uncaughtException` listener registers first so it's fired before Cucumber's listener for the same event, which would normally handle whatever error occurred inside a step definition and gracefully fail the step. Which in turn leads to Protractor exiting the suite at the first exception (which could be, for example, a failed assertion).

**Comment by NickTomlin** [comment] 2016-09-14 19:20
It still seems like this is an issue with the framework relying on this and not Protractor itself (since `uncaughtException` is the last line of defense).

I'm not opposed to adding something like this in but it seems better dealt with at the framework level if possible.

**Comment by calendir** [comment] 2016-09-15 07:59
I understand your reluctance, but I don't see a way of handling this in `protractor-cucumber-framework` as all it does is listen to events broadcast by Cucumber and is only made aware of the failure if Cucumber has handled it.

**Comment by jlin412** [comment] 2016-09-22 13:07
+1 It is blocking cucumber.js users.

**Comment by igniteram** [comment] 2016-09-22 13:51
This seems to be an issue! I am aware that `uncaught exception` event is triggered before the cucumber listeners which is why the steps are failing abruptly incase of errors. 

**Note** : It works fine with Protractor 3.3.0 and `uncaught exception` was added from 4.0, so I won't say it's a blocker as of now, you could downgrade and check if it works for you.

Meanwhile, There should be an alternative for this to support with newer versions of protractor!
@NickTomlin @cnishina any suggestions?

**Comment by aluzardo** [comment] 2016-09-22 14:39
+1 It is blocking cucumber.js users.

**Comment by mgiambalvo** [comment] 2016-09-28 15:35
Whoops, I missed that @NickTomlin was taking this in #3491.

According to [cucumber/cucumber-js#643](https://github.com/cucumber/cucumber-js/issues/643), this needs a fix to `protractor-cucumber-framework`. Thanks for taking care of this, Nick!

Follow up on this issue should be directed to [mattfritz/protractor-cucumber-framework#56](https://github.com/mattfritz/protractor-cucumber-framework/issues/56)

**Comment by mgiambalvo** [comment] 2016-09-29 08:41
I take that back! It is a problem on our end.... kind of. The mocha and jasmine frameworks both have wrappers that handle exceptions - [jasminewd]([https://github.com/angular/jasminewd] for jasmine and [the Mocha wrappers in selenium-webdriver](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/testing/index.js). There's no such wrapper for cucumber, so we've actually never handled webdriver errors, it's just never been an issue since we ignored uncaught exceptions in the past.

It's actually a little surprising cucumber works at all without a webdriver wrapping, but I guess the pattern of putting all your expectations in a "Then" block means all the WebDriver ControlFlow promises will be resolved by the time you check for things.

In any case, this will be fixed in the next point release. Sorry for the breakage.

**Comment by aluzardo** [comment] 2016-09-29 09:06
If someone need it. I found a temporally workaround to avoid this problem temporally. The workaround is using ´multiCapabilities´and more than one browser inside the `config.js`.

For example:

```
multiCapabilities: [
        {
            browserName: 'firefox'
        },
        {
            browserName: 'chrome'
        }
    ]
```

**Comment by NickTomlin** [comment] 2016-09-29 17:13
@mgiambalvo thanks for following up on this!

I was working on something similar for the cucumber framework issue (I just updated it with a description of the problem). I was also very surprised that this had been "working" for so long.  I think your idea of fixing this in the time being is a much better quick solve. Thanks for taking that on!

**Comment by jlin412** [comment] 2016-09-29 17:47
There is always some integration issue of exception or error handling between cucumber and protractor on and off.  Perhaps, this is the root cause and will be resolved once for all!!!

**Comment by mgiambalvo** [comment] 2016-09-29 23:20
Well, unfortunately, this just goes back to the old behavior of ignoring uncaught exceptions from WebDriver. Though we do log a warning message when they happen now (progress!). I'm honestly a little surprised that cucumber works at all without some kind of webdriver wrapper similar to the ones I linked above for jasmine and mocha. I'd like to follow up on this later and find a better long term solution for cucumber.

**Comment by bhreinb** [comment] 2016-10-03 15:03
Hi There,

When do we anticipate to have a fix for this? Many thanks in advance.

I can roll back to an old version but i'd like to use the latest edition of protractor.

**Comment by mgiambalvo** [comment] 2016-10-06 02:29
The fix should be included in the next patch release, probably sometime next week.

**Closed** 2016-10-10 20:46 UTC
Labels: type: bug

**Comment by szikszail** [comment] 2016-10-25 07:39
Hi Guys, Do we have any info about that release which will include this fix?

**Comment by AlexandrosD** [comment] 2016-10-27 20:43
+1

**Comment by Chuckv** [comment] 2016-11-03 23:52
So I was seeing this same issue.  (using protractor, cucumber-protractor-framework, cucumber, webdriverjs)  and hoping that when we got the new release (which I presume would be 4.0.10 as it just came out a few days ago.

I updated protractor to the latest, but I find that for my tests, that I still get the failures and an exit with code 199 any time an action in a step fails (when that step's promise is not being returned) 

 eg I have a step that has two parts, both webdriver calls.  the first part clicks an element, the second waits for a spinner modal to go away..   so the code is roughly

    $(css-selector).click();
    return browser.wait(EC.not(EC.presenceOf($(css-for-spinner))));

if the click fails to find the element, that's the end of the test run, when what you would hope for is just for that scenario to fail and move on to the next one.   So it's seeming to me like this is not fixed.

**Comment by mgiambalvo** [comment] 2016-11-04 00:26
In 4.0.10, there's a new configuration option `ignoreUncaughtExceptions`. We don't want to turn this on by default, since it could mask difficult to debug WebDriver errors in Jasmine-based testing. Cucumber users will need to turn this option on, though.

**Comment by Chuckv** [comment] 2016-11-04 15:32
Ah, that makes sense.   Where is this documented so I make sure I'm using it right?

**Comment by kieranbop** [comment] 2017-01-10 11:03
I somehow stumbled accross this and the fix has saved me so much time. Thanks to everyone involved resolving this.
