### ISSUE TITLE
can't run it  in window 10

### ISSUE THREAD

**Issue by felix307253927** [angular/protractor#3135] opened 2016-04-18 06:31 UTC
I can run it in Ubuntu, when i run it in window10    throw error:

Failed: Angular could not be found on the page http://localhost:8080/login.html : angular never provided resumeBootstrap

**Comment by NickTomlin** [comment] 2016-04-21 22:45
I'm not able to reproduce this on a Windows 10 VM with the [example](https://github.com/angular/protractor/blob/master/example/example_spec.js). It sounds like there's an issue with your local setup that is causing Angular not to load.

I'm going to close this issue for now, please re-open a new one following the [Issue Template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) (including a reproducible example). Thanks! 😄

**Closed by NickTomlin** 2016-04-21 22:45 UTC

**Comment by felix307253927** [comment] 2016-04-22 05:07
@NickTomlin  My angularjs version is 1.2.29, and I update the angularjs version to 1.5.5 and it works. Why?
