### ISSUE TITLE
waitForAngular does not wait for $httpBackend pass through requests

### ISSUE THREAD

**Issue by mike-bresnahan** [angular/protractor#3948] opened 2017-01-09 20:42 UTC
`browser.waitForAngular()` does not wait for `$httpBackend` pass through requests. The root cause is that there are two `$browser` instances, one for mock `$httpBackend` requests and one for real `$httpBackend` requests (i.e. pass through requests) and protractor calls `notifyWhenNoOutstandingRequests()` on only the instance used for mock requests.

By "pass through requests" I mean those configured like this:

```javascript
    $httpBackend.whenGET(/.*/).passThrough();
```

I am able to reproduce this with a slightly modified angular-seed project.

```
$ git diff --ignore-space-change
diff --git a/app/app.js b/app/app.js
index 6ea2401..d1ac31e 100644
--- a/app/app.js
+++ b/app/app.js
@@ -3,12 +3,15 @@
```
```js
 // Declare app level module which depends on views, and components
 angular.module('myApp', [
        'ngRoute',
/* + */       'ngMockE2E',
        'myApp.view1',
        'myApp.view2',
        'myApp.version'
 ]).
//-config(['$locationProvider', '$routeProvider', function($locationProvider, $routeProvider) {
/* + */       config(['$locationProvider', '$routeProvider', '$provide', function($locationProvider, $routeProvider, $provide) {
        $locationProvider.hashPrefix('!');

        $routeProvider.otherwise({redirectTo: '/view1'});
//-}]);
/* + */}]).run(function ($httpBackend) {
/* + */       $httpBackend.whenGET(/.*/).passThrough();
/* + */});
```
```
diff --git a/app/index.html b/app/index.html
index ec9da03..c6e3046 100644
--- a/app/index.html
+++ b/app/index.html
@@ -33,6 +33,7 @@
```
```html
   -->
   <script src="bower_components/angular/angular.js"></script>
   <script src="bower_components/angular-route/angular-route.js"></script>
<!-- + -->  <script src="bower_components/angular-mocks/angular-mocks.js"></script>
   <script src="app.js"></script>
   <script src="view1/view1.js"></script>
   <script src="view2/view2.js"></script>
```

Then in angular.js, comment out this line in createHttpBackend().

```js
		  /*
        completeRequest(callback,
            status,
            response,
            xhr.getAllResponseHeaders(),
            statusText);
		  */
```

This will cause real HTTP requests to never complete, but Protractor won't wait.

Now run the e2e tests and watch them fail immediately without waiting for the HTTP request to complete.

Node v6.9.2
Protractor 4.0.14
Angular 1.5.8
Chrome 55.0.2883.87
Windows 7

**Comment by mike-bresnahan** [comment] 2017-01-10 17:36
Note that the second $browser instance is created in angular-mocks.js here:

```javascript
angular.module('ngMockE2E', ['ng']).config(['$provide', function($provide) {
  $provide.value('$httpBackend', angular.injector(['ng']).get('$httpBackend'));
  $provide.decorator('$httpBackend', angular.mock.e2e.$httpBackendDecorator);
}]);
```

**Comment by mike-bresnahan** [comment] 2017-01-10 20:09
This bug was introduced in this commit.

```javascript
commit 6685043ad40acc50d7088f87e2a71f76d2265306
Author: Andrew Schmadel <aschmadel@learningobjects.com>
Date:   Mon Oct 19 10:31:43 2015 -0400

    fix(ngMockE2E): allow $httpBackend.passThrough() to work when ngMock is loaded

    Allow $httpBackend.passThrough() to work normally when ngMock is loaded
    concurrently with ngMockE2E, as is typically the case when writing tests with
    angular.mock.module()

    Fixes #1434
    Closes #13124

diff --git a/src/ngMock/angular-mocks.js b/src/ngMock/angular-mocks.js
index 4ec4638..5bb2dc5 100644
--- a/src/ngMock/angular-mocks.js
+++ b/src/ngMock/angular-mocks.js
@@ -2328,6 +2328,7 @@ angular.module('ngMock', ['ng']).provider({
  * the {@link ngMockE2E.$httpBackend e2e $httpBackend} mock.
  */
 angular.module('ngMockE2E', ['ng']).config(['$provide', function($provide) {
+  $provide.value('$httpBackend', angular.injector(['ng']).get('$httpBackend'));
   $provide.decorator('$httpBackend', angular.mock.e2e.$httpBackendDecorator);
 }]);

diff --git a/test/ngMock/angular-mocksSpec.js b/test/ngMock/angular-mocksSpec.js
index 1cfe423..d3a2892 100644
--- a/test/ngMock/angular-mocksSpec.js
+++ b/test/ngMock/angular-mocksSpec.js
@@ -2150,12 +2150,12 @@ describe('ngMockE2E', function() {
     var hb, realHttpBackend, callback;

     beforeEach(function() {
-      module(function($provide) {
-        callback = jasmine.createSpy('callback');
+      callback = jasmine.createSpy('callback');
+      angular.module('ng').config(function($provide) {
         realHttpBackend = jasmine.createSpy('real $httpBackend');
         $provide.value('$httpBackend', realHttpBackend);
-        $provide.decorator('$httpBackend', angular.mock.e2e.$httpBackendDecorator);
       });
+      module('ngMockE2E');
       inject(function($injector) {
         hb = $injector.get('$httpBackend');
       });
```

**Comment by sjelin** [comment] 2017-01-10 22:51
Sorry, why are you using `ngMock` *and* Protractor?  `ngMock` is for unit testing, Protractor is for integration testing.  There are a number of ways these two don't play well together

**Comment by mike-bresnahan** [comment] 2017-01-10 23:11
This issue effects normal e2e tests, e.g. the ones in angular-seed. ngMock is not involved. If you clone angular-seed, modify it the way I describe, and then run the e2e tests, you will see the issue. It's also possible to see the problem via code inspection. This change https://github.com/angular/angular.js/pull/13124 caused there to be 2 $browser instances and thus 2 outstandingRequestCount variables. If you then look at waitForAngular in protractor, you will see that it will only wait for one of the outstandingRequestCount variables to be set to 0.

**Comment by mike-bresnahan** [comment] 2017-01-10 23:16
IMHO, the problem is with Angular and not with Protractor and this change https://github.com/angular/angular.js/pull/13124 should be reverted. I have created an angular issue: https://github.com/angular/angular.js/issues/15593.

**Comment by mike-bresnahan** [comment] 2017-01-10 23:19
BTW, downgrading to Angular 1.5.6 resolves the issue.

**Comment by sjelin** [comment] 2017-01-10 23:27
Yeah but you're adding angular mocks to the seed app.  Why would you ever do that?

**Comment by mike-bresnahan** [comment] 2017-01-10 23:32
I'm confused by your question. I added angular-mocks.js so that I could use ngMockE2E per the documentation. Is there some other way to use ngMockE2E.$httpBackend in e2e tests? 

https://docs.angularjs.org/api/ngMockE2E

**Comment by mike-bresnahan** [comment] 2017-01-10 23:35
Oh wait... are you are confused why I am using the angular-seed app in the first place? I am using it as a simple test case to demonstrate the issue.

**Comment by sjelin** [comment] 2017-01-11 00:23
Oh I see, never mind.  I didn't realize that `ngMockE2E` was from the same file as `ngMock`

**Comment by sjelin** [comment] 2017-01-11 00:39
But actually I'm still confused.  Unless your module depends on `ngMock`, that line from the PR you referenced should do nothing?  I guess I'll have to load up the seed app myself and look around

**Comment by petebacondarwin** [comment] 2017-01-11 09:45
I think the problem is indeed with Angular - so I think you can close this one.
@mike-bresnahan can you open a new issue in the angular.js repo for this?

**Comment by mike-bresnahan** [comment] 2017-01-11 16:20
Sjelin, if you are referring to this line, it is part of ngMockE2E. 

```javascript
angular.module('ngMockE2E', ['ng']).config(['$provide', function($provide) {
  $provide.value('$httpBackend', angular.injector(['ng']).get('$httpBackend'));
  $provide.decorator('$httpBackend', angular.mock.e2e.$httpBackendDecorator);
}]);
```

**Comment by petebacondarwin** [comment] 2017-01-11 16:31
I believe the problem is that `angular.injector(['ng'])` creates a brand new injector, which also creates new singleton objects for `$httpBackend` and `$browser`.

**Comment by sjelin** [comment] 2017-01-11 18:59
Closed in favor of https://github.com/angular/angular.js/issues/15593

**Closed by sjelin** 2017-01-11 18:59 UTC
Labels: status: needs investigation
